import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {brand} from './brand.js';
import {createPeacockFan,fanScale,fanTextureMB} from './valley-tail.js';
const B=brand.colors;
const rootUrl=new URL('../',import.meta.url);
export function createAssets(toon,resources,{originalCharacters=false,tailDown=false,peacockFan=false,environmentVariant=null}={}){
  const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);const states={pcock:'placeholder'},envModels={},envStates={};let textureMB=0;
  function ownModel(model,maxTriangles=30000,maxTexture=Infinity,original=false){let triangles=0,valid=true;const textures=new Set(),meshes=[];model.traverse(o=>{if(o.isMesh){triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;resources.own(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture){textures.add(v);if((v.image?.width||0)>maxTexture||(v.image?.height||0)>maxTexture)valid=false;}resources.own(m);}meshes.push(o);}});if(triangles>maxTriangles)valid=false;for(const t of textures){resources.own(t);textureMB+=(t.image?.width||0)*(t.image?.height||0)*4*4/3/1048576;}if(!valid)return false;for(const o of meshes){o.castShadow=true;if(original)continue;const source=Array.isArray(o.material)?o.material[0]:o.material;o.material=toon.material(source.color||B.text,{map:source.map||null,vertexColors:Boolean(o.geometry.attributes.color)});o.castShadow=true;toon.hull(o);}return true;}
  async function modelFile(url){const response=await fetch(url,{signal:AbortSignal.timeout(6000)});if(!response.ok||response.status===204)return null;const bytes=await response.arrayBuffer();if(bytes.byteLength<20)return null;return loader.parseAsync(bytes,new URL('.',url).href);}
  async function loadEnvironment(){try{const url=new URL(environmentVariant==='valley'?'assets/models/env/valley/manifest.json':'assets/models/env/manifest.json',rootUrl),r=await fetch(url);if(!r.ok)return;const manifest=await r.json();for(const [key,entry]of Object.entries(manifest.models||{})){envStates[key]='composed stand-in';if(!entry.enabled)continue;try{const gltf=await modelFile(new URL(entry.file,url));if(gltf&&ownModel(gltf.scene,Math.min(entry.maxTriangles||3000,entry.kind==='hero'?8000:3000),512)){envModels[key]=gltf.scene;envStates[key]='loaded';}}catch{envStates[key]='composed stand-in (unavailable)';}}}catch{}}
  function standIn(){if(peacockFan)textureMB+=fanTextureMB;const root=new THREE.Group(),body=new THREE.Group();root.add(body);const geos={sphere:resources.own(new THREE.IcosahedronGeometry(.5,1)),cylinder:resources.own(new THREE.CylinderGeometry(.5,.5,1,8)),cone:resources.own(new THREE.ConeGeometry(.5,1,8))};const mats=new Map();function piece(shape,color,x,y,z,sx,sy,sz,rx=0,rz=0){if(!mats.has(color))mats.set(color,toon.material(color,{rim:originalCharacters?0:.11}));const m=new THREE.Mesh(geos[shape],mats.get(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.rotation.set(rx,0,rz);body.add(m);if(!originalCharacters)toon.hull(m);return m;}
    piece('sphere',B.pulseBlue,0,.9,0,.9,1.25,.85);piece('cylinder',B.pulseCyan,0,1.55,.05,.3,.85,.3);piece('sphere',B.pulseBlue,0,2,.1,.6,.63,.6);piece('cone',B.gold,0,1.98,.51,.24,.42,.24,Math.PI/2);for(const side of [-1,1]){piece('sphere',B.bg,side*.22,2.1,.29,.09,.12,.11);piece('sphere',B.glow,side*.42,.95,-.05,.2,.8,.65);piece('cylinder',B.logoOrange,side*.2,.3,.05,.09,.52,.09);piece('sphere',B.gold,side*.2,.09,.2,.18,.1,.4);}for(let i=0;i<3;i++)piece('cone',B.gold,(i-1)*.1,2.4,.1,.07,.25,.07);
    const tail=peacockFan?createPeacockFan(resources):new THREE.Group();tail.position.set(0,.95,-.3);body.add(tail);const palette=[B.glow,B.accent,B.logoCoral,B.gold,B.logoOrange,B.pulseCyan,B.pulsePurple];for(let i=0;i<(peacockFan?0:7);i++){const a=(i-3)*.24,m=new THREE.Mesh(geos.sphere,toon.material(palette[i],{rim:originalCharacters?0:.11}));m.position.set(Math.sin(a)*1.1,Math.cos(a)*1.1,-.14);m.scale.set(.3,1.75,.13);m.rotation.z=-a;tail.add(m);if(!originalCharacters)toon.hull(m);}if(tailDown&&!peacockFan){tail.rotation.z=Math.PI;tail.position.y=1.35;tail.position.z=-.32;tail.scale.set(1,.55,.75);}if(peacockFan)tail.scale.setScalar(fanScale);return {root,body,tail,fallback:body,tailBaseScale:tail.scale.clone()};
  }
  async function loadPeacock(actor){try{const url=new URL('assets/manifest.json',rootUrl),r=await fetch(url);if(!r.ok)return;const manifest=await r.json(),entry=manifest.models?.pcock;if(!entry)return;states.pcock='loading';const gltf=await modelFile(new URL(entry.file.replace(/^\.\//,''),rootUrl));if(!gltf){states.pcock='placeholder (missing)';return;}if(!ownModel(gltf.scene,30000,Infinity,originalCharacters)){states.pcock='placeholder (budget)';return;}const model=gltf.scene,bounds=new THREE.Box3().setFromObject(model),size=new THREE.Vector3(),center=new THREE.Vector3();bounds.getSize(size);bounds.getCenter(center);const scale=2.25/Math.max(.01,size.y);model.scale.setScalar(scale);model.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);actor.root.add(model);actor.fallback.visible=false;const bone=model.getObjectByName('mixamorigHips')||model.getObjectByName('mixamorig:Hips');if(bone){bone.add(actor.tail);actor.tail.position.set(0,.04/scale,-.15/scale);actor.tail.scale.setScalar(1/scale);}else{actor.root.add(actor.tail);actor.tail.position.set(0,.95,-.3);}if(tailDown&&!peacockFan){actor.tail.rotation.z=Math.PI;actor.tail.position.set(0,.22/scale,-.32/scale);actor.tail.scale.set(1/scale,.55/scale,.75/scale);}if(peacockFan){actor.tail.rotation.set(0,0,0);actor.tail.position.set(0,-.10/scale,-.28/scale);actor.tail.scale.setScalar(fanScale/scale);actor.tail.userData.attachedBone=bone?.name||'root';}actor.tailBaseScale=actor.tail.scale.clone();actor.model=model;actor.mixer=new THREE.AnimationMixer(model);const run=gltf.animations.find(c=>/walking|running/i.test(c.name));if(run){actor.walk=actor.mixer.clipAction(run);actor.walk.setLoop(THREE.LoopRepeat,Infinity);actor.walk.clampWhenFinished=false;}actor.rest=[];for(const side of ['Left','Right']){const arm=model.getObjectByName('mixamorig'+side+'Arm')||model.getObjectByName('mixamorig:'+side+'Arm');if(arm){const rest=arm.quaternion.clone(),axis=new THREE.Vector3(0,0,1);arm.rotateOnAxis(axis,side==='Left'?-.95:.95);actor.rest.push({arm,rest,pose:arm.quaternion.clone()});}}states.pcock='loaded';}catch{states.pcock='placeholder (unavailable)';}}
  async function loadGuide(key,root){states[key]='placeholder';try{const r=await fetch(new URL('assets/manifest.json',rootUrl));if(!r.ok)return;const manifest=await r.json(),entry=manifest.models?.[key];if(!entry)return;const gltf=await modelFile(new URL(entry.file.replace(/^\.\//,''),rootUrl));if(!gltf||!ownModel(gltf.scene,20000,Infinity,originalCharacters)){states[key]='placeholder (missing)';return;}const model=gltf.scene,bounds=new THREE.Box3().setFromObject(model),size=new THREE.Vector3(),center=new THREE.Vector3();bounds.getSize(size);bounds.getCenter(center);const scale=(key==='liberty'?2.8:2.5)/Math.max(.01,size.y);model.scale.setScalar(scale);model.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);for(const side of ['Left','Right']){const arm=model.getObjectByName('mixamorig'+side+'Arm')||model.getObjectByName('mixamorig:'+side+'Arm');if(arm&&key==='pulse')arm.rotateZ(side==='Left'?-.8:.8);}root.add(model);states[key]='loaded';return model;}catch{states[key]='placeholder (unavailable)';}}
  function instantiateEnv(key){return envModels[key]?.clone(true);}
  return {states,envStates,envModels,loadEnvironment,standIn,loadPeacock,loadGuide,instantiateEnv,get textureMB(){return textureMB;}};
}
