import * as THREE from 'three';
import {applyBrandCss,brand} from './brand.js';
import {Resources} from './disposal.js';
import {createToon} from './toon.js';
import {createAssets} from './assets.js';
import {createRunnerRenderer} from './liberty-renderer.js';
import {createParticles} from './particles.js';
import {createAudio} from './audio.js';
import {createMiniHudEditor} from './mini-hud-editor.js';
import {ensureStyles} from './styles.js';
import {createCrossingWorld} from './crossing-world.js';
import {CROSSING_BUILD,STEP,laneAt,trafficAt,createCrossingLoop,clamp} from './crossing-loop.js';
const SETTINGS_KEY='pcock.crossing.settings.v1',RECORDS_KEY='pcock.crossing.records.v1';
const read=key=>{try{const o=JSON.parse(localStorage.getItem(key)||'{}');return o&&typeof o==='object'&&!Array.isArray(o)?o:{};}catch{return {};}};
const write=(key,data)=>{try{localStorage.setItem(key,JSON.stringify(data));return true;}catch{return false;}};
export async function bootCrossing(){
  await ensureStyles(['./fonts.css','./crossing.css']);applyBrandCss();
  const query=new URLSearchParams(location.search),funOnly=query.get('fun')==='1',root=document.getElementById('crossing-root'),mobile=(navigator.maxTouchPoints||0)>0||matchMedia('(pointer:coarse)').matches;
  root.className=mobile?'cx-mobile':'';
  root.innerHTML=`<div class="cx-world"></div><header class="cx-header"><a class="cx-brand" href="../index.html">PCOCK<small>LIBERTY CROSSING</small></a><div class="cx-actions"><a data-runner href="./gasless-run.html">RUNNER</a><a href="../index.html">← <span>Liberty World</span></a><button data-full>FULL</button><button data-settings>SETTINGS</button><button data-pause hidden>PAUSE</button></div></header>
  <section class="cx-menu"><span class="cx-eyebrow">A LIBERTY SWAP MINI-GAME</span><h1>WATCH.<br>WAIT.<br>CROSS.</h1><p>Same fearless peacock. A city full of traffic.<br>Find a gap, cross the road and reach the next safe island.</p><div class="cx-modes"><button data-mode="city" aria-pressed="true">CITY CROSSING<small>Reach Liberty Square</small></button><button data-mode="endless" aria-pressed="false">ENDLESS TRAFFIC<small>How far can you get?</small></button></div><button class="cx-primary cx-start" data-play>LET’S CROSS ↗</button><div class="cx-menu-foot"><span data-menu-best>2 LIVES · NO WALLET NEEDED</span><button data-how>HOW TO PLAY</button></div></section>
  <section class="cx-hud" hidden><div class="cx-scorebox"><div><small>ROWS CROSSED</small><strong data-rows>0</strong></div><div><small>SCORE</small><strong data-score>0</strong></div><div><div data-lives>♥ ♥</div><div data-flow>×1 FLOW</div></div></div><div class="cx-objectives"><b>THIS RUN</b><span data-goal-rows>Cross 40 rows · 0 / 40</span><span data-goal-seals>Collect 5 seals · 0 / 5</span><span data-goal-near>3 close calls · 0 / 3</span></div><div class="cx-route"><b data-region>LIBERTY PLAZA</b><div><i data-progress></i></div><small data-control-copy>WASD / ARROWS · SPACE FORWARD · ESC PAUSE</small></div><div class="cx-controls"><div class="cx-pad"><button data-move="up" aria-label="Move forward">↑</button><button data-move="left" aria-label="Move left">←</button><button data-move="down" aria-label="Move backward">↓</button><button data-move="right" aria-label="Move right">→</button></div><button class="cx-hop cx-primary" data-hop aria-label="Hop forward">↑<small>CROSS</small></button></div></section>
  <div class="cx-toast" role="status" hidden></div><section class="cx-overlay" hidden><div class="cx-panel" role="dialog" aria-modal="true" aria-labelledby="cx-panel-title"></div></section><div class="cx-beta">BETA · LIBERTY SWAP UNIVERSE</div><div class="cx-rotate"><b>TURN TO LANDSCAPE</b><span>The road is wider than it looks. Rotate your phone so you can see traffic coming from both sides.</span><a href="../index.html">← Return to Liberty World</a></div>`;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],defaults={preset:'Auto',renderScale:1,fpsCap:60,playerScale:2,reduceMotion:false,sfxVolume:.35,musicVolume:.12},settings={...defaults,...read(SETTINGS_KEY)};
  if(!['Auto','Low','Medium','High','Ultra'].includes(settings.preset))settings.preset='Auto';settings.renderScale=clamp(Number(settings.renderScale)||1,.6,1);settings.playerScale=clamp(Number(settings.playerScale)||2,.9,2.4);settings.fpsCap=[0,30,60,120].includes(settings.fpsCap)?settings.fpsCap:60;settings.sfxVolume=clamp(Number(settings.sfxVolume)||0,0,.5);settings.musicVolume=clamp(Number(settings.musicVolume)||0,0,.3);
  if(['Low','Medium','High','Ultra'].includes(query.get('preset')))settings.preset=query.get('preset');
  const resources=new Resources(),runtime=createRunnerRenderer($('.cx-world'),settings,resources),{scene,camera,renderer}=runtime,toon=createToon(resources),assets=createAssets(toon,resources,{originalCharacters:true,peacockFan:true}),actor=assets.standIn();scene.add(actor.root);await assets.loadPeacock(actor);
  if(assets.states.pcock!=='loaded')throw new Error('The original PCOCK character could not load. Reload the page to try again.');
  renderer.domElement.setAttribute('aria-label','Peacock road-crossing game');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;runtime.sun.intensity=3.1;scene.fog=new THREE.Fog('#dff6ff',105,330);scene.traverse(o=>{if(o.isHemisphereLight){o.intensity=2.1;o.color.set('#dff6ff');}});
  const world=createCrossingWorld(scene,resources,(await import('./liberty-renderer.js')).runnerProfiles[runtime.preset]),particles=createParticles(scene,resources),audio=createAudio(settings);
  const shadow=new THREE.Mesh(resources.own(new THREE.CircleGeometry(1.05,24)),resources.own(new THREE.MeshBasicMaterial({map:world.shadowTexture,transparent:true,opacity:.63,depthWrite:false})));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
  let screen='title',mode='city',loop,uiTime=0,toastTime=0,hudTime=0,held=null,holdAge=0,holdNext=.29,cameraSnap=true,lookZ=0,paid=false,settingsBack='title',records=read(RECORDS_KEY),saveWarning=false;
  if(funOnly)$('[data-runner]').href='./gasless-run.html?fun=1';const pendingKeys=new Set(),point=new THREE.Vector3(),goal=new THREE.Vector3(),look=new THREE.Vector3(),defaultForward=Math.PI;
  function blockedOrientation(){return mobile&&innerHeight>innerWidth;}
  function toast(message,life=false){$('.cx-toast').textContent=message;$('.cx-toast').hidden=false;$('.cx-toast').classList.toggle('cx-lastlife',life);toastTime=life?1.5:2.15;}
  function release(){held=null;holdAge=0;holdNext=.29;pendingKeys.clear();$$('.cx-pressed').forEach(b=>b.classList.remove('cx-pressed'));if(loop)loop.state.queued=null;}
  function setScreen(next){screen=next;release();$('.cx-menu').hidden=next!=='title';$('.cx-hud').hidden=next!=='run';$('.cx-overlay').hidden=['run','title'].includes(next);$('[data-pause]').hidden=next!=='run';$('.cx-beta').hidden=next!=='title';document.activeElement?.blur();}
  function commitRecord(){if(paid)return;paid=true;if(funOnly)return;const s=loop.state,old=records[mode];if(!old||s.score>(Number(old.score)||0)||s.score===old.score&&s.maxRow>(Number(old.rows)||0)){records[mode]={score:s.score,rows:s.maxRow,seals:s.seals,seconds:Math.round(s.age*10)/10};saveWarning=!write(RECORDS_KEY,records);}}
  function onEvent(type,message){if(type==='life'){release();audio.sound('damage');toast(message,true);}else if(type==='crash'){release();audio.sound('damage');toast(message);commitRecord();}else if(type==='over'||type==='win'){commitRecord();showResults(type==='win');}else{if(['seal','slow','near','checkpoint'].includes(type))audio.sound(type==='near'?'jump':'buy');if(type!=='start')toast(message);if(type==='resume')cameraSnap=true;}}
  function resetRun(){loop=createCrossingLoop({mode,seed:414},onEvent);world.reset();particles.reset();paid=false;cameraSnap=true;lookZ=0;$('.cx-toast').hidden=true;toastTime=0;release();world.update(loop.state,0);}
  function play(){resetRun();setScreen('run');loop.start();audio.unlock();toast('TIME YOUR CROSSING · SAFE ISLANDS ARE GREEN');paintHud();}
  function title(){resetRun();setScreen('title');const best=records[mode];$('[data-menu-best]').textContent=funOnly?'FUN MODE · NOTHING SAVED':best?'BEST '+best.rows+' ROWS · '+best.score+' POINTS':'2 LIVES · NO WALLET NEEDED';$$('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));}
  function panel(titleText,kicker='LIBERTY CROSSING'){const p=$('.cx-panel');p.replaceChildren();const tag=document.createElement('span');tag.className='cx-eyebrow';tag.textContent=kicker;const h=document.createElement('h2');h.id='cx-panel-title';h.textContent=titleText;p.append(tag,h);return p;}
  function text(p,t,cls=''){const e=document.createElement('p');e.className=cls;e.textContent=t;p.append(e);return e;}
  function button(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;b.className=primary?'cx-primary':'';b.onclick=fn;return b;}
  function actions(p,...buttons){const r=document.createElement('div');r.className='cx-panel-actions';r.append(...buttons);p.append(r);}
  function pause(){if(screen!=='run')return;setScreen('pause');const p=panel('TAKE A BREATHER');text(p,'Traffic is paused. Your crossing is exactly where you left it.');actions(p,button('Resume',()=>setScreen('run'),true),button('Settings',showSettings),button('Choose mode',title));}
  function showHow(){setScreen('how');const p=panel('READ THE ROAD');text(p,'Move one step at a time, or hold a direction to keep moving. Stay on the green islands to watch for a gap. You can always wait there safely.');text(p,'PC: WASD or arrow keys. Space moves forward. Escape pauses. Mobile: tap CROSS, use the four-way pad, or swipe on the game. A tap on the game also moves forward. There is no crouch control.');text(p,'Gold rings are Liberty seals. Cyan diamonds trigger a Green Wave, slowing traffic for 4.5 seconds. Passing close to a car without being hit earns a close-call bonus. Five quick forward steps build your score multiplier.');text(p,'Two lives per run. The first hit returns you to the last safe island. The second leaves your flag and ends the run. City Crossing ends at Liberty Square; Endless Traffic continues with gradually faster lanes.');text(p,'A hop is a movement animation, not an invincibility jump. You must still avoid every vehicle. Car shapes, traffic directions and lane speeds differ.');text(p,'No real currency or transactions. This mini-game never awards or spends Liberty World or Runner progress. '+(funOnly?'Fun Mode also saves no scores or records.':'Only its own settings and personal best are saved locally.'),'cx-note');actions(p,button('Back',title,true));}
  function showResults(win){release();setScreen('results');const p=panel(win?'YOU MADE IT.':'ONE MORE CROSSING?',win?'LIBERTY SQUARE':'END OF THE ROAD'),s=loop.state;const grid=document.createElement('div');grid.className='cx-results';for(const [label,value]of [['ROWS',s.maxRow],['SCORE',s.score],['SEALS',s.seals]]){const d=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=value;small.textContent=label;d.append(strong,small);grid.append(d);}p.append(grid);text(p,s.nearMisses+' close calls · '+Math.round(s.age)+' seconds · '+(mode==='city'?'City Crossing':'Endless Traffic'));text(p,funOnly?'FUN MODE · Practice run only. No scores or campaign progress saved.':saveWarning?'This browser could not save your personal best.':'Personal best: '+(records[mode]?.rows||0)+' rows / '+(records[mode]?.score||0)+' points. Liberty World and Runner progress are unchanged.','cx-note');actions(p,button('Try again',play,true),button('Choose mode',title),button('Return to Valley',()=>location.assign('../index.html')));}
  function showSettings(){if(screen==='settings')return;settingsBack=screen;setScreen('settings');const p=panel('YOUR WAY TO CROSS');
    function select(label,key,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');for(const [v,t]of options){const o=document.createElement('option');o.value=v;o.textContent=t;o.selected=String(settings[key])===String(v);s.append(o);}s.onchange=()=>{settings[key]=key==='fpsCap'?Number(s.value):s.value;runtime.applySettings();write(SETTINGS_KEY,settings);};l.append(s);p.append(l);}
    select('Visual quality','preset',['Auto','Low','Medium','High','Ultra'].map(x=>[x,x]));select('Frame limit','fpsCap',[[60,'60 FPS'],[30,'30 FPS'],[120,'120 FPS'],[0,'Unlimited']]);
    const l=document.createElement('label');l.textContent='PCOCK size';const range=document.createElement('input');range.type='range';range.min='.9';range.max='2.4';range.step='.05';range.value=settings.playerScale;range.setAttribute('aria-label','PCOCK size');range.oninput=()=>{settings.playerScale=Number(range.value);write(SETTINGS_KEY,settings);};l.append(range);p.append(l);
    for(const [label,key]of [['Reduced motion','reduceMotion'],['Sound and music','sound']]){const l=document.createElement('label');l.textContent=label;const c=document.createElement('input');c.type='checkbox';c.checked=key==='sound'?settings.sfxVolume>0:settings.reduceMotion;c.onchange=()=>{if(key==='sound'){settings.sfxVolume=c.checked?.35:0;settings.musicVolume=c.checked?.12:0;audio.apply();}else settings.reduceMotion=c.checked;write(SETTINGS_KEY,settings);};l.append(c);p.append(l);}
    text(p,'This uses the Runner renderer and character. Size is visual only: it never changes collision difficulty.','cx-note');actions(p,button('Back',()=>{if(settingsBack==='run'||settingsBack==='pause'){setScreen('run');if(settingsBack==='pause')pause();}else if(settingsBack==='results')showResults(loop.state.phase==='win');else title();},true),button('Resize HUD',()=>{setScreen('hudedit');$('.cx-overlay').hidden=true;const returnScreen=settingsBack;hudEditor.choose(()=>{screen=returnScreen;showSettings();settingsBack=returnScreen;});}));
  }
  async function fullscreen(){try{let doc=document;try{if(parent!==window&&parent.location.origin===location.origin)doc=parent.document;}catch{}if(doc.fullscreenElement)await doc.exitFullscreen();else await doc.documentElement.requestFullscreen({navigationUI:'hide'});}catch{toast('Fullscreen is controlled by your browser.');}}
  const directions={up:[0,1],left:[-1,0],down:[0,-1],right:[1,0]};
  function move(name){if(screen!=='run'||blockedOrientation())return false;const d=directions[name];if(!d)return false;const ok=loop.request(...d);if(ok){audio.sound('jump');particles.emit(loop.state.x,.06,loop.state.z);}return ok;}
  function hold(name,element){release();move(name);held=name;holdAge=0;holdNext=.29;element?.classList.add('cx-pressed');}
  for(const b of $$('[data-move],[data-hop]')){b.addEventListener('pointerdown',e=>{if(screen!=='run')return;e.preventDefault();b.setPointerCapture(e.pointerId);hold(b.dataset.move||'up',b);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,release);}
  const keyNames={ArrowUp:'up',KeyW:'up',Space:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};
  function onKey(e){if(['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName))return;if(keyNames[e.code]&&screen==='run'){e.preventDefault();if(!e.repeat){hold(keyNames[e.code]);pendingKeys.add(e.code);}}else if(e.code==='Escape'){e.preventDefault();if(screen==='run')pause();else if(screen==='pause')setScreen('run');}else if(e.code==='KeyF'&&!e.repeat)fullscreen();else if(e.code==='KeyR'&&!e.repeat&&screen==='results')play();}
  const upKey=e=>{if(pendingKeys.has(e.code))release();};addEventListener('keydown',onKey);addEventListener('keyup',upKey);
  let gesture=null;const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{if(screen!=='run'||e.button>0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);gesture={id:e.pointerId,x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(!gesture||gesture.id!==e.pointerId)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;gesture=null;move(Math.hypot(dx,dy)<18?'up':Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});canvas.addEventListener('pointercancel',()=>gesture=null);
  const blur=()=>{release();gesture=null;if(screen==='run')pause();},visibility=()=>{if(document.hidden)blur();},resize=()=>{if(blockedOrientation())blur();cameraSnap=true;};addEventListener('blur',blur);addEventListener('visibilitychange',visibility);addEventListener('resize',resize);
  $('[data-play]').onclick=play;$('[data-how]').onclick=showHow;$('[data-pause]').onclick=pause;$('[data-full]').onclick=fullscreen;$('[data-settings]').onclick=showSettings;for(const b of $$('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;title();};
  const hudEditor=createMiniHudEditor(root,{storageKey:'pcock.crossing.hud.v1',layoutType:'PCOCK_CROSSING_HUD_V1',targets:[['header','HEADER','.cx-header'],['score','SCORE & LIVES','.cx-scorebox'],['goals','CHALLENGES','.cx-objectives'],['progress','ROUTE','.cx-route'],['pad','DIRECTION PAD','.cx-pad'],['hop','CROSS BUTTON','.cx-hop']],previewSelectors:['.cx-hud','.cx-controls'],previewCss:'.pcock-mini-hud-editing .cx-controls{display:block!important}',onEnter:release});
  function setText(selector,value){const e=$(selector);if(e.textContent!==String(value))e.textContent=value;}
  function paintHud(){const s=loop.state;setText('[data-rows]',s.maxRow);setText('[data-score]',s.score);setText('[data-lives]',s.lives===2?'♥ ♥':s.lives===1?'♥ · LAST LIFE':'OUT');setText('[data-flow]','×'+s.combo+' FLOW');setText('[data-goal-rows]',(s.maxRow>=40?'✓ ':'')+'Cross 40 rows · '+Math.min(40,s.maxRow)+' / 40');setText('[data-goal-seals]',(s.seals>=5?'✓ ':'')+'Collect 5 seals · '+Math.min(5,s.seals)+' / 5');setText('[data-goal-near]',(s.nearMisses>=3?'✓ ':'')+'3 close calls · '+Math.min(3,s.nearMisses)+' / 3');const row=Math.round(-s.z/STEP),lane=laneAt(row);setText('[data-region]',s.slowTime>0?'GREEN WAVE · '+s.slowTime.toFixed(1)+'s':lane.kind==='safe'?'SAFE ISLAND · WATCH BOTH WAYS':lane.direction>0?'TRAFFIC → · LOOK LEFT':'← TRAFFIC · LOOK RIGHT');$('[data-progress]').style.width=(mode==='city'?Math.min(100,s.maxRow/97*100):(s.maxRow%80)/80*100)+'%';}
  function fixed(dt){if(screen!=='run'||blockedOrientation())return;if(held&&loop.state.phase==='run'){holdAge+=dt;if(holdAge>=holdNext){move(held);holdNext+=.23;}}loop.step(dt);}
  function interpolate(alpha,dt){if(!loop)return;uiTime+=dt;toastTime-=dt;if(toastTime<=0)$('.cx-toast').hidden=true;const s=loop.state,active=screen==='run',blend=active&&s.phase==='run'?alpha:1,x=s.px+(s.x-s.px)*blend,z=s.pz+(s.z-s.pz)*blend,jump=s.previousHopY+(s.hopY-s.previousHopY)*blend;
    actor.root.position.set(x,.05+jump,z);actor.root.scale.setScalar(settings.playerScale);const angle=Math.atan2(Math.sin(s.facing-actor.root.rotation.y),Math.cos(s.facing-actor.root.rotation.y));actor.root.rotation.y+=angle*Math.min(1,dt*20);
    const walking=active&&s.phase==='run'&&!!s.move;if(walking){if(actor.walk&&!actor.walk.isRunning())actor.walk.reset().play();actor.walk?.setEffectiveTimeScale(1.8);actor.mixer?.update(dt);}else{actor.walk?.stop();for(const a of actor.rest||[])a.arm.quaternion.copy(a.pose);}
    actor.tail.animate?.(dt,{speed:walking?7:0,gliding:false,reduceMotion:settings.reduceMotion});actor.root.visible=s.grace<=0||Math.sin(uiTime*23)>.1;
    if(s.phase==='crash'||s.phase==='over'){actor.root.rotation.z=settings.reduceMotion?0:-.55;actor.root.position.y=.12;}else actor.root.rotation.z=0;
    shadow.position.set(x,.036,z);shadow.scale.setScalar(settings.playerScale*(1-jump*.16));particles.update(dt);
    const response=cameraSnap?1:1-Math.exp(-dt*9);lookZ+=(z-lookZ)*response;const menu=screen==='title',crash=s.phase==='crash'&&!settings.reduceMotion,centerX=menu?5:x*.32;goal.set(centerX+4+(crash?Math.sin((2.1-s.recovery)*1.1)*3:0),camera.aspect<1.4?32:27,lookZ+26);look.set(centerX,1,lookZ-11);camera.position.lerp(goal,response);camera.up.set(0,1,0);camera.lookAt(look);camera.fov=50;camera.updateProjectionMatrix();cameraSnap=false;
    toon.time.value=settings.reduceMotion?0:uiTime;renderer.getDrawingBufferSize(toon.resolution.value);world.update(screen==='title'?{...s,clock:uiTime}:s,uiTime,camera);audio.setMood({region:0,intensity:active?.3+(s.slowTime>0?.2:0):.08});audio.update(dt);hudTime+=dt;if(hudTime>.1){hudTime=0;paintHud();}
  }
  function report(){return {build:CROSSING_BUILD,screen,mode,funOnly,assets:assets.states,sourceRenderer:'Liberty Runner',vehicleSource:'Most Wanted R71 classic fleet',...runtime.metrics,world:world.stats,run:loop.snapshot(),records:structuredClone(records),saveWarning,errors:window.__PCOCK_ERRORS||[]};}
  window.PCOCK={ready:false,report,get settings(){return {...settings};}};
  // Debug controls exist only behind the explicit QA query, never in normal play.
  if(query.get('qa')==='1')window.PCOCK.qa={loop:()=>loop,jumpToSafe(row){row=Math.max(1,Math.floor(row/8)*8+1);Object.assign(loop.state,{row,col:0,x:0,px:0,z:-row*STEP,pz:-row*STEP,hopY:0,previousHopY:0,maxRow:row,checkpoint:row,move:null,queued:null});cameraSnap=true;world.reset();},hit(){loop.hit({id:'qa-collision'});}};
  runtime.setRunning(()=>screen==='run'&&!blockedOrientation());runtime.setQualityHandler(p=>world.setQuality(p));title();await renderer.compileAsync(scene,camera);runtime.start(fixed,interpolate);window.PCOCK.ready=true;
  resources.onDispose(()=>{hudEditor.dispose();audio.dispose();removeEventListener('keydown',onKey);removeEventListener('keyup',upKey);removeEventListener('blur',blur);removeEventListener('visibilitychange',visibility);removeEventListener('resize',resize);});addEventListener('pagehide',()=>resources.dispose(),{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
}
