import {GAME_IDS, levelFromXp} from './save.js';
import {gameEnabled} from './game-availability.js';
import {utcDay} from './rng.js';
export const currencies=Object.freeze({'gasless-run':'Coins','peg-keeper':'Peg Points','ghost-route':'Ghost Shards'});
export const achievements=Object.freeze([
  ['first-run','First flight','runs',1],['five-runs','Finding a rhythm','runs',5],['twenty-runs','Frequent flyer','runs',20],
  ['first-upgrade','A better flight','purchases',1],['five-upgrades','Fine feathers','purchases',5],
  ['first-pickup','A bright find','pickups',1],['twenty-pickups','Collector','pickups',20],['hundred-pickups','Treasure trail','pickups',100],
  ['first-jump','Off the ground','jumps',1],['twenty-jumps','Spring wings','jumps',20],
  ['hundred-metres','A little further','distance',100],['kilometre','Long way home','distance',1000],
  ['first-feathers','Shared freedom','feathers',1],['hundred-feathers','Color keeper','feathers',100],
  ['level-two','Growing wings','level',2],['level-five','High flyer','level',5],
  ['first-star','A little star','stars',1],['nine-stars','Constellation','stars',9],
  ['daily-three','Three sunrises','streak',3],['two-games','Both journeys','games',2]
].map(([id,title,metric,target])=>Object.freeze({id,title,metric,target})));
export function createEconomy(save){
  function unlockAchievements(state){const all=Object.entries(state.games).filter(([id])=>gameEnabled(id)).map(([,game])=>game),values={runs:all.reduce((s,g)=>s+g.runs,0),purchases:all.reduce((s,g)=>s+Object.values(g.upgrades).reduce((a,b)=>a+b,0),0),pickups:all.reduce((s,g)=>s+g.stats.pickups,0),jumps:all.reduce((s,g)=>s+g.stats.jumps,0),distance:all.reduce((s,g)=>s+g.stats.distance,0),feathers:state.profile.feathers,level:levelFromXp(state.profile.xp),stars:all.reduce((s,g)=>s+Object.values(g.stars).reduce((a,b)=>a+b,0),0),streak:Math.max(...all.map(g=>g.daily.streak)),games:all.filter(g=>g.runs>0).length};for(const a of achievements)if(values[a.metric]>=a.target&&!state.profile.achievements.includes(a.id))state.profile.achievements.push(a.id);}
  function quote(id,item){const g=save.state.games[id];if(!g)return null;const level=g.upgrades[item.id]||0;return {level,cost:item.kind==='upgrade'?Math.round(item.cost*item.growth**level):item.cost,maxed:item.kind==='upgrade'&&level>=item.max};}
  function purchase(id,item){if(!GAME_IDS.includes(id)||!item||!['upgrade','boost','skin'].includes(item.kind))return {ok:false,reason:'Unknown item'};const q=quote(id,item),g=save.state.games[id];if(q.maxed||item.kind==='skin'&&g.skins.includes(item.id))return {ok:false,reason:'Already owned'};if(!Number.isSafeInteger(q.cost)||q.cost<0||q.cost>g.currency)return {ok:false,reason:'Not enough '+currencies[id]};save.update(s=>{const target=s.games[id];target.currency-=q.cost;if(item.kind==='upgrade')target.upgrades[item.id]=(target.upgrades[item.id]||0)+1;if(item.kind==='boost')target.boosts[item.id]=Math.min(99,(target.boosts[item.id]||0)+1);if(item.kind==='skin')target.skins.push(item.id);unlockAchievements(s);});return {ok:true,cost:q.cost};}
  function missionMultiplier(id){return 1+Math.min(10,save.state.games[id].missions.tier)*.1;}
  function award(id,result,missionConfig=[]){if(!GAME_IDS.includes(id)||!result||typeof result.id!=='string')return {ok:false};if(save.state.receipts.includes(result.id))return {ok:false,duplicate:true};const g=save.state.games[id],earnings=Math.max(0,Math.floor(Number.isFinite(result.earned)?result.earned:0)),multiplier=missionMultiplier(id),currency=Math.floor(earnings*multiplier),xp=Math.max(10,Math.min(500,Math.floor(result.xp||currency/2))),before=levelFromXp(save.state.profile.xp),previousBest=g.best;let completedSet=false,missionBonus=0,feathers=Math.floor(currency*.1);
    save.update(s=>{const target=s.games[id];target.runs++;target.currency+=currency;s.profile.feathers+=feathers;s.profile.xp+=xp;target.best=Math.max(target.best,Math.floor(result.score||0));target.top.push({score:Math.floor(result.score||0),date:utcDay()});target.top.sort((a,b)=>b.score-a.score);target.top.length=Math.min(10,target.top.length);for(const key of Object.keys(target.stats))target.stats[key]+=Math.max(0,Math.floor(result.stats?.[key]||0));const tier=target.missions.tier;for(let i=0;i<3;i++){const mission=missionConfig[i];if(mission)target.missions.progress[i]+=Math.max(0,Math.floor(result.stats?.[mission.metric]||0));}if(missionConfig.length===3&&missionConfig.every((m,i)=>target.missions.progress[i]>=Math.ceil(m.target*(1+tier*.25)))){completedSet=true;missionBonus=30+10*tier;target.currency+=missionBonus;const bonusFeathers=Math.floor(missionBonus*.1);s.profile.feathers+=bonusFeathers;feathers+=bonusFeathers;target.missions.tier++;target.missions.progress=[0,0,0];}const missionId=result.mission||'foundation-course';target.stars[missionId]=Math.max(target.stars[missionId]||0,Math.max(1,Math.min(3,result.stars||1)));target.tutorialSeen=true;target.featureUnlocks=['play','settings','how','store','characters','missions','leaderboard','daily'];if(result.daily&&target.daily.date!==utcDay()){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);target.daily.streak=target.daily.date===yesterday?target.daily.streak+1:1;target.daily.date=utcDay();}s.receipts.push(result.id);s.receipts=s.receipts.slice(-100);unlockAchievements(s);});
    return {ok:true,currency,feathers,xp,multiplier,missionBonus,completedSet,newBest:result.score>previousBest,levelUp:levelFromXp(save.state.profile.xp)>before};
  }
  function spendRevive(id,cost=20){const g=save.state.games[id];if(!g||g.currency<cost)return false;save.update(s=>{s.games[id].currency-=cost;});return true;}
  return {quote,purchase,award,missionMultiplier,spendRevive,consumeBoost(id,key){const g=save.state.games[id];if(!(g?.boosts[key]>0))return false;save.update(s=>s.games[id].boosts[key]--);return true;}};
}
