import * as THREE from 'three';
import {brand,applyBrandCss} from './brand.js';
import {worldPalette as W} from './world-palette.js';
import {Resources,spring} from './disposal.js';
import {createParticles} from './particles.js';
import {createSave} from './save.js';
import {createEconomy} from './economy.js';
import {shellConfig} from './shell-config.js';
import {rng,hashSeed,utcDay} from './rng.js';
import {createRenderer,profiles} from './renderer.js';
import {createToon} from './toon.js';
import {createTerrain,heightAt} from './terrain.js';
import {createSky} from './sky.js';
import {createAssets} from './assets.js';
import {createKit} from './kit.js';
import {createHud,element} from './hud-kit.js';
import {createInput} from './input.js';
import {createAudio} from './audio.js';
import {createGameShell} from './game-shell.js';
import {createDebug} from './debug.js';
import {ensureStyles} from './styles.js';
await ensureStyles(['./fonts.css','./foundation.css']);
applyBrandCss();document.body.classList.add('foundation');
const params=new URLSearchParams(location.search),shot=params.get('shot'),resources=new Resources(),save=createSave();
const config=shellConfig(document.body.dataset.game||params.get('game')||'gasless-run');
const settings=new Proxy({},{get:(_,key)=>save.state.settings[key],set:(_,key,value)=>{save.state.settings[key]=value;return true;}});
if(['Auto','Low','Medium','High','Ultra'].includes(params.get('preset')))settings.preset=params.get('preset');
const root=document.getElementById('foundation-root')||document.body.appendChild(element('main','pc-root'));root.replaceChildren();root.className='pc-root';root.setAttribute('aria-label','Feathers of Liberty shared foundation');
const world=element('div','pc-world'),grade=element('div','pc-grade'),brandbar=element('header','pc-brandbar');brandbar.innerHTML='<a class="pc-mark" href="./index.html">PCOCK<small>FEATHERS OF LIBERTY</small></a><span class="pc-stage-tag">S1 · FOUNDATION</span>';brandbar.querySelector('a').href=config.returnUrl;root.append(world,grade,brandbar);
if(location.protocol==='file:'){root.innerHTML='<section class="pc-file-message"><h1>PCOCK</h1><p>Open this game through a local web server.</p><p>Run node tools/serve.mjs in this folder, then visit http://127.0.0.1:8080/pcock/.</p></section>';throw new Error('A local web server is required.');}
await document.fonts.ready;await Promise.all([document.fonts.load('400 24px "Soloist Extra Italic"'),document.fonts.load('400 16px "BT Beau Sans"')]);
const runtime=createRenderer(world,settings,resources),{scene,camera,renderer}=runtime,toon=createToon(resources),assets=createAssets(toon,resources),terrain=createTerrain(scene,toon,resources),sky=createSky(scene,toon,resources);
await assets.loadEnvironment();const kit=createKit(scene,toon,resources,assets),actor=assets.standIn();scene.add(actor.root);actor.root.position.set(0,heightAt(0,8),8);actor.root.rotation.y=Math.PI;
const blob=new THREE.Mesh(resources.own(new THREE.CircleGeometry(.55,16)),resources.own(new THREE.MeshBasicMaterial({color:W.outline,transparent:true,opacity:.25,depthWrite:false})));blob.rotation.x=-Math.PI/2;scene.add(blob);
const hud=createHud(root,save,config),input=createInput(renderer.domElement,hud.hud,settings),audio=createAudio(settings),economy=createEconomy(save);
resources.onDispose(()=>{save.dispose();audio.dispose();input.dispose();hud.dispose();});
const player={position:new THREE.Vector3(0,heightAt(0,8),8),previous:new THREE.Vector3(),velocityY:0,onGround:true,coyote:.1,glide:1.5,yaw:0,speed:0},drawPosition=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),cameraGoal=new THREE.Vector3(),bubblePoint=new THREE.Vector3(),size=new THREE.Vector2();
let dashLeft=0,dashCooldown=0;
let active=false,paused=true,turning=false,worldTime=0,runAge=0,yaw=.45,pitch=.38,score=0,picked=0,jumps=0,distance=0,runIndex=0,runId='',daily=false,courseSeed=hashSeed('foundation'),revived=false,railHint=false,activeChunks=16,currentSkin='original',signature=1.5,magnet=1,dashSpeed=9,shake=0,previousScreen='',settingsVersion=0;
const squash={value:1,velocity:0},cameraSprings=[{value:16,velocity:0},{value:10,velocity:0},{value:22,velocity:0}],pickups=[],pickupGeo=resources.own(new THREE.IcosahedronGeometry(.5,1)),pickupMat=toon.material(brand.colors.gold),pickupEdge=toon.outline(toon.tint(brand.colors.gold));
for(let i=0;i<5;i++){const group=new THREE.Group(),mesh=new THREE.Mesh(pickupGeo,pickupMat),hull=new THREE.Mesh(pickupGeo,pickupEdge);mesh.scale.set(.32,1.3,.15);hull.scale.copy(mesh.scale);group.add(hull,mesh);group.position.set(i===2?-.65:0,1.25,7-i*4);scene.add(group);pickups.push({group,x:group.position.x,z:group.position.z,collected:false});}
const beacon=new THREE.Group(),beaconGeo=resources.own(new THREE.TorusGeometry(.9,.12,7,18)),beaconMesh=new THREE.Mesh(beaconGeo,toon.material(brand.colors.accent));beacon.add(beaconMesh);toon.hull(beaconMesh);beacon.position.set(0,1.6,-15);scene.add(beacon);
let stressGroup=null;if(params.has('stress')){stressGroup=new THREE.Group();const geo=resources.own(new THREE.IcosahedronGeometry(.5,0)),mesh=new THREE.InstancedMesh(geo,toon.material(brand.colors.text),600),hull=new THREE.InstancedMesh(geo,toon.outline(brand.colors.glow),600),dummy=new THREE.Object3D(),color=new THREE.Color(),random=rng(10091);resources.own(mesh);resources.own(hull);for(let i=0;i<600;i++){const x=(random()-.5)*50,z=(random()-.5)*55;dummy.position.set(x,heightAt(x,z)+.4,z);dummy.scale.setScalar(.2+random()*.6);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);hull.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,color.set(i%2?brand.colors.primary:brand.colors.accent));}stressGroup.add(hull,mesh);scene.add(stressGroup);}
function refreshUpgrades(){const g=save.state.games[config.id];signature=1.5+(g.upgrades.signature||0)*.7;dashSpeed=9+(config.id==='peg-keeper'?(g.upgrades.signature||0)*1.5:0);magnet=1+(g.upgrades.magnet||0)*.5;setSkin(g.skin);}
function setSkin(id){currentSkin=id;if(typeof hat!=='undefined')hat.visible=id==='wayfarer-hat';if(typeof particles!=='undefined')particles.setEmber(id==='ember-trail');const colors=id==='signal-tail'?[brand.colors.pulseCyan,brand.colors.pulseBlue,brand.colors.pulsePurple,brand.colors.pulseMagenta,brand.colors.pulseRed,brand.colors.pulseCyan,brand.colors.pulsePurple]:[brand.colors.glow,brand.colors.accent,brand.colors.logoCoral,brand.colors.gold,brand.colors.logoOrange,brand.colors.pulseCyan,brand.colors.pulsePurple];let i=0;for(const m of actor.tail.children)if(m.isMesh&&!m.userData.hull){m.material.color.set(colors[i]);const next=actor.tail.children[actor.tail.children.indexOf(m)+1];if(next?.userData.hull)next.material.color.copy(toon.tint(colors[i]));i++;}}
function settingsChanged(){runtime.applySettings();kit.setFoliage(settings.foliage);grade.hidden=settings.postFX==='off';runtime.renderer.shadowMap.enabled=settings.shadows==='real'&&['High','Ultra'].includes(runtime.preset);runtime.sun.castShadow=runtime.renderer.shadowMap.enabled;runtime.sun.shadow.mapSize.set(512,512);runtime.sun.shadow.camera.left=runtime.sun.shadow.camera.bottom=-35;runtime.sun.shadow.camera.right=runtime.sun.shadow.camera.top=35;root.classList.toggle('pc-color-safe',settings.colorSafe);settingsVersion++;}
const particles=createParticles(scene,resources);let dustAge=0;
const hat=new THREE.Group();const cap=new THREE.Mesh(resources.own(new THREE.ConeGeometry(.35,.45,8)),toon.material(brand.colors.glow));cap.position.y=2.5;hat.add(cap);toon.hull(cap);const band=new THREE.Mesh(resources.own(new THREE.CylinderGeometry(.3,.3,.07,8)),toon.material(brand.colors.gold));band.position.y=2.29;hat.add(band);toon.hull(band);actor.root.add(hat);hat.visible=false;
const adapter={begin({daily:dailyRun}){refreshUpgrades();hud.reset();particles.reset();daily=dailyRun;runIndex++;runId=config.id+'|'+Date.now()+'|'+runIndex;active=true;paused=false;turning=false;yaw=0;dashLeft=dashCooldown=0;player.onGround=true;player.coyote=.1;runAge=0;score=0;picked=jumps=distance=0;revived=false;railHint=false;player.position.set(0,heightAt(0,8),8);player.previous.copy(player.position);player.velocityY=0;player.glide=signature;courseSeed=hashSeed(daily?config.id+'|'+utcDay():'foundation');const dailyRandom=rng(courseSeed);for(let i=0;i<pickups.length;i++){const p=pickups[i];p.x=daily?(dailyRandom()-.5)*1.3:(i===2?-.65:0);p.group.position.x=p.x;p.collected=false;p.group.visible=true;}if(economy.consumeBoost(config.id,'head-start')){score+=10;hud.feedback('score','BRIGHT START!');}input.enable(true);hud.show(true);},pause(value){paused=value;input.enable(!value&&active);hud.show(!value&&active);},exit(){active=false;input.enable(false);hud.show(false);},revive(){revived=true;paused=false;active=true;runAge=Math.min(runAge,15);player.position.set(0,heightAt(0,8),8);player.velocityY=0;input.enable(true);hud.show(true);},refreshUpgrades,settingsChanged,setSkin,turntable(value){turning=value;input.enable(value||(!paused&&active));},screenChanged(name){previousScreen=name;if(name==='title'||name==='characters'){actor.root.position.set(3,heightAt(3,5),5);actor.root.rotation.y=-.5;}}};
const shell=createGameShell(root,{save,economy,config,audio,adapter,shot});resources.onDispose(()=>shell.dispose());hud.onPause(()=>shell.open('pause'));hud.onFinish(()=>finish());
function finish(){if(!active||paused||picked<3||jumps<1||Math.hypot(player.position.x,player.position.z+15)>3.4)return;paused=true;active=false;input.enable(false);hud.feedback('streak','FREEDOM!');shell.finish({id:runId,score,earned:Math.max(50,picked*12),xp:40+picked*5,stars:picked>=5?3:2,success:true,revived,daily,stats:{distance:Math.floor(distance),jumps,pickups:picked}});}
const interact=e=>{if(e.code==='KeyE'&&Math.hypot(player.position.x,player.position.z+15)<3.4)finish();};addEventListener('keydown',interact);resources.onDispose(()=>removeEventListener('keydown',interact));
function fail(){if(!active)return;active=false;paused=true;input.enable(false);hud.hit();shell.finish({id:runId,score,earned:Math.max(15,picked*12),xp:20,stars:1,success:false,revived,daily,stats:{distance:Math.floor(distance),jumps,pickups:picked}});}
function fixed(dt){worldTime+=dt;player.speed=0;if(!active||paused)return;runAge+=dt;if(runAge>60){fail();return;}const controls=input.sample(dt);yaw-=controls.lookX*.004;pitch=THREE.MathUtils.clamp(pitch+controls.lookY*.003,.18,.8);input.state.lookX=input.state.lookY=0;player.previous.copy(player.position);dashLeft=Math.max(0,dashLeft-dt);dashCooldown=Math.max(0,dashCooldown-dt);if(controls.dash&&dashCooldown===0){dashLeft=.22;dashCooldown=.85;audio.sound('jump');squash.value=.9;}const x=controls.x,z=controls.z,speed=dashLeft>0?dashSpeed:4.8,dx=(x*Math.cos(yaw)-z*Math.sin(yaw))*speed*dt,dz=(z*Math.cos(yaw)+x*Math.sin(yaw))*speed*dt;player.position.x=THREE.MathUtils.clamp(player.position.x+dx,-36,36);player.position.z=THREE.MathUtils.clamp(player.position.z+dz,-36,36);for(const c of kit.colliders)if(Math.abs(player.position.x-c.x)<c.w+.35&&Math.abs(player.position.z-c.z)<c.d+.35){player.position.x=player.previous.x;player.position.z=player.previous.z;}if(Math.abs(player.position.x)<1.75&&Math.abs(player.position.z-1.5)<.43&&player.position.y<.68){player.position.z=player.previous.z;if(!railHint){hud.feedback('close','JUMP THE RAIL');railHint=true;}}const travelled=Math.hypot(player.position.x-player.previous.x,player.position.z-player.previous.z);player.speed=travelled/dt;distance+=travelled;dustAge+=dt;if(dustAge>.1&&player.onGround&&Math.hypot(dx,dz)>.01&&settings.particles>0){particles.emit(player.position.x,player.position.y,player.position.z);dustAge=0;}if(Math.hypot(dx,dz)>.01)player.yaw=Math.atan2(dx,dz);const ground=heightAt(player.position.x,player.position.z);player.coyote=player.onGround?.1:Math.max(0,player.coyote-dt);if(controls.jumpBuffer>0&&player.coyote>0){player.velocityY=7.7;player.onGround=false;player.coyote=0;player.glide=signature;input.consumeJump();jumps++;squash.value=.83;audio.sound('jump');}const gliding=controls.jump&&!player.onGround&&player.velocityY<0&&player.glide>0;if(gliding){player.velocityY=Math.max(player.velocityY,-1.4);player.glide=Math.max(0,player.glide-dt);}else player.velocityY-=23*dt;player.position.y+=player.velocityY*dt;if(player.position.y<=ground){if(!player.onGround&&player.velocityY<-5)squash.value=.76;player.position.y=ground;player.velocityY=0;player.onGround=true;player.glide=signature;}else player.onGround=false;
  for(const p of pickups)if(!p.collected&&Math.hypot(player.position.x-p.x,player.position.z-p.z)<magnet&&player.position.y<2.6){p.collected=true;p.group.visible=false;picked++;score+=100;audio.sound('pickup');hud.feedback(picked>=3?'streak':'score',picked>=3?'STREAK ×'+picked:'+100');}if(player.position.z<-13&&picked>=3&&jumps>=1&&Math.hypot(player.position.x,player.position.z+15)<1.25)finish();
}
const hudInfo={};
function menuCamera(){if(camera.aspect<.8){camera.position.set(actor.root.position.x+8,actor.root.position.y+5.2,actor.root.position.z+16);cameraTarget.set(actor.root.position.x,-1,actor.root.position.z);}else{camera.position.set(14,8.5,21);cameraTarget.set(-5,2,-4);}camera.lookAt(cameraTarget);}
function interpolate(alpha,dt){const locomoting=active&&!paused&&player.onGround&&player.speed>.08;const t=shot?3:worldTime;toon.time.value=settings.reduceMotion?0:t;toon.resolution.value.set(renderer.domElement.width,renderer.domElement.height);if(active&&!paused){drawPosition.lerpVectors(player.previous,player.position,alpha);actor.root.position.copy(drawPosition);actor.root.rotation.y=player.yaw;}else{if(!active&&!shot&&!settings.reduceMotion){actor.root.position.y=heightAt(actor.root.position.x,actor.root.position.z)+Math.sin(t*1.8)*.035;if(turning){actor.root.rotation.y+=dt*.45+input.state.lookX*.008;input.state.lookX=input.state.lookY=0;}}}
  if(locomoting){if(actor.walk&&!actor.walk.isRunning())actor.walk.reset().play();actor.walk?.setEffectiveWeight(1);}else if(actor.walk?.isRunning())actor.walk.stop();actor.mixer?.update(dt);if(!locomoting)for(const p of actor.rest||[])p.arm.quaternion.copy(p.pose);const sy=settings.reduceMotion?1:spring(squash,1,dt,15);actor.root.scale.set(1/Math.sqrt(sy),sy,1/Math.sqrt(sy));blob.position.set(actor.root.position.x,heightAt(actor.root.position.x,actor.root.position.z)+.035,actor.root.position.z);blob.visible=settings.shadows!=='off';for(let i=0;i<pickups.length;i++){const p=pickups[i];p.group.rotation.y=t*.8+i;p.group.position.y=1.25+(settings.reduceMotion?0:Math.sin(t*2+i)*.15);}beacon.rotation.z=Math.sin(t*.8)*.05;
  if(shot){if(shot==='menu'){menuCamera();}else if(shot==='vista'){camera.position.set(29,18,35);cameraTarget.set(0,2,-8);}else if(shot==='props'){camera.position.set(-9,6,8);cameraTarget.set(0,2.5,-6);}else{camera.position.set(14,9,23);cameraTarget.set(0,2,-5);}camera.lookAt(cameraTarget);}else if(active&&!paused){cameraTarget.copy(actor.root.position);cameraTarget.y+=1.1;const range=16;cameraGoal.set(cameraTarget.x+Math.sin(yaw)*range*Math.cos(pitch),cameraTarget.y+Math.sin(pitch)*range,cameraTarget.z+Math.cos(yaw)*range*Math.cos(pitch));for(let i=0;i<3;i++)camera.position.setComponent(i,spring(cameraSprings[i],cameraGoal.getComponent(i),dt,7));if(settings.cameraShake&&!settings.reduceMotion)camera.position.y+=hud.cameraKick;camera.lookAt(cameraTarget);}else{menuCamera();}sky.sun.lookAt(camera.position);activeChunks=terrain.update(camera,Math.min(settings.viewDistance,profiles[runtime.preset].distance));
  if(active&&!paused){hudInfo.x=player.position.x;hudInfo.z=player.position.z;hudInfo.yaw=yaw;hudInfo.pickups=picked;hudInfo.remaining=5-picked;hudInfo.glideFraction=player.glide/signature;hudInfo.dashCooldown=1-dashCooldown/.85;hudInfo.tutorial=jumps<1?'Jump the low rail; hold Jump to glide.':picked<3?'Collect at least three signal feathers.':'Visit the finish beacon. E / tap completes.';bubblePoint.copy(beacon.position);bubblePoint.y+=1.4;bubblePoint.project(camera);renderer.getSize(size);hud.setBubble((bubblePoint.x*.5+.5)*size.x-70,(-bubblePoint.y*.5+.5)*size.y,Math.hypot(player.position.x,player.position.z+15)<3.4&&picked>=3&&jumps>=1&&bubblePoint.z<1);}else hud.setBubble(0,0,false);particles.update(dt);hud.update(dt,hudInfo);shell.update(dt);debug.update(dt);
}
function report(){const m=runtime.metrics,story=save.state.profile.story;return {build:'PCOCK-S1-FOUNDATION-20260930-r1',fps:m.fps,frameMs:m.frameMs,cpuMs:m.cpuMs,drawCalls:m.drawCalls,triangles:m.triangles,textureMB:Math.round((assets.textureMB+.36)*100)/100,assets:{...assets.states},env:{...assets.envStates},activeChunks,pools:{scorePops:{active:hud.pops.active,capacity:hud.pops.capacity},dust:{active:particles.pool.active,capacity:particles.pool.capacity}},heapMB:performance.memory?Math.round(performance.memory.usedJSHeapSize/1048576):null,preset:runtime.preset,requestedPreset:settings.preset,renderScale:m.renderScale,dpr:m.dpr,memory:{...renderer.info.memory},stress:params.has('stress'),contextLost:m.contextLost,audioUnlocked:audio.unlocked,screen:shell.screen,character:{animation:actor.walk?.isRunning()?'locomotion':'idle',clip:actor.walk?.isRunning()?actor.walk.getClip().name:null,speed:Math.round(player.speed*100)/100},saveVersion:save.state.saveVersion,profile:{feathers:save.state.profile.feathers,xp:save.state.profile.xp},currency:{game:config.id,name:config.currency,value:save.state.games[config.id].currency},quest:{completed:story.completed||[],feathers:story.feathers||[],featherCount:story.feathers?.length||0},course:{age:runAge,daily,seed:courseSeed,score,picked,jumps,distance,glideSeconds:signature,magnetRadius:magnet,player:{x:player.position.x,y:player.position.y,z:player.position.z}},errors:(window.__PCOCK_ERRORS||[]).slice(-5),saveError:save.error};}
const debug=createDebug(root,report,params.has('debug'));resources.onDispose(()=>debug.dispose());
window.PCOCK={ready:false,report,get settings(){return save.state.settings;},get save(){return structuredClone(save.state);},setPreset(value){if(['Auto','Low','Medium','High','Ultra'].includes(value)){save.update(s=>s.settings.preset=value);settingsChanged();}}};
await assets.loadPeacock(actor);refreshUpgrades();settingsChanged();hud.show(false);if(shot==='results')shell.showPreviewResults();else if(shot==='shop')shell.open('shop');else if(['spawn','props','vista'].includes(shot)){shell.open('title');root.querySelector('.pc-menu-layer').hidden=true;actor.root.position.set(0,heightAt(0,7),7);actor.root.rotation.y=Math.PI;hud.show(params.get('hud')!=='0');}else shell.open('title');if(params.get('hud')==='0'){brandbar.hidden=true;hud.show(false);}
await renderer.compileAsync(scene,camera);runtime.start(fixed,interpolate);window.PCOCK.ready=true;
const visibility=()=>{if(document.hidden&&active&&!paused)shell.open('pause');};addEventListener('visibilitychange',visibility);resources.onDispose(()=>removeEventListener('visibilitychange',visibility));addEventListener('pagehide',()=>resources.dispose(),{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
