import * as THREE from 'three';
import {brand} from './brand.js';
import {worldPalette as W} from './world-palette.js';
import {createSceneKit,mergeParts} from './scene-kit.js';
import {ghostZones} from './ghost-data.js';
export function createGhostWorld(scene,toon,resources,assets,{stress=false}={}){
 const B=brand.colors,kit=createSceneKit(scene,toon,resources,assets),box=resources.own(new THREE.BoxGeometry(1,1,1)),sphere=resources.own(new THREE.IcosahedronGeometry(.5,0)),dummy=new THREE.Object3D(),parts=[],colliders=[],roofs=[],ramps=[],shadows=[],pads=[];
 function part(geometry,color,x,y,z,sx,sy,sz,ry=0){dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,ry,0);dummy.updateMatrix();parts.push({geometry,matrix:dummy.matrix.clone(),color});}
 part(box,W.nightGround,0,-.3,-15,166,.6,70);part(box,W.nightGround,0,-.3,40,166,.6,24);part(box,W.nightShadow,0,-3.3,24,166,.6,8);
 for(const z of [20,28])part(box,W.nightGlass,0,-1.7,z,166,3,.35);
 for(let x=-80;x<=80;x+=8)part(box,W.nightRoof,x,.008,-15,.035,.015,70);for(let z=-48;z<20;z+=8)part(box,W.nightRoof,0,.008,z,166,.015,.035);
 for(const zone of ghostZones){
  for(const dx of [-10,10])for(const z of [-28,-2]){const x=zone.x+dx,height=6;part(box,W.nightGlass,x,2.8,z,9,5.6,9);part(box,W.nightRoof,x,5.75,z,9.7,.3,9.7);colliders.push({x,z,w:4.5,d:4.5,top:height,bottom:0});roofs.push({x,z,w:4.85,d:4.85,top:6});
   for(const side of [-1,1])for(let k=0;k<3;k++){part(box,k%2?B.pulseBlue:B.pulseCyan,x+side*4.54,1.4+k*1.5,z,.1,.5,7);part(box,k%2?B.glow:B.primary,x,1.4+k*1.5,z+side*4.54,7,.35,.1);}part(box,B.primary,x,6.1,z+4.8,9.7,.12,.12);for(const side of [-1,1]){part(box,W.nightRoof,x+side*4.7,6.6,z,.12,1.2,9.4);for(let k=-1;k<=1;k++)part(box,W.nightRoof,x+k*3,2.8,z+side*4.6,.16,5.5,.16);}part(sphere,W.nightShadow,x-2,6.4,z,1.3,.8,1.3);
   const rx=x+6;ramps.push({x:rx,z,w:1.1,from:z+7,to:z-5,top:6});for(let k=0;k<9;k++)part(box,W.nightRoof,rx,(k+.5)*6/9,z+7-(k+.5)*12/9,2.2,6/9,12/9);
  }
  for(const z of [-28,-2]){part(box,W.nightRoof,zone.x,5.8,z,12,.4,2);roofs.push({x:zone.x,z,w:6,d:1,top:6});for(const side of [-1,1])part(box,B.primary,zone.x,6.8,z+side*.95,12,.12,.12);}
  for(const dx of [-12,12]){shadows.push({x:zone.x+dx,z:-13,w:4,d:6});part(box,W.nightShadow,zone.x+dx,.012,-13,8,.025,12);}
  for(const [dx,z]of [[-13,12],[13,-14]]){pads.push({x:zone.x+dx,z});part(kit.templates['feather-shrine'],B.text,zone.x+dx+2,0,z,.45,.45,.45);part(box,B.pulseCyan,zone.x+dx,.035,z,3,.07,3);}
  for(const [dx,z]of [[0,7],[-2,-15],[3,-38]]){part(kit.templates.crate,B.text,zone.x+dx,0,z,2,2,2);colliders.push({x:zone.x+dx,z,w:1,d:1,bottom:0,top:2});roofs.push({x:zone.x+dx,z,w:1,d:1,top:2});}
  part(kit.templates['liberty-arch'],B.text,zone.x,0,17,.65,.65,.65);for(const side of [-1,1]){part(box,W.nightRoof,zone.x+side*2.35,-.15,24,.3,.3,8);part(box,W.nightRoof,zone.x,-.15,24+side*3.85,5,.3,.3);}roofs.push({x:zone.x,z:24,w:2.5,d:4,top:0});part(box,B.accent,zone.x,.03,24,.14,.06,8);
 }
 for(const zone of ghostZones)for(const z of [-40,-14,10,34])for(const side of [-1,1]){part(kit.templates['signal-lamp'],B.text,zone.x+side*20,0,z,1,1.4,1);part(kit.templates.planter,B.text,zone.x+side*17,0,z,.8,.8,.8);part(box,B.pulseCyan,zone.x+side*19,.035,z+5,.1,.07,7);}
 // Sewer slopes at both ends lead from streets to the safe lower route.
 for(const side of [-1,1])for(let i=0;i<10;i++)part(box,W.nightRoof,side*(65+i),-3+(i+.5)*.3,24,1,.3,7.5);
 const pipe=resources.own(new THREE.CylinderGeometry(.18,.18,1,6));pipe.rotateZ(Math.PI/2);for(const z of [20.7,27.3])part(pipe,W.nightRoof,0,.2,z,160,1,1);for(let x=-75;x<=75;x+=10){for(const z of [20.5,27.5])part(box,W.nightRoof,x,-.8,z,.28,4.2,.28);part(box,W.nightRoof,x,1.3,24,.3,.28,7.2);part(sphere,B.pulseCyan,x,.8,24,.35,.35,.35);part(box,W.nightGlass,x,-2.99,24,.06,.02,7.2);}part(box,B.pulseCyan,0,-2.98,24,160,.025,.08);
 // Far skyline and original Liberty/PulseChain landmarks make four depth layers.
 for(let i=0;i<23;i++){const x=(i-11)*8,z=-58-(i%3)*7,height=10+(i*7%19);part(box,i%2?W.nightFog:W.nightShadow,x,height/2,z,6,height,6);for(let j=0;j<4;j++)part(box,B.pulseBlue,x,2+j*height/5,z+3.1,3,.4,.1);}
 part(kit.templates['signal-spire'],B.text,0,0,-53,2.5,2.5,2.5);const geometry=resources.own(mergeParts(parts)),mesh=new THREE.Mesh(geometry,kit.material),hull=new THREE.Mesh(geometry,kit.outline);scene.add(hull,mesh);
 scene.fog.color.set(W.nightFog);scene.background=new THREE.Color(W.nightSky);scene.traverse(o=>{if(o.isHemisphereLight){o.color.set(W.moon);o.groundColor.set(W.nightShadow);o.intensity=.8;}});
 const glassGeo=resources.own(new THREE.PlaneGeometry(4.3,7.5));glassGeo.rotateX(-Math.PI/2);const glass=new THREE.InstancedMesh(glassGeo,resources.own(new THREE.MeshBasicMaterial({color:W.nightGlass,transparent:true,opacity:.4,side:THREE.DoubleSide})),3);resources.own(glass);for(let i=0;i<3;i++){dummy.position.set(ghostZones[i].x,.02,24);dummy.scale.setScalar(1);dummy.rotation.set(0,0,0);dummy.updateMatrix();glass.setMatrixAt(i,dummy.matrix);}scene.add(glass);const moon=new THREE.Mesh(resources.own(new THREE.IcosahedronGeometry(4,1)),resources.own(new THREE.MeshBasicMaterial({color:W.moon})));moon.position.set(-50,37,-73);scene.add(moon);toon.hull(moon);
 const stars=new THREE.InstancedMesh(sphere,resources.own(new THREE.MeshBasicMaterial({color:W.moon})),70);resources.own(stars);for(let i=0;i<70;i++){dummy.position.set(Math.sin(i*4.1)*135,30+i%40,Math.cos(i*4.1)*135);dummy.scale.setScalar(.12);dummy.updateMatrix();stars.setMatrixAt(i,dummy.matrix);}scene.add(stars);
 const coneGeometry=resources.own(new THREE.CircleGeometry(1,20,Math.PI/2-.57,1.14));coneGeometry.rotateX(-Math.PI/2);const coneMat=resources.own(new THREE.MeshBasicMaterial({color:B.text,transparent:true,opacity:.15,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending})),cones=new THREE.InstancedMesh(coneGeometry,coneMat,13);resources.own(cones);cones.frustumCulled=false;scene.add(cones);
 const watcherParts=[];parts.length=0;part(sphere,W.nightRoof,0,0,0,1.3,.6,1.3);part(box,B.accent,0,0,.55,.75,.15,.15);part(box,W.nightShadow,0,.1,0,2,.12,.2);watcherParts.push(...parts);parts.length=0;const watcherGeo=resources.own(mergeParts(watcherParts)),watchers=new THREE.InstancedMesh(watcherGeo,kit.material,13),watcherHulls=new THREE.InstancedMesh(watcherGeo,kit.outline,13);resources.own(watchers);resources.own(watcherHulls);watchers.frustumCulled=watcherHulls.frustumCulled=false;scene.add(watcherHulls,watchers);
 parts.length=0;part(box,W.nightShadow,0,3,0,2.3,3,1.4);part(sphere,W.nightRoof,0,5,0,2.3,1.8,2);for(const side of [-1,1]){part(box,W.nightGlass,side*.65,1,0,.6,2.6,.75);part(box,W.nightRoof,side*1.5,3.4,0,.7,2.8,.8);part(box,B.danger,side*.45,5.2,1,.5,.25,.1);}part(kit.templates['signal-spire'],B.text,0,5.6,-.5,.2,.2,.2);const warden=new THREE.Mesh(resources.own(mergeParts(parts)),kit.material);scene.add(warden);const wardenHull=toon.hull(warden),bossConeGeo=resources.own(new THREE.CircleGeometry(1,30,Math.PI/2-.8,1.6));bossConeGeo.rotateX(-Math.PI/2);const bossCone=new THREE.Mesh(bossConeGeo,coneMat);scene.add(bossCone);
 const targetGeo=resources.own(new THREE.TorusGeometry(1.5,.12,6,24)),targets=Array.from({length:3},()=>{const mesh=new THREE.Mesh(targetGeo,toon.material(B.gold));scene.add(mesh);return {mesh,hull:toon.hull(mesh)};});const decoy=new THREE.Mesh(sphere,toon.material(B.gold));scene.add(decoy);const decoyHull=toon.hull(decoy),color=new THREE.Color();
 const particles=new THREE.InstancedMesh(sphere,toon.material(B.pulseCyan),stress?600:36);resources.own(particles);scene.add(particles);
 function heightAt(x,z){if(z>20&&z<28){const edge=Math.abs(x);return edge<65?-3:Math.min(0,-3+(edge-65)*.3);}return 0;}
 function groundAt(x,z,y){let h=heightAt(x,z);for(const r of roofs)if(y>=r.top-.5&&Math.abs(x-r.x)<r.w&&Math.abs(z-r.z)<r.d)h=Math.max(h,r.top);for(const r of ramps)if(Math.abs(x-r.x)<r.w&&z<r.from&&z>r.to)h=Math.max(h,(r.from-z)/(r.from-r.to)*r.top);return h;}
 function blocked(x,z,y){if(Math.abs(x)>80||z<-48||z>48)return true;for(const c of colliders)if(y<c.top-.22&&y+1.8>c.bottom&&Math.abs(x-c.x)<c.w+.3&&Math.abs(z-c.z)<c.d+.3)return true;return false;}
 function lineOfSight(ax,ay,az,bx,by,bz){const steps=Math.ceil(Math.hypot(bx-ax,bz-az)/.6);for(let i=1;i<steps;i++){const t=i/steps,x=ax+(bx-ax)*t,z=az+(bz-az)*t,y=ay+(by-ay)*t;for(const c of colliders)if(y<c.top&&y>c.bottom&&Math.abs(x-c.x)<c.w&&Math.abs(z-c.z)<c.d)return false;if(y<-.1&&by>-.1&&z>20&&z<28)return false;}return true;}
 function update(loop,player,time){const s=loop.state;for(let i=0;i<13;i++){const w=loop.watchers[i];dummy.position.set(w?.x||0,w?.y||0,w?.z||0);dummy.rotation.set(0,w?.yaw||0,0);dummy.scale.setScalar(w&&!w.boss?1:0);dummy.updateMatrix();watchers.setMatrixAt(i,dummy.matrix);watcherHulls.setMatrixAt(i,dummy.matrix);const near=w&&Math.hypot(w.x-player.position.x,w.z-player.position.z)<(s.ping>0?loop.pingRange:23);dummy.position.set(w?.x||0,heightAt(w?.x||0,w?.z||0)+.055,w?.z||0);dummy.rotation.set(0,(w?.yaw||0)+Math.PI,0);dummy.scale.setScalar(near&&!w.boss?w.range:0);dummy.updateMatrix();cones.setMatrixAt(i,dummy.matrix);cones.setColorAt(i,color.set(w?.alerted?B.danger:w?.awareness>.2?B.gold:B.pulseCyan));}watchers.instanceMatrix.needsUpdate=watcherHulls.instanceMatrix.needsUpdate=cones.instanceMatrix.needsUpdate=true;cones.instanceColor.needsUpdate=true;coneMat.opacity=s.ping>0?.35:.15;const boss=loop.watchers.find(w=>w.boss);warden.visible=wardenHull.visible=bossCone.visible=!!boss;if(boss){warden.position.set(boss.x,0,boss.z);warden.rotation.y=boss.yaw;wardenHull.position.copy(warden.position);wardenHull.rotation.copy(warden.rotation);bossCone.position.set(boss.x,.07,boss.z);bossCone.rotation.y=boss.yaw+Math.PI;bossCone.scale.setScalar(boss.range);}
  for(let i=0;i<targets.length;i++){const t=loop.contract.targets[i],v=!!t&&!s.delivered.includes(i)&&(loop.contract.type!=='heist'||i===s.delivered.length),item=targets[i];item.mesh.visible=item.hull.visible=v;if(t){item.mesh.position.set(t.x,1.8+Math.sin(time*2)*.1,t.z);item.mesh.rotation.y=time*.3;item.hull.position.copy(item.mesh.position);item.hull.rotation.copy(item.mesh.rotation);}}
  decoy.visible=decoyHull.visible=!!s.decoy;if(s.decoy){decoy.position.set(s.decoy.x,1.3,s.decoy.z);decoy.scale.set(.25,1.2,.18);decoy.rotation.y=time*2;decoyHull.position.copy(decoy.position);decoyHull.scale.copy(decoy.scale);decoyHull.rotation.copy(decoy.rotation);}
  for(let i=0;i<particles.count;i++){dummy.position.set(Math.sin(time*.15+i*3)*76,1+i%7,Math.cos(time*.1+i*7)*45);dummy.scale.set(.025,.08,.025);dummy.rotation.set(0,0,0);dummy.updateMatrix();particles.setMatrixAt(i,dummy.matrix);}particles.instanceMatrix.needsUpdate=true;
 }
 return {heightAt,groundAt,blocked,cameraBlocked(x,z,y){return y<heightAt(x,z)+.2||blocked(x,z,y);},lineOfSight,update,roofs,ramps,pads,shadows,colliders,respawn:{x:-61,z:12},inShadow(x,z){return z>20&&z<28||shadows.some(s=>Math.abs(x-s.x)<s.w&&Math.abs(z-s.z)<s.d);},onPad(x,z){return pads.some(p=>Math.hypot(x-p.x,z-p.z)<2.2);},unsafe(x,z,y){return y<-5;},activeChunks:3};
}
