import {rng} from './rng.js';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function createGhostLoop(contract,seed,upgrades,world,emit=()=>{}){
 const random=rng(seed),capacity=100+(upgrades.charge||0)*20,s={contract:contract.id,age:0,charge:capacity,capacity,cloaked:false,exhausted:false,ping:0,decoys:2+(upgrades.decoys||0),decoy:null,value:contract.value,privacy:100,exposed:0,alerts:0,style:0,distance:0,jumps:0,dashes:0,glideTime:0,delivered:[],ended:false,success:false,grade:null,score:0,revived:false,hunt:false},watchers=Array.from({length:contract.type==='boss'?13:5},(_,i)=>{const homeX=contract.type==='boss'?-48+(i%3)*48:contract.zone*48-48;return {id:i,homeX:homeX+((i%2)*2-1)*7,homeZ:-6-Math.floor(i/2)*7,x:0,z:0,y:i===4?7:2.6,yaw:0,phase:random()*6.28,awareness:0,alerted:false,lastSeen:0,theft:0,range:contract.type==='boss'&&i===12?24:16,boss:contract.type==='boss'&&i===12,decoyed:false};});let lastX=contract.start.x,lastZ=contract.start.z;for(const w of watchers){if(w.boss){w.homeX=0;w.homeZ=-19;w.y=5;}w.x=w.homeX+Math.sin(w.phase)*4;w.z=w.homeZ+Math.cos(w.phase)*3;if(contract.type==='chase'&&w.id<2){w.x=contract.start.x+(w.id?3:-3);w.z=contract.start.z+5;w.alerted=true;w.awareness=1;w.theft=3;}}
 function action(type,player){if(s.ended)return;if(type==='ping'&&s.ping<=0){s.ping=3;emit('ping','PULSE PING · Vision revealed');}if(type==='decoy'&&s.decoys>0){s.decoys--;s.decoy={x:player.position.x,z:player.position.z,age:7};s.style+=5;emit('decoy','DECOY FEATHER');}if(type==='dash'){s.dashes++;s.style+=1;}if(type==='jump')s.jumps++;}
 function sees(w,p){const dx=p.x-w.x,dz=p.z-w.z,d=Math.hypot(dx,dz);if(d>w.range||Math.abs(p.y+1.2-w.y)>4)return false;const facing=Math.atan2(dx,dz),angle=Math.atan2(Math.sin(facing-w.yaw),Math.cos(facing-w.yaw));return Math.abs(angle)<(w.boss?.8:.57)&&world.lineOfSight(w.x,w.y,w.z,p.x,p.y+1,p.z);}
 function deliver(player){if(s.ended)return false;let index=-1;const pending=contract.type==='heist'?[s.delivered.length]:contract.targets.map((_,i)=>i).filter(i=>!s.delivered.includes(i));for(const i of pending){const t=contract.targets[i];if(t&&Math.hypot(t.x-player.position.x,t.z-player.position.z)<3&&Math.abs(player.position.y)<2){index=i;break;}}if(index<0){emit('hint','Reach a gold ring at street level.');return false;}s.delivered.push(index);emit('delivery',contract.type==='heist'&&s.delivered.length===1?'PACKAGE RECOVERED · Return to sender':'SAFE ARRIVAL '+s.delivered.length+' / '+contract.targets.length);if(s.delivered.length===contract.targets.length)finish(true);return true;}
 function finish(success){s.ended=true;s.success=success;const time=clamp(contract.par/Math.max(1,s.age),0,1.2),value=s.value/contract.value;s.score=Math.round(1000*(time*.3+s.privacy/100*.35+value*.3+Math.min(1,s.style/30)*.05));s.grade=!success?'D':s.score>=980?'S':s.score>=860?'A':s.score>=720?'B':s.score>=580?'C':'D';emit('finish',s.grade);}
 function step(dt,player,cloakHeld){if(s.ended)return;s.age+=dt;s.ping=Math.max(0,s.ping-dt);if(s.decoy){s.decoy.age-=dt;if(s.decoy.age<=0)s.decoy=null;}if(!cloakHeld)s.exhausted=false;if(s.charge<=.01&&cloakHeld)s.exhausted=true;s.cloaked=cloakHeld&&!s.exhausted&&s.charge>0;if(s.cloaked)s.charge=Math.max(0,s.charge-(10-(upgrades.efficiency||0)*1.1)*dt);else if(world.inShadow(player.position.x,player.position.z)||world.onPad(player.position.x,player.position.z))s.charge=Math.min(capacity,s.charge+24*dt);else s.charge=Math.min(capacity,s.charge+2*dt);s.distance+=Math.hypot(player.position.x-lastX,player.position.z-lastZ);lastX=player.position.x;lastZ=player.position.z;if(player.gliding){s.glideTime+=dt;s.style+=dt*.5;}
  let seen=false;s.hunt=false;for(const w of watchers){w.theft=Math.max(0,w.theft-dt);w.decoyed=!!s.decoy&&Math.hypot(w.x-s.decoy.x,w.z-s.decoy.z)<18;if(w.alerted){const dx=player.position.x-w.x,dz=player.position.z-w.z,len=Math.max(1,Math.hypot(dx,dz));if(!s.cloaked&&world.lineOfSight(w.x,w.y,w.z,player.position.x,player.position.y+1,player.position.z)){w.x+=dx/len*2.3*dt;w.z+=dz/len*2.3*dt;w.yaw=Math.atan2(dx,dz);}}else{const t=s.age*.2+w.phase;w.x=w.homeX+Math.sin(t)*4;w.z=w.homeZ+Math.cos(t)*3;w.yaw=t+Math.PI/2;}
   if(w.decoyed){w.yaw=Math.atan2(s.decoy.x-w.x,s.decoy.z-w.z);w.awareness=Math.max(0,w.awareness-dt*.7);}const visible=!s.cloaked&&!w.decoyed&&sees(w,player.position);if(visible){seen=true;w.lastSeen=0;w.awareness=Math.min(1,w.awareness+dt*(contract.number===1?.42:.7));if(w.awareness>=1&&!w.alerted){w.alerted=true;s.alerts++;s.value=Math.max(0,s.value-contract.value*.12);w.theft=6;emit('alert','FRONT-RUN · Value lost. Break sight!');}else if(w.alerted&&w.theft===0){s.value=Math.max(0,s.value-contract.value*.08);w.theft=6;emit('alert','HUNT CONTINUES · Find cover or cloak');}}
   else{w.lastSeen+=dt;w.awareness=Math.max(0,w.awareness-dt*.5);if(w.lastSeen>=2&&w.alerted){w.alerted=false;w.awareness=0;s.style+=4;emit('escape','SIGHT BROKEN · Safe for now');}}s.hunt||=w.alerted;}
  if(seen)s.exposed+=dt;s.privacy=100*(1-s.exposed/Math.max(.01,s.age));if(s.age>=contract.limit||s.value<=0)finish(false);
 }
 return {state:s,watchers,contract,step,action,deliver,sees,finish,revive(){s.ended=false;s.success=false;s.revived=true;s.age=Math.min(s.age,contract.limit-45);s.value=Math.max(s.value,contract.value*.5);s.charge=capacity;for(const w of watchers){w.alerted=false;w.awareness=0;}},get pingRange(){return 25+(upgrades.ping||0)*7;}};
}
