import * as THREE from 'three';
import {brand,applyBrandCss} from './brand.js';
import {worldPalette as W} from './world-palette.js';
import {Resources} from './disposal.js';
import {createSave} from './save.js';
import {createEconomy} from './economy.js';
import {createRenderer} from './renderer.js';
import {createToon} from './toon.js';
import {createAssets} from './assets.js';
import {createHud,element,button} from './hud-kit.js';
import {createInput} from './input.js';
import {createMovement} from './movement.js';
import {createAudio} from './audio.js';
import {createParticles} from './particles.js';
import {createGameShell} from './game-shell.js';
import {createDebug} from './debug.js';
import {ensureStyles} from './styles.js';
import {createMiniHudEditor} from './mini-hud-editor.js';
import {hashSeed,utcDay} from './rng.js';
import {ghostConfig,ghostContracts,ghostZones} from './ghost-data.js';
import {createGhostLoop} from './ghost-loop.js';
import {createGhostWorld} from './ghost-world.js';
await ensureStyles(['./fonts.css','./foundation.css','./arcade.css']);applyBrandCss();document.body.classList.add('foundation','arcade','ghost');await document.fonts.ready;
const query=new URLSearchParams(location.search),funOnly=query.get('fun')==='1',shot=query.get('shot'),resources=new Resources(),save=createSave(),settings=new Proxy({},{get:(_,k)=>save.state.settings[k],set:(_,k,v)=>{save.state.settings[k]=v;return true;}}),economy=createEconomy(save),config=ghostConfig(save);if(query.has('preset'))settings.preset=query.get('preset');
const root=document.getElementById('foundation-root');root.replaceChildren();root.className='pc-root';const host=element('div','pc-world'),grade=element('div','pc-grade'),bar=element('header','pc-brandbar');bar.innerHTML='<a class="pc-mark" href="../index.html">PCOCK<small>FEATHERS OF LIBERTY</small></a><span class="pc-stage-tag">GHOST ROUTE</span>';root.append(host,grade,bar);
const runtime=createRenderer(host,settings,resources),{scene,camera,renderer}=runtime,toon=createToon(resources),assets=createAssets(toon,resources,{originalCharacters:true,peacockFan:true});await assets.loadEnvironment();const world=createGhostWorld(scene,toon,resources,assets,{stress:query.has('stress')}),actor=assets.standIn();scene.add(actor.root);await assets.loadPeacock(actor);runtime.sun.color.set(W.moon);runtime.sun.intensity=.85;
const hud=createHud(root,save,config),input=createInput(renderer.domElement,hud.hud,settings),audio=createAudio(settings),particles=createParticles(scene,resources),banner=element('div','a-banner'),stats=element('div','a-stats'),actions=element('div','g-actions'),board=element('div','pc-menu-layer'),meters=element('div','g-meters');root.append(banner,stats,actions,board,meters);board.hidden=true;hud.hud.querySelector('.pc-mission small').textContent='GHOST ROUTE';hud.hud.querySelector('.pc-desktop-help').textContent=config.controls;hud.hud.querySelector('.pc-hit-pips').hidden=true;
let loop,active=false,paused=true,choosing=false,daily=false,runId='',sequence=0,time=0,selected=1,cloakKey=false,lastCloaked=false,preview=false,turntable=false,readyToFinish=false;const cloakPointers=new Set();
const mover=createMovement(actor,input,camera,settings,world,type=>{loop?.action(type,mover.player);if(type==='jump'||type==='dash')audio.sound('jump');});
let ghostHudMenus=[];
const ghostHudEditor=createMiniHudEditor(root,{
 storageKey:'pcock.ghost.hud.layouts.v1',layoutType:'PCOCK_GHOST_ROUTE_HUD_LAYOUT_V1',
 targets:[
  ['brand','BRAND / GAME NAME','.pc-brandbar'],['status','STATUS / SCORE','.pc-hud-top'],
  ['mission','MISSION / OBJECTIVE','.pc-mission'],['compass','MINIMAP / COMPASS','.pc-compass'],
  ['stick','MOVE STICK','.pc-stick'],['actions','JUMP / DASH / INTERACT','.pc-abilities'],
  ['prompt','INTERACT PROMPT','.pc-world-bubble'],['banner','CONTRACT BANNER','.a-banner'],
  ['stats','CONTRACT STATS','.a-stats'],['ghostActions','CLOAK / DECOY / PING','.g-actions'],
  ['awareness','WATCHER / AWARENESS HUD','.g-meters']
 ],
 previewSelectors:['.pc-hud','.pc-controls','.a-banner','.a-stats','.g-actions','.g-meters'],
 previewCss:'.pc-root.pcock-mini-hud-editing .pc-hud{display:block!important}.pc-root.pcock-mini-hud-editing .pc-world-bubble,.pc-root.pcock-mini-hud-editing .a-banner,.pc-root.pcock-mini-hud-editing .a-stats,.pc-root.pcock-mini-hud-editing .g-actions,.pc-root.pcock-mini-hud-editing .g-meters{display:block!important;visibility:visible!important;opacity:.94!important}.pc-root.pcock-mini-hud-mobile .pc-controls{display:flex!important}.pc-root.pcock-mini-hud-pc .pc-controls{display:none!important}',
 onEnter(){ghostHudMenus=[...root.querySelectorAll('.pc-menu-layer')].map(el=>({el,hidden:el.hidden}));for(const x of ghostHudMenus)x.el.hidden=true;hud.show(true);banner.hidden=stats.hidden=actions.hidden=meters.hidden=false;input.enable(false);mover.enabled=false;},
 onExit(){for(const x of ghostHudMenus)x.el.hidden=x.hidden;ghostHudMenus=[];hud.show(false);banner.hidden=stats.hidden=actions.hidden=meters.hidden=true;input.enable(false);mover.enabled=false;}
});

function effect(type,text){if(type==='finish'){readyToFinish=true;return;}hud.feedback(type==='alert'?'damage':type==='escape'?'close':'streak',text);audio.sound(type==='alert'?'damage':type==='delivery'?'buy':'pickup');}
function makeLoop(number,seed){selected=number;loop=createGhostLoop(ghostContracts[number-1],seed,save.state.games[config.id].upgrades,world,effect);mover.place(loop.contract.start.x,loop.contract.start.z);mover.yaw=0;world.respawn.x=loop.contract.start.x;world.respawn.z=loop.contract.start.z;readyToFinish=false;const u=save.state.games[config.id].upgrades;mover.configure({glide:2.4+(u.signature||0)*.5,speed:6});}
function unlocked(){const stars=save.state.games[config.id].stars;let n=1;while(n<=15&&stars['contract-'+n])n++;return n;}
function startContract(number,dailyRun=false){choosing=false;board.hidden=true;board.replaceChildren();daily=dailyRun;runId='ghost-'+Date.now()+'-'+(++sequence);makeLoop(number,hashSeed(daily?'ghost-'+utcDay():number+'|'+sequence));hud.reset();particles.reset();active=true;paused=false;preview=false;input.enable(true);mover.enabled=true;hud.show(true);actions.hidden=banner.hidden=stats.hidden=meters.hidden=false;setSkin(save.state.games[config.id].skin);audio.unlock();}
function showBoard(){choosing=true;active=false;input.enable(false);mover.enabled=false;hud.show(false);actions.hidden=banner.hidden=stats.hidden=meters.hidden=true;board.hidden=false;board.replaceChildren();const p=element('section','pc-panel pc-wide'),head=element('div','pc-panel-header');head.append(element('h2','','CONTRACTS'),button('×',()=>{choosing=false;board.hidden=true;shell.open('title');},'pc-button'));p.append(head,element('p','pc-notice','Pick a delivery. Gold rings mark your destination; streets, roofs and sewers all connect.'));const grid=element('div','g-contracts');for(const c of ghostContracts){const count=save.state.games[config.id].stars[c.id]||0,b=button(c.number+'. '+c.title+' · '+(count?'★'.repeat(count):c.number>unlocked()?'Locked':c.type),()=>startContract(c.number),'pc-button');b.disabled=c.number>unlocked();b.dataset.contract=c.number;grid.append(b);}p.append(grid);board.append(p);}
const hat=new THREE.Mesh(resources.own(new THREE.ConeGeometry(.35,.45,6)),toon.material(brand.colors.glow));hat.position.y=2.4;actor.root.add(hat);const hatHull=toon.hull(hat);hat.visible=hatHull.visible=false;const actorMaterials=new Set();actor.root.traverse(o=>{if(o.material){o.material.transparent=true;actorMaterials.add(o.material);}});
function setSkin(id){const colors=id==='signal-tail'?[brand.colors.pulseCyan,brand.colors.pulseBlue,brand.colors.pulsePurple,brand.colors.pulseMagenta,brand.colors.pulseRed]:[brand.colors.glow,brand.colors.accent,brand.colors.logoCoral,brand.colors.gold,brand.colors.logoOrange,brand.colors.pulseCyan,brand.colors.pulsePurple];let i=0;for(const mesh of actor.tail.children)if(mesh.isMesh&&!mesh.userData.hull&&!actor.tail.animate)mesh.material.color.set(colors[i++%colors.length]);particles.setEmber(id==='ember-trail');hat.visible=hatHull.visible=id==='wayfarer-hat';}
function settingsChanged(){runtime.applySettings();root.classList.toggle('pc-reduce-motion',settings.reduceMotion);root.classList.toggle('pc-color-safe',settings.colorSafe);grade.hidden=settings.postFX==='off';audio.apply();}
const adapter={openHudEditor(){ghostHudEditor.choose(()=>shell.open('settings'));},begin({daily:dailyRun,retry}){if(retry)startContract(selected,dailyRun);else if(dailyRun)startContract(1+hashSeed(utcDay())%15,true);else showBoard();},pause(v){paused=v;cloakKey=false;cloakPointers.clear();mover.enabled=!v&&active&&!choosing;hud.show(!v&&active&&!choosing);actions.hidden=banner.hidden=stats.hidden=meters.hidden=v||!active||choosing;},exit(){active=false;choosing=false;board.hidden=true;input.enable(false);},revive(){loop.revive();readyToFinish=false;active=true;paused=false;runId+='-revive';mover.enabled=true;hud.show(true);actions.hidden=banner.hidden=stats.hidden=meters.hidden=false;},settingsChanged,refreshUpgrades(){},setSkin,turntable(v){turntable=v;}};
makeLoop(1,hashSeed('ghost-menu'));if(funOnly)config.returnUrl=new URL('../index.html?return=runner',import.meta.url).href;const shell=createGameShell(root,{save,economy,config,audio,adapter,shot,funOnly});hud.onPause(()=>shell.open('pause'));hud.onFinish(()=>{if(active&&!paused)loop.deliver(mover.player);});
const cloak=button('HOLD CLOAK',()=>{},'pc-button');cloak.setAttribute('aria-label','Hold Private cloak');cloak.addEventListener('pointerdown',e=>{e.preventDefault();cloakPointers.add(e.pointerId);cloak.setPointerCapture(e.pointerId);});for(const type of ['pointerup','pointercancel','lostpointercapture'])cloak.addEventListener(type,e=>cloakPointers.delete(e.pointerId));actions.append(cloak,button('DECOY · Q',()=>ability('decoy'),'pc-button'),button('PING · F',()=>ability('ping'),'pc-button'));
function ability(type){if(active&&!paused)loop.action(type,mover.player);}
const keyDown=e=>{if(!active||paused||e.target.closest('input,select,textarea'))return;if(e.code==='KeyC'){e.preventDefault();cloakKey=true;}if(!e.repeat){if(e.code==='KeyQ')ability('decoy');if(e.code==='KeyF')ability('ping');if(e.code==='KeyE')loop.deliver(mover.player);}},keyUp=e=>{if(e.code==='KeyC')cloakKey=false;},blur=()=>{cloakKey=false;cloakPointers.clear();};addEventListener('keydown',keyDown);addEventListener('keyup',keyUp);addEventListener('blur',blur);
const meterNodes=Array.from({length:13},()=>{const n=element('div','g-awareness');meters.append(n);return n;});const projected=new THREE.Vector3(),target=new THREE.Vector3(),goal=new THREE.Vector3(),arrow=new THREE.Mesh(resources.own(new THREE.ConeGeometry(.2,.65,5)),toon.material(brand.colors.gold));scene.add(arrow);const arrowHull=toon.hull(arrow);
function finish(){if(!active)return;readyToFinish=false;active=false;paused=true;mover.enabled=false;const s=loop.state,stars=s.grade==='S'||s.grade==='A'?3:s.grade==='B'?2:1;if(s.success&&!funOnly){save.state.profile.story.ghostMilestone=true;if(selected===16)save.state.profile.story.wardenDefeated=true;save.write();}shell.finish({id:runId,score:s.score,earned:s.success?Math.round(45+s.value*.3+s.privacy*.15):Math.max(10,Math.floor(s.age/5)),xp:s.success?60:20,stars,mission:s.success?loop.contract.id:'attempt-'+loop.contract.id,success:s.success,revived:s.revived,daily,detail:'GRADE '+s.grade+' · '+Math.round(s.privacy)+'% PRIVATE · '+Math.round(s.value)+' VALUE · '+Math.round(s.age)+'s / '+loop.contract.par+'s par',stats:{distance:s.distance,jumps:s.jumps,pickups:s.delivered.length}});}
function fixed(dt){if(!active||paused||choosing||preview){mover.step(dt,false);return;}const cloakHeld=cloakKey||cloakPointers.size>0;mover.configure({speed:cloakHeld&&loop.state.charge>0?3.3:6});mover.step(dt,true);loop.step(dt,mover.player,cloakHeld);if(readyToFinish||loop.state.ended)finish();}
function objective(){const pending=loop.contract.targets.map((p,i)=>({...p,i})).filter(p=>!loop.state.delivered.includes(p.i));if(loop.contract.type!=='heist')pending.sort((a,b)=>Math.hypot(a.x-mover.player.position.x,a.z-mover.player.position.z)-Math.hypot(b.x-mover.player.position.x,b.z-mover.player.position.z));return pending[0]||loop.contract.targets[0];}
const info={};let dust=0;
function interpolate(alpha,dt){time+=dt;const t=shot?3:time,s=loop.state,p=mover.player;toon.time.value=settings.reduceMotion?0:t;renderer.getDrawingBufferSize(toon.resolution.value);mover.render(alpha,dt,active&&!paused&&!preview);if(turntable)actor.root.rotation.y+=time*.1;world.update(loop,p,t);if(s.cloaked!==lastCloaked){lastCloaked=s.cloaked;for(const m of actorMaterials)m.opacity=s.cloaked?.32:1;}const o=objective();target.set(o.x,1.8,o.z);arrow.position.copy(actor.root.position);arrow.position.y+=3.5;arrow.rotation.set(Math.PI/2,0,-Math.atan2(o.x-p.position.x,o.z-p.position.z));arrowHull.position.copy(arrow.position);arrowHull.rotation.copy(arrow.rotation);arrow.visible=arrowHull.visible=active&&!paused&&!choosing&&query.get('hud')!=='0';
 if(shot&&!['shop','results','menu'].includes(shot)){const views={ghost:[-61,7,28,-56,1,5],roof:[-34,16,-5,-45,5,-23],sewer:[7,.5,24,19,-1,24],warden:[6,10,-6,0,3,-23]};const v=views[shot]||views.ghost;camera.position.set(...v.slice(0,3));camera.lookAt(...v.slice(3));}
 const near=Math.hypot(p.position.x-o.x,p.position.z-o.z)<3&&Math.abs(p.position.y)<2;projected.copy(target).project(camera);hud.setBubble((projected.x*.5+.5)*innerWidth-60,Math.min(innerHeight-220,(-projected.y*.5+.5)*innerHeight),near&&active&&!paused);hud.hud.querySelector('[data-bubble]').textContent='Deliver · E / tap';info.x=p.position.x;info.z=p.position.z;info.yaw=mover.yaw;info.glideFraction=p.glide/mover.glideMax;info.dashCooldown=1-p.cooldown/.95;info.tutorial=loop.contract.lesson;hud.update(dt,info);hud.hud.querySelector('[data-mission]').textContent=loop.contract.title+' · '+s.delivered.length+'/'+loop.contract.targets.length;banner.textContent=s.hunt?'HUNTED — BREAK SIGHT':s.cloaked?'PRIVATE · '+Math.ceil(s.charge)+' CHARGE':'PUBLIC · '+Math.ceil(s.charge)+' CHARGE';banner.classList.toggle('danger',s.hunt);stats.textContent=Math.ceil(loop.contract.limit-s.age)+'s · '+Math.round(s.privacy)+'% PRIVATE · '+Math.round(s.value)+' VALUE · '+s.decoys+' DECOYS';cloak.style.setProperty('--charge',s.charge/s.capacity*100+'%');
 const ctx=hud.hud.querySelector('[data-minimap]').getContext('2d');ctx.fillStyle=brand.colors.surface;ctx.fillRect(0,0,96,96);for(const z of ghostZones){ctx.strokeStyle=brand.colors.primary;ctx.strokeRect(45+z.x*.45,35,20,23);}ctx.fillStyle=brand.colors.gold;ctx.fillRect(46+o.x*.45,46+o.z*.6,4,4);ctx.fillStyle=brand.colors.text;ctx.fillRect(47+p.position.x*.45,47+p.position.z*.6,3,3);
 for(let i=0;i<meterNodes.length;i++){const w=loop.watchers[i],node=meterNodes[i];node.hidden=!w||!active||paused||Math.hypot(w.x-p.position.x,w.z-p.position.z)>25;if(w){projected.set(w.x,w.y+1.1,w.z).project(camera);node.hidden||=projected.z>1||Math.abs(projected.x)>1;node.style.left=(projected.x*.5+.5)*innerWidth+'px';node.style.top=(-projected.y*.5+.5)*innerHeight+'px';node.textContent=w.alerted?'ALERT':w.awareness>.15?'? '+Math.round(w.awareness*100)+'%':'WATCHER';node.style.setProperty('--awareness',w.awareness*100+'%');}}
 dust+=dt;if(active&&!paused&&p.speed>1&&p.onGround&&dust>.15&&settings.particles>0){particles.emit(p.position.x,p.position.y,p.position.z);dust=0;}particles.update(dt);audio.setMood({intensity:s.hunt?.85:s.cloaked?.15:.35,region:3});audio.update(dt);shell.update(dt);debug.update(dt);
}
function report(){const m=runtime.metrics,s=loop.state,p=mover.player;return {build:'PCOCK-S4-GHOST-20260930',stage:'S4',game:config.id,funOnly,fps:m.fps,frameMs:m.frameMs,cpuMs:m.cpuMs,drawCalls:m.drawCalls,triangles:m.triangles,textureMB:Math.round(assets.textureMB*100)/100,assets:{...assets.states},activeChunks:3,pools:{scorePops:{active:hud.pops.active,capacity:hud.pops.capacity},dust:{active:particles.pool.active,capacity:particles.pool.capacity},watchers:{active:loop.watchers.length,capacity:13}},heapMB:performance.memory?Math.round(performance.memory.usedJSHeapSize/1048576):null,preset:runtime.preset,renderScale:m.renderScale,dpr:m.dpr,stress:query.has('stress'),contextLost:m.contextLost,screen:choosing?'contracts':shell.screen,contract:{...s,title:loop.contract.title,type:loop.contract.type,limit:loop.contract.limit,targets:loop.contract.targets,watchers:loop.watchers.map(w=>({x:w.x,y:w.y,z:w.z,yaw:w.yaw,awareness:w.awareness,alerted:w.alerted,boss:w.boss}))},player:{x:p.position.x,y:p.position.y,z:p.position.z,speed:p.speed,onGround:p.onGround,gliding:p.gliding,jumps:p.jumps},unlocked:unlocked(),currency:save.state.games[config.id].currency,storyMilestone:!!save.state.profile.story.ghostMilestone,errors:(window.__PCOCK_ERRORS||[]).slice(-5),saveError:save.error};}
const debug=createDebug(root,report,query.has('debug')&&query.get('hud')!=='0');window.PCOCK={ready:false,report,get settings(){return save.state.settings;},get save(){return structuredClone(save.state);},setPreset(v){if(['Auto','Low','Medium','High','Ultra'].includes(v)){settings.preset=v;save.write();settingsChanged();}}};settingsChanged();shell.open('title');if(shot){if(['shop','menu'].includes(shot))shell.open(shot==='menu'?'title':'shop');else if(shot==='results')shell.showPreviewResults();else{shell.play(false);startContract(shot==='warden'?16:1);preview=true;loop.step(0,mover.player,false);if(shot==='roof')mover.place(-42,-28,6);if(shot==='sewer')mover.place(18,24,-3);if(shot==='warden')mover.place(3,-25,0);}if(query.get('hud')==='0'){bar.hidden=true;hud.show(false);actions.hidden=banner.hidden=stats.hidden=meters.hidden=true;}}
await renderer.compileAsync(scene,camera);runtime.start(fixed,interpolate);window.PCOCK.ready=true;
resources.onDispose(()=>{ghostHudEditor.dispose();save.dispose();input.dispose();audio.dispose();hud.dispose();shell.dispose();debug.dispose();removeEventListener('keydown',keyDown);removeEventListener('keyup',keyUp);removeEventListener('blur',blur);});addEventListener('pagehide',()=>resources.dispose(),{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)shell.open('pause');});
