import {brand} from './brand.js';
import {Pool,spring} from './disposal.js';
import {levelProgress} from './save.js';
export function element(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;}
export function button(text,fn,className='pc-button'){const b=element('button',className,text);b.type='button';b.addEventListener('click',fn);return b;}
export function createHud(root,save,config){
  const hud=element('section','pc-hud');hud.setAttribute('aria-label','Adventure HUD');hud.innerHTML=`<div class="pc-hud-top"><div class="pc-balance"><span>❧</span><div><small>FEATHERS</small><strong data-feathers>0</strong></div></div><div class="pc-level" aria-label="Player level"><span data-level>1</span></div><div class="pc-game-currency"><small>${config.currency.toUpperCase()}</small><strong data-currency>0</strong></div><button class="pc-button pc-pause" data-pause aria-label="Pause">Ⅱ</button></div><div class="pc-mission"><small>FOUNDATION COURSE</small><strong data-mission>Follow the feather signal</strong><p data-tutorial>Move → jump → collect → finish</p><div class="pc-hit-pips" aria-label="Two hit points"><i></i><i></i></div><div class="pc-combo"><span></span></div></div><div class="pc-compass"><span data-compass>N</span><canvas width="96" height="96" data-minimap aria-label="Test scene minimap"></canvas></div><div class="pc-controls"><div class="pc-stick" data-stick role="group" aria-label="Movement joystick"><div data-knob></div></div><div class="pc-abilities"><button data-jump aria-label="Jump and hold to glide"><span>↑</span>JUMP</button><button data-dash aria-label="Hold to dash"><span>»</span>SPRINT</button><button data-interact aria-label="Interact, same as the E key"><span>E</span>INTERACT</button></div></div><p class="pc-desktop-help">WASD move · drag to look · Space jump / hold to glide · Shift dash · Esc pause</p><div class="pc-world-bubble" data-bubble hidden>Finish course · E / tap</div>`;
  root.append(hud);const effects=element('div','pc-effects'),flash=element('div','pc-flash'),damage=element('div','pc-damage');effects.append(flash,damage);root.append(effects);
  const pops=new Pool(20,()=>{const el=element('div','pc-score-pop');el.hidden=true;effects.append(el);return {el,active:false,age:0,x:0,y:0,scale:{value:.5,velocity:0}};});
  const feather={value:save.state.profile.feathers,velocity:0},currency={value:save.state.games[config.id].currency,velocity:0},kick={value:0,velocity:0},flashState={value:0,velocity:0},damageState={value:0,velocity:0};
  const nodes={};for(const k of ['feathers','currency','level','mission','tutorial','compass','minimap','bubble','jump','dash','interact'])nodes[k]=hud.querySelector('[data-'+k+']');const ctx=nodes.minimap.getContext('2d');let shown=false;
  function update(dt,info={}){const profile=save.state.profile,game=save.state.games[config.id],level=levelProgress(profile.xp);nodes.feathers.textContent=Math.round(spring(feather,profile.feathers,dt,9)).toLocaleString();nodes.currency.textContent=Math.round(spring(currency,game.currency,dt,9)).toLocaleString();nodes.level.textContent=level.level;hud.querySelector('.pc-level').style.setProperty('--xp-progress',Math.round(level.fraction*360)+'deg');nodes.jump.style.setProperty('--cooldown',Math.round((info.glideFraction||0)*360)+'deg');nodes.dash.style.setProperty('--cooldown',Math.round((info.dashCooldown||0)*360)+'deg');root.style.setProperty('--control-opacity',save.state.settings.controlOpacity);hud.classList.toggle('pc-left-handed',save.state.settings.leftHanded);hud.classList.toggle('pc-controls-compact',save.state.settings.layout==='compact');hud.querySelector('.pc-combo span').style.width=Math.min(100,(info.pickups||0)*20)+'%';if(info.tutorial)nodes.tutorial.textContent=info.tutorial;if(info.remaining!==undefined)nodes.mission.textContent=info.remaining+' signal feathers to find';if(shown){nodes.compass.textContent='N · '+Math.round((info.yaw||0)*180/Math.PI)+'°';ctx.fillStyle=brand.colors.surface;ctx.fillRect(0,0,96,96);ctx.strokeStyle=brand.colors.primary;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(48,83);ctx.lineTo(48,16);ctx.stroke();ctx.fillStyle=brand.colors.gold;for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(48,70-i*10,2.5,0,6.28);ctx.fill();}ctx.fillStyle=brand.colors.text;ctx.beginPath();ctx.arc(48+(info.x||0)*1.6,55+(info.z||0)*1.6,4,0,6.28);ctx.fill();}
    for(const p of pops.items)if(p.active){p.age+=dt;const s=spring(p.scale,1,dt,15);p.el.style.transform=`translate(${p.x}px,${p.y-p.age*p.age*55}px) scale(${s})`;p.el.style.opacity=String(Math.max(0,1-(p.age/.9)**3));if(p.age>.9){p.el.hidden=true;pops.release(p);}}flash.style.opacity=String(Math.max(0,spring(flashState,0,dt,14)));damage.style.opacity=String(Math.max(0,spring(damageState,0,dt,10)));spring(kick,0,dt,12);
  }
  function pop(text,x=innerWidth*.7,y=innerHeight*.28,type='score'){const p=pops.acquire();if(!p)return;p.age=0;p.x=x;p.y=y;p.scale.value=.5;p.scale.velocity=12;p.el.textContent=text;p.el.className='pc-score-pop '+(type==='close'?'pc-close':type==='streak'?'pc-streak':'');p.el.hidden=false;}
  function hit(){damageState.value=.65;kick.value=.16;navigator.vibrate?.(35);const pips=hud.querySelectorAll('.pc-hit-pips i');pips[1].classList.add('spent');}
  function feedback(type,text,x,y){pop(text,x,y,type);flashState.value=type==='damage'?0:.16;kick.value=type==='close'?.06:.03;}
  return {hud,pops,update,pop,feedback,hit,reset(){for(const p of pops.items)p.el.hidden=true;pops.reset();for(const pip of hud.querySelectorAll('.pc-hit-pips i'))pip.classList.remove('spent');},get cameraKick(){return kick.value;},show(value){shown=value;hud.hidden=!value;},setBubble(x,y,visible){nodes.bubble.hidden=!visible;nodes.bubble.style.transform=`translate(${x}px,${y}px)`;},onPause(fn){hud.querySelector('[data-pause]').onclick=fn;},onFinish(fn){nodes.bubble.onclick=fn;},onInteract(fn){nodes.interact.onclick=fn;nodes.interact.addEventListener('pointerdown',e=>{e.stopPropagation();});},dispose(){hud.remove();effects.remove();pops.reset();}};
}
