export function createInput(canvas,root,settings){
  const keys=new Set(),pointers=new Map(),state={x:0,z:0,jump:false,dash:false,lookX:0,lookY:0,jumpBuffer:0},stick=root.querySelector('[data-stick]'),knob=root.querySelector('[data-knob]');let enabled=false;
  // HUD buttons can retain focus after a menu closes. Only active form editors
  // own movement keys; enable(false) already blocks gameplay in menus.
  function editable(target){return target?.closest('input,select,textarea,[contenteditable]:not([contenteditable="false"])');}
  const down=e=>{if(!enabled||editable(e.target))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!keys.has(e.code))state.jumpBuffer=.14;keys.add(e.code);};const up=e=>keys.delete(e.code);
  function bind(el,kind){if(!el)return;el.addEventListener('pointerdown',e=>{if(!enabled)return;if(kind==='look'&&e.button!==0)return;e.preventDefault();const rect=el.getBoundingClientRect();pointers.set(e.pointerId,{kind,x:e.clientX,y:e.clientY,ox:rect.left+rect.width/2,oy:rect.top+rect.height/2});el.setPointerCapture(e.pointerId);if(kind==='jump')state.jumpBuffer=.14;});el.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;if(p.kind==='stick'){const dx=e.clientX-p.ox,dz=e.clientY-p.oy,n=Math.max(40,Math.hypot(dx,dz));state.x=dx/n;state.z=dz/n;knob.style.transform=`translate(${state.x*30}px,${state.z*30}px)`;}if(p.kind==='look'){state.lookX+=(e.clientX-p.x)*settings.sensitivity;state.lookY+=(e.clientY-p.y)*settings.sensitivity;}p.x=e.clientX;p.y=e.clientY;});const release=e=>{const p=pointers.get(e.pointerId);if(!p)return;if(p.kind==='stick'){state.x=state.z=0;knob.style.transform='';}pointers.delete(e.pointerId);};for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,release);}
  bind(canvas,'look');bind(stick,'stick');bind(root.querySelector('[data-jump]'),'jump');bind(root.querySelector('[data-dash]'),'dash');
  function reset(){keys.clear();pointers.clear();Object.assign(state,{x:0,z:0,jump:false,dash:false,lookX:0,lookY:0,jumpBuffer:0});if(knob)knob.style.transform='';}
  const blur=()=>reset();addEventListener('keydown',down);addEventListener('keyup',up);addEventListener('blur',blur);addEventListener('visibilitychange',blur);
  const sampleState={x:0,z:0,jump:false,dash:false,jumpBuffer:0,lookX:0,lookY:0};
  function sample(dt){let x=state.x,z=state.z;state.jump=keys.has('Space');state.dash=keys.has('ShiftLeft')||keys.has('ShiftRight');for(const p of pointers.values()){if(p.kind==='jump')state.jump=true;if(p.kind==='dash')state.dash=true;}if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;if(keys.has('KeyW')||keys.has('ArrowUp'))z--;if(keys.has('KeyS')||keys.has('ArrowDown'))z++;const pad=navigator.getGamepads?.()[0];if(pad){if(Math.abs(pad.axes[0])>.18)x+=pad.axes[0];if(Math.abs(pad.axes[1])>.18)z+=pad.axes[1];if(pad.buttons[0]?.pressed&&!state.jump)state.jumpBuffer=.12;state.jump||=pad.buttons[0]?.pressed;state.dash||=pad.buttons[1]?.pressed;}const len=Math.max(1,Math.hypot(x,z));sampleState.x=x/len;sampleState.z=z/len;sampleState.jump=state.jump;sampleState.dash=state.dash;sampleState.jumpBuffer=state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);sampleState.lookX=state.lookX;sampleState.lookY=state.lookY;return sampleState;}
  return {state,sample,reset,enable(value){enabled=value;if(!value)reset();},consumeJump(){state.jumpBuffer=0;},dispose(){removeEventListener('keydown',down);removeEventListener('keyup',up);removeEventListener('blur',blur);removeEventListener('visibilitychange',blur);reset();},get enabled(){return enabled;}};
}
