import * as THREE from 'three';
import {brand,applyBrandCss} from './brand.js';
import {worldPalette as W} from './world-palette.js';
import {Resources} from './disposal.js';
import {createSave} from './save.js';
import {createEconomy} from './economy.js';
import {createRunnerRenderer,runnerProfiles} from './liberty-renderer.js';
import {createToon} from './toon.js';
import {createAssets} from './assets.js';
import {createInput} from './input.js';
import {createAudio} from './audio.js';
import {createParticles} from './particles.js';
import {ensureStyles} from './styles.js';
import {createMiniHudEditor} from './mini-hud-editor.js';
import {courses,perks,disclaimer,makeFrame} from './liberty-track.js';
import {createLibertyLoop} from './liberty-loop.js';
import {createLibertyWorld} from './liberty-world.js';
import {runnerBiome} from './liberty-biomes.js';
import {freshTour,dailyChallenge,tourGoals,settleTour,trailChoices,medalCount} from './liberty-tour.js';
await ensureStyles(['./fonts.css','./liberty-runner.css']);applyBrandCss();document.body.className='liberty-runner';document.title='Liberty Runner · PCOCK';
const root=document.getElementById('foundation-root');root.className='lr-root';
root.innerHTML=`<div class="lr-world"></div><div class="lr-vignette"></div>
<header class="lr-header"><a class="lr-wordmark" href="../index.html">PCOCK<span>LIBERTY RUNNER</span></a><div class="lr-header-right"><a class="lr-return-valley" href="../index.html?return=runner" aria-label="Return to Liberty Valley">← Valley</a><span class="lr-wallet"><i>◈</i> <b data-wallet>0</b> <small>$PDAI</small></span><button class="lr-settings-tab" data-settings aria-label="Settings">⚙ <span>Settings</span></button><button class="lr-icon" data-pause aria-label="Pause" hidden>Ⅱ</button></div></header>
<section class="lr-menu" aria-label="Main menu"><div class="lr-hero"><span class="lr-eyebrow">THE WORLD IS YOUR RUNWAY</span><h1>FREEDOM.<br>AT FULL SPEED.</h1><p>FIVE WORLDS. ONE FEARLESS PEACOCK.<br>Master the corners. One hit sends you back.</p><button class="lr-primary lr-play">LET’S RUN <span>↗</span></button><div class="lr-menu-links"><button data-shop>Upgrade perks</button><button data-settings>Settings & controls</button><button data-tour>Tour goals & trails</button></div><button class="lr-daily" data-daily></button></div><div class="lr-course-picker">${courses.map((c,i)=>`<button class="lr-course ${i===0?'selected':''}" data-course="${c.id}" aria-pressed="${i===0}"><span class="lr-course-art ${c.id}"><img src="../assets/runner/${c.id}.png" alt="${c.name}: ${c.description}" width="960" height="600" decoding="async"><span class="lr-map-number">0${i+1}</span></span><span><small>${c.tag}</small><strong>${c.name}</strong><em>${(c.length/1000).toFixed(1)} KM · ${c.loops.length} LOOPS · ${c.description}</em><span class="lr-best" data-best="${c.id}">NEW HORIZONS</span></span><b>↗</b></button>`).join('')}</div><div class="lr-menu-foot">AN ORIGINAL LIBERTY SWAP ADVENTURE <span>PC + MOBILE / SINGLE PLAYER</span></div></section>
<section class="lr-hud" hidden><div class="lr-readouts"><div><small>RUN TIME</small><strong data-time>00:00.00</strong></div><div><small>COLLECTED / $PDAI</small><strong class="lr-coin-number" data-coins>0</strong></div><div class="lr-speed"><small>SPEED / KM/H</small><strong data-speed>0</strong></div></div><div class="lr-chain"><strong data-score>0</strong><span data-combo>×1 FLOW</span><small data-feathers>✦ 0 / 3</small><small data-pace>CHASE YOUR FIRST RECORD</small></div><div class="lr-boost-meter"><span>GASLESS BOOST <b data-boost>100%</b></span><div><i data-charge></i></div><small data-shield></small></div><div class="lr-route"><span data-region>Sunrise Causeway</span><b data-distance>0 / 2600 m</b><div><i data-progress></i></div></div><div class="lr-message" role="status"></div><div class="lr-desktop-help">A / D STEER <i>·</i> SPACE JUMP + GLIDE <i>·</i> S + STEER DRIFT <i>·</i> S SLIDE <i>·</i> SHIFT BOOST</div><div class="lr-touch"><div data-stick aria-label="Steering pad"><span data-knob>↔</span><small>STEER</small></div><div class="lr-touch-actions"><button data-slide aria-label="Slide">↓<small>SLIDE</small></button><button data-dash aria-label="Boost">ϟ<small>BOOST</small></button><button data-jump aria-label="Jump and hold to glide">↑<small>JUMP / GLIDE</small></button></div></div></section>
<section class="lr-overlay" hidden><div class="lr-panel" role="dialog" aria-modal="true" aria-labelledby="lr-panel-title"></div></section><div class="lr-toast" role="status" hidden></div><pre class="lr-debug" hidden></pre>`;
const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],resources=new Resources(),save=createSave(),economy=createEconomy(save),query=new URLSearchParams(location.search),funOnly=query.get('fun')==='1';
const graphicsDefaults={preset:'Auto',renderScale:1,fpsCap:0,foliage:1,particles:1},graphics=()=>save.state.profile.story.libertyRunnerSettings||= {...graphicsDefaults};if(funOnly){for(const el of $$('[data-shop],[data-tour],[data-daily],.lr-wallet'))el.hidden=true;const note=document.createElement('p');note.className='lr-disclaimer';note.innerHTML='<b>FUN MODE</b> · Play any course now. No Liberty story progress, $PDAI, medals, records, rewards or unlocks will be saved.';$('.lr-hero').append(note);}
for(const k of Object.keys(graphicsDefaults))if(typeof graphics()[k]!==typeof graphicsDefaults[k])graphics()[k]=graphicsDefaults[k];
if(!['Auto','Low','Medium','High','Ultra'].includes(graphics().preset))graphics().preset='Auto';graphics().renderScale=Math.max(.6,Math.min(1,graphics().renderScale));if(graphics().version!==6){graphics().fpsCap=graphics().fpsCap===30?30:0;graphics().version=6;}if(![0,30,60,120,144].includes(graphics().fpsCap))graphics().fpsCap=0;
const settings=new Proxy({},{get:(_,k)=>Object.hasOwn(graphicsDefaults,k)?graphics()[k]:save.state.settings[k],set:(_,k,v)=>{if(Object.hasOwn(graphicsDefaults,k))graphics()[k]=v;else save.state.settings[k]=v;return true;}});
if(['Low','Medium','High','Ultra'].includes(query.get('preset')))settings.preset=query.get('preset');
const runtime=createRunnerRenderer($('.lr-world'),settings,resources),{scene,camera,renderer}=runtime,toon=createToon(resources),assets=createAssets(toon,resources,{originalCharacters:true,peacockFan:true}),audio=createAudio(settings),input=createInput(renderer.domElement,$('.lr-hud'),settings),actor=assets.standIn(),particles=createParticles(scene,resources);scene.add(actor.root);await assets.loadPeacock(actor);
renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;const tailScale=actor.tail.scale.clone();let dustTime=0;
// A fixed character budget and the supplied animation are retained from the shared loader.
const params={game:'gasless-run'},hud=$('.lr-hud'),menu=$('.lr-menu'),overlay=$('.lr-overlay'),panel=$('.lr-panel');
let loop,world,screen='title',settingsBack='title',selected=courses.some(c=>c.id===query.get('map'))?query.get('map'):'coast',time=0,runId='',paid=false,summary=null,slidePointer=null,queuedSlide=false,queuedBoost=false,coinCooldown=0,toastTimer=0,cameraSnap=true,retries=0,preview=!!query.get('shot');
const runnerHudEditor=createMiniHudEditor(root,{
 storageKey:'pcock.runner.hud.layouts.v1',layoutType:'PCOCK_LIBERTY_RUNNER_HUD_LAYOUT_V1',
 targets:[
  ['header','HEADER / RETURN / SETTINGS','.lr-header'],['readouts','TIME / COINS / SPEED','.lr-readouts'],
  ['chain','SCORE / FLOW / FEATHERS','.lr-chain'],['boost','BOOST METER','.lr-boost-meter'],
  ['route','ROUTE / PROGRESS','.lr-route'],['message','RUN MESSAGE','.lr-message'],
  ['help','PC CONTROL HELP','.lr-desktop-help'],['stick','STEERING PAD','[data-stick]'],
  ['actions','SLIDE / BOOST / JUMP','.lr-touch-actions'],['toast','POPUP NOTIFICATION','.lr-toast']
 ],
 previewSelectors:['.lr-hud'],
 previewCss:'.lr-root.pcock-mini-hud-editing .lr-hud{display:block!important}.lr-root.pcock-mini-hud-editing .lr-message,.lr-root.pcock-mini-hud-editing .lr-toast{display:block!important;visibility:visible!important;opacity:.94!important}.lr-root.pcock-mini-hud-mobile .lr-touch{display:block!important}.lr-root.pcock-mini-hud-pc .lr-touch{display:none!important}',
 onEnter(){screen='hud-edit';menu.hidden=true;overlay.hidden=true;hud.hidden=false;input.enable(false);},
 onExit(){hud.hidden=true;input.enable(false);}
});
function openRunnerHudEditor(){const back=settingsBack;runnerHudEditor.choose(()=>{screen=back;showSettings();});}

const backward=new THREE.Vector3(),shadowNormal=new THREE.Vector3(0,0,1);
const f=makeFrame(),future=makeFrame(),r=new THREE.Vector3(),u=new THREE.Vector3(),forward=new THREE.Vector3(),position=new THREE.Vector3(),goal=new THREE.Vector3(),look=new THREE.Vector3(),basis=new THREE.Matrix4(),q=new THREE.Quaternion();
const shadow=new THREE.Mesh(resources.own(new THREE.CircleGeometry(.65,20)),resources.own(new THREE.MeshBasicMaterial({color:W.outline,transparent:true,opacity:.24,depthWrite:false})));scene.add(shadow);
const streakPositions=new Float32Array(20*6),streakGeometry=resources.own(new THREE.BufferGeometry());streakGeometry.setAttribute('position',new THREE.BufferAttribute(streakPositions,3));const streaks=new THREE.LineSegments(streakGeometry,resources.own(new THREE.LineBasicMaterial({color:brand.colors.pulseCyan,transparent:true,opacity:.22,depthTest:false,depthWrite:false})));streaks.frustumCulled=false;streaks.renderOrder=10;camera.add(streaks);scene.add(camera);
const trailSpectrum=[brand.colors.pulseCyan,brand.colors.pulseBlue,brand.colors.pulsePurple,brand.colors.pulseMagenta,brand.colors.gold].map(c=>new THREE.Color(c));
const timeText=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${(n%60).toFixed(2).padStart(5,'0')}`;
const tour=()=>save.state.profile.story.libertyRunnerTour||freshTour(),bests=()=>tour().records;let dailyMode=null;
function selectCourse(id){selected=id;for(const c of $$('[data-course]')){const chosen=c.dataset.course===id;c.classList.toggle('selected',chosen);c.setAttribute('aria-pressed',chosen);}makeRun(id,true);}
function toast(text){$('.lr-toast').textContent=text;$('.lr-toast').hidden=false;toastTimer=2.5;}
function refresh(){const game=save.state.games[params.game];$('[data-wallet]').textContent=game.currency.toLocaleString();for(const c of courses){const best=bests()[c.id];$(`[data-best="${c.id}"]`).textContent=best?`${'★'.repeat(best.stars)}${'☆'.repeat(3-best.stars)} · ${best.rank} RANK · ${timeText(best.time)}`:'☆☆☆ · SET YOUR FIRST RECORD';}const daily=dailyChallenge(),done=tour().daily[daily.key];$('[data-daily]').textContent=`${done?'✓ COMPLETE':'TODAY +200 $PDAI'} · ${daily.title} · ${courses.find(c=>c.id===daily.map).name} ↗`;streaks.material.color.set(({pulse:brand.colors.pulseCyan,gold:brand.colors.gold,magenta:brand.colors.pulseMagenta,rainbow:brand.colors.pulsePurple})[tour().trail]||brand.colors.pulseCyan);if(save.error)toast('Saving is unavailable in this browser.');}
function effect(type,message){if(type==='coin'){if(coinCooldown<=0){audio.sound('pickup');coinCooldown=.065;if(settings.particles>0)particles.emit(actor.root.position.x,actor.root.position.y+.8,actor.root.position.z);}}else if(type==='hit'||type==='recover')audio.sound('damage');else if(type==='jump'||type==='boost')audio.sound('jump');else if(['finish','shield','power','feather','drift','loop','checkpoint'].includes(type))audio.sound('buy');}
function makeRun(id,forMenu=false){world?.dispose();particles.reset();loop=createLibertyLoop(id,save.state.games[params.game].upgrades,effect);world=createLibertyWorld(scene,loop.track,runnerProfiles[runtime.preset]);shadow.material.map=world.shadowTexture;shadow.material.needsUpdate=true;shadow.material.opacity=.68;const biome=runnerBiome(id);scene.fog=new THREE.Fog(biome.fog,150,380);world.setQuality(runnerProfiles[runtime.preset],settings);runtime.sun.intensity=biome.night?2.5:3.1;scene.traverse(o=>{if(o.isHemisphereLight){o.intensity=biome.night?1.8:2.1;o.color.set(biome.colors.sky);}});camera.far=650;camera.updateProjectionMatrix();scene.background=null;if(forMenu){loop.state.distance=id==='coast'?880:130;loop.state.previous=loop.state.distance;}world.update(loop,0);cameraSnap=true;}
function setScreen(name){screen=name;input.enable(name==='run'&&!preview);slidePointer=null;queuedSlide=queuedBoost=false;menu.hidden=name!=='title';hud.hidden=name!=='run';$('[data-pause]').hidden=name!=='run';overlay.hidden=['run','title'].includes(name);document.activeElement?.blur();}
function play(){preview=false;retries=0;makeRun(selected);runId='liberty-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));paid=false;summary=null;setScreen('run');if(dailyMode){loop.state.message=dailyMode.description.toUpperCase();loop.state.messageTime=5;}audio.unlock();refresh();}
function title(){dailyMode=null;preview=false;makeRun(selected,true);setScreen('title');refresh();}
function panelHead(kicker,title){panel.innerHTML=`<small class="lr-eyebrow">${kicker}</small><h2 id="lr-panel-title">${title}</h2>`;}
function button(text,action,primary=false){const b=document.createElement('button');b.textContent=text;b.className=primary?'lr-primary':'lr-secondary';b.onclick=action;return b;}
function actions(...items){const row=document.createElement('div');row.className='lr-panel-actions';items.forEach(i=>row.append(i));panel.append(row);}
function pause(){if(screen!=='run'||preview)return;setScreen('pause');panelHead('TAKE A BREATHER','Keep your freedom.');panel.insertAdjacentHTML('beforeend',`<p>${loop.track.config.name} · ${Math.floor(loop.state.distance)} m<br>Your run is waiting right here.</p>`);actions(button('Resume',()=>setScreen('run'),true),button('Settings & controls',showSettings),button('Restart run',play),button('Bank coins & exit',()=>finish(false)));}
function finish(success=true){if(paid)return;paid=true;const s=loop.state;s.success=success,tourSource=funOnly?structuredClone(tour()):tour(),result=settleTour(tourSource,loop.track.config,s,success,dailyMode),award=funOnly?{ok:true,currency:0,feathers:0,xp:0,multiplier:1,newBest:false}:economy.award(params.game,{id:runId,earned:s.coins+result.bonus,score:Math.floor(s.score),xp:Math.max(10,s.coins/2),stars:Math.max(1,result.stars),mission:'liberty-tour-'+selected,stats:{distance:s.distance,jumps:s.jumps,pickups:s.coins}});
  if(!funOnly&&award.ok)save.update(v=>{v.profile.story.libertyRunnerTour=result.tour;});summary={success,coins:s.coins,banked:funOnly?0:(award.currency||0),time:s.age,best:funOnly?false:result.newBest,hits:s.hits,score:Math.floor(s.score),combo:s.maxCombo,feathers:s.feathers,drifts:s.drifts,...result,earned:funOnly?[]:result.earned,bonus:funOnly?0:result.bonus,funOnly};showResults();refresh();
}
function showResults(){setScreen('results');panelHead(summary.best?'A NEW PERSONAL BEST':summary.success?'COURSE COMPLETE':'COINS BANKED',summary.success?`${summary.rank} RANK · You ran free.`:'Every run counts.');panel.insertAdjacentHTML('beforeend',`<p>${loop.track.config.name} · ${(loop.track.config.length/1000).toFixed(1)} km</p><div class="lr-result-grid"><div><small>TIME</small><strong>${timeText(summary.time)}</strong></div><div><small>$PDAI BANKED</small><strong>+${summary.banked}</strong></div><div><small>SCORE / MAX FLOW</small><strong>${summary.score.toLocaleString()}</strong><small>×${summary.combo} · ${summary.drifts} DRIFTS · ${summary.hits} HITS</small></div></div><div class="lr-goals">${summary.goals.map(g=>`<div class="${summary.success&&g.done?'complete':''}"><b>${summary.success&&g.done?'★':'☆'}</b><span>${g.title}<small>${g.value}</small></span></div>`).join('')}</div><p>${summary.funOnly?'FUN MODE · score is for this run only. No medals, records, rewards or Liberty progress were saved.':summary.earned.length?`First-time rewards: ${summary.earned.join(' · ')}. +${summary.bonus} bonus $PDAI.`:'Each new course medal pays 100 $PDAI. Chase all 15 to unlock every boost trail.'}</p>`);const resultActions=[button('Run again',play,true)];if(!funOnly)resultActions.push(button('Upgrade perks',()=>shop('results')));resultActions.push(button('Choose course',title));actions(...resultActions);panel.insertAdjacentHTML('beforeend',`<p class="lr-disclaimer">${disclaimer}</p>`);}
function showTour(){setScreen('tour');panelHead('FIVE WORLDS / FIFTEEN MEDALS',`${medalCount(tour())} / 15 medals`);const c=courses.find(c=>c.id===selected),record=bests()[selected];panel.insertAdjacentHTML('beforeend',`<p>${c.name} · ${(c.length/1000).toFixed(1)} km · ${c.loops.length} loops<br>Each first-time medal pays 100 fictional $PDAI. Collect medals across all maps to unlock boost trails.</p><div class="lr-goals">${[{id:'coins',text:`Collect ${c.coinGoal} coins`},{id:'feathers',text:'Find 3 feathers on the high routes'},{id:'time',text:`Finish in under ${timeText(c.par)}`}].map(g=>`<div><b>${tour().claimed.includes(c.id+':'+g.id)?'★':'☆'}</b><span>${g.text}</span></div>`).join('')}</div><p>Chain coins and clean obstacle passes for up to ×5 score. Hold Slide and steer into a bend to earn a drift bonus and refill boost. Dash pads launch you forward; orange spring pads launch you into the air. M pickups attract coins and S pickups grant an automatic dodge.</p><h3>YOUR BOOST TRAIL</h3><div class="lr-trails"></div>`);for(const choice of trailChoices){const unlocked=medalCount(tour())>=choice.need,b=button(`${choice.name}${tour().trail===choice.id?' ✓':unlocked?'':` · ${choice.need} medals`}`,()=>{save.update(v=>{const t=v.profile.story.libertyRunnerTour||=freshTour();t.trail=choice.id;});refresh();showTour();});b.disabled=!unlocked;$('.lr-trails').append(b);}actions(button('Back to courses',title,true));}
function shop(back='title'){setScreen('shop');panelHead('MAKE YOUR NEXT RUN BETTER','A little more freedom.');panel.insertAdjacentHTML('beforeend',`<p class="lr-shop-wallet"><b>${save.state.games[params.game].currency}</b> fictional $PDAI available</p><div class="lr-perks"></div>`);for(const perk of perks){const quote=economy.quote(params.game,perk),card=document.createElement('article');card.className='lr-perk';card.innerHTML=`<small>${perk.short.toUpperCase()} / LEVEL ${Math.min(perk.max,quote.level)} OF ${perk.max}</small><h3>${perk.title}</h3><p>${perk.description}</p><div class="lr-perk-effect">${perk.effect(quote.level)}${quote.maxed?'':`<br><span>→ ${perk.effect(quote.level+1)}</span>`}</div>`;const buy=button(quote.maxed?'MAXED':`Upgrade · ${quote.cost} $PDAI`,()=>{const result=economy.purchase(params.game,perk);if(result.ok){audio.sound('buy');shop(back);refresh();toast(`${perk.short} upgraded`);}},true);buy.dataset.purchase=perk.id;buy.disabled=quote.maxed||quote.cost>save.state.games[params.game].currency;card.append(buy);$('.lr-perks').append(card);}actions(button('Back',()=>back==='results'?showResults():title()));}
function closeSettings(){if(settingsBack==='pause'){setScreen('run');pause();}else if(settingsBack==='results')showResults();else if(settingsBack==='tour')showTour();else if(settingsBack==='shop')shop(summary?'results':'title');else {setScreen(settingsBack);refresh();}}
function showSettings(){if(screen==='settings')return;settingsBack=screen;setScreen('settings');panelHead('YOUR WAY TO PLAY','Settings');panel.insertAdjacentHTML('beforeend',`<p>Auto adjusts graphics for smoother play. Your run stays paused while you change settings.</p><div class="lr-settings"><label>Visual quality<select data-quality>${['Auto','Low','Medium','High','Ultra'].map(p=>`<option ${settings.preset===p?'selected':''}>${p}</option>`).join('')}</select></label><p class="lr-quality-status" data-quality-status></p><label>Resolution <span><select data-resolution>${[1,.9,.8,.7,.6].map(v=>`<option value="${v}" ${settings.renderScale===v?'selected':''}>${Math.round(v*100)}%</option>`).join('')}</select></span></label><label>Frame limit<select data-fps>${[0,144,120,60,30].map(v=>`<option value="${v}" ${settings.fpsCap===v?'selected':''}>${v?v+' FPS':'Unlimited'}</option>`).join('')}</select></label><label><span>Grass & flowers</span><input data-foliage type="checkbox" ${settings.foliage?'checked':''}></label><label><span>Dust & pickup particles</span><input data-particles type="checkbox" ${settings.particles?'checked':''}></label><label><span>Sound & music</span><input data-sound type="checkbox" ${settings.sfxVolume?'checked':''}></label><label><span>Reduced motion</span><input data-motion type="checkbox" ${settings.reduceMotion?'checked':''}></label></div><details class="lr-controls-copy"><summary>Controls & run tips</summary><p><b>PC</b> A/D or arrows steer. Space jumps; hold to glide. S slides; hold S while steering into a bend to drift and refill boost. Shift boosts. Escape pauses.<br><br><b>MOBILE</b> Move the left thumb pad; use the right buttons to jump, glide, slide and boost. Landscape gives the widest view.<br><br>Steer right at a fork for high-route feathers. Chain coins for a ×5 score multiplier. Collect M magnets and S automatic dodges; use dash and spring pads. Actual obstacle hits and missed jumps restart the course and clear the unbanked run coins. $PDAI buys permanent perks between runs.</p></details><p class="lr-disclaimer">${disclaimer}</p>`);
  const changed=()=>{runtime.applySettings();world.update(loop,time);save.write();updateQualityStatus();};$('[data-quality]').onchange=e=>{settings.preset=e.target.value;changed();};$('[data-resolution]').onchange=e=>{settings.renderScale=Number(e.target.value);changed();};$('[data-fps]').onchange=e=>{settings.fpsCap=Number(e.target.value);changed();};for(const key of ['foliage','particles'])$(`[data-${key}]`).onchange=e=>{settings[key]=e.target.checked?1:0;if(key==='particles')particles.reset();changed();};$('[data-sound]').onchange=e=>{settings.sfxVolume=e.target.checked?.35:0;settings.musicVolume=e.target.checked?.16:0;audio.apply();save.write();};$('[data-motion]').onchange=e=>{settings.reduceMotion=e.target.checked;save.write();};actions(button(settingsBack==='run'?'Resume run':settingsBack==='pause'?'Back to pause':'Back',closeSettings,true),button('Resize HUD',openRunnerHudEditor),button('Restore defaults',()=>{Object.assign(graphics(),graphicsDefaults);settings.reduceMotion=false;changed();screen=settingsBack;showSettings();}));updateQualityStatus();
}
function updateQualityStatus(){const el=$('[data-quality-status]');if(el)el.textContent=`Active: ${runtime.preset} · ${runtime.metrics.bufferWidth} × ${runtime.metrics.bufferHeight}${runtime.metrics.softwareGraphics?' · Software graphics':' · Hardware graphics'}${runtime.metrics.lastRunFPS?' · Last run '+runtime.metrics.lastRunFPS+' FPS':''}`;}
$('.lr-play').onclick=play;$('[data-pause]').onclick=pause;$('[data-shop]').onclick=()=>shop();for(const b of $$('[data-settings]'))b.onclick=showSettings;$('[data-tour]').onclick=showTour;$('[data-daily]').onclick=()=>{dailyMode=dailyChallenge();selectCourse(dailyMode.map);play();};
for(const b of $$('[data-course]'))b.onclick=()=>{dailyMode=null;selectCourse(b.dataset.course);};
const slide=$('[data-slide]'),slideDown=e=>{if(screen!=='run')return;e.preventDefault();queuedSlide=true;slidePointer=e.pointerId;slide.setPointerCapture(e.pointerId);},slideUp=e=>{if(e.pointerId===slidePointer)slidePointer=null;};slide.addEventListener('pointerdown',slideDown);for(const e of ['pointerup','pointercancel','lostpointercapture'])slide.addEventListener(e,slideUp);$('[data-dash]').addEventListener('pointerdown',()=>{if(screen==='run')queuedBoost=true;});
const key=e=>{if(screen==='run'&&!e.repeat){if(['KeyS','ArrowDown'].includes(e.code))queuedSlide=true;if(['ShiftLeft','ShiftRight'].includes(e.code))queuedBoost=true;}if(e.code==='Escape'){e.preventDefault();if(screen==='run')pause();else if(screen==='pause')setScreen('run');else if(screen==='settings')closeSettings();}},blur=()=>{input.reset();slidePointer=null;queuedSlide=queuedBoost=false;if(screen==='run')pause();},visibility=()=>{if(document.hidden)blur();};addEventListener('keydown',key);addEventListener('blur',blur);addEventListener('visibilitychange',visibility);
function retryCrash(){const reason=loop.state.crashReason;loop.reset();retries++;particles.reset();input.reset();slidePointer=null;queuedSlide=queuedBoost=false;runId='liberty-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+retries);paid=false;summary=null;cameraSnap=true;loop.state.message=reason.toUpperCase()+' · BACK TO THE START';loop.state.messageTime=3;world.update(loop,time);}
function fixed(dt){coinCooldown-=dt;if(screen!=='run'||preview)return;const c=input.sample(dt);loop.step(dt,{steer:c.x,jump:c.jump||c.jumpBuffer>0,slide:c.z>.4||slidePointer!==null||queuedSlide,boost:c.dash||queuedBoost});input.consumeJump();queuedSlide=queuedBoost=false;if(loop.state.crashed)retryCrash();else if(loop.state.ended)finish(true);}
const scoreEl=$('[data-score]'),comboEl=$('[data-combo]'),feathersEl=$('[data-feathers]'),paceEl=$('[data-pace]'),speedEl=$('[data-speed]'),coinsEl=$('[data-coins]'),timeEl=$('[data-time]'),distanceEl=$('[data-distance]'),chargeEl=$('[data-charge]'),boostEl=$('[data-boost]'),shieldEl=$('[data-shield]'),progressEl=$('[data-progress]'),regionEl=$('[data-region]'),messageEl=$('.lr-message');let hudTick=0;
function interpolate(alpha,dt){time+=dt;toastTimer-=dt;if(toastTimer<=0)$('.lr-toast').hidden=true;const s=loop.state,moving=screen==='run'&&!preview,mix=moving?alpha:1,d=s.previous+(s.distance-s.previous)*mix,x=s.px+(s.x-s.px)*mix,y=s.py+(s.y-s.py)*mix;
  trackFrame(d,s.route);position.set(f.x+f.rx*x+f.ux*y,f.y+f.uy*y+.06,f.z+f.rz*x+f.uz*y);actor.root.position.copy(position);basis.makeBasis(backward.copy(r).negate(),u,forward);actor.root.quaternion.setFromRotationMatrix(basis);actor.root.scale.set(1,s.slide>0?.52:1,1);if(s.drifting)actor.root.rotateZ(-(loop.track.cornerAt(d)?.direction||0)*.22);if(moving){if(actor.walk&&!actor.walk.isRunning())actor.walk.reset().play();actor.walk?.setEffectiveTimeScale(Math.min(2.8,1.2+s.speed/55));}else actor.walk?.stop();actor.mixer?.update(moving?dt:0);if(!moving)for(const a of actor.rest||[])a.arm.quaternion.copy(a.pose);actor.root.visible=true;shadow.material.opacity=s.grace>0?.38:.68;
  shadow.position.set(f.x+f.rx*x+f.ux*.035,f.y+f.uy*.035,f.z+f.rz*x+f.uz*.035);shadow.quaternion.setFromUnitVectors(shadowNormal,u);shadow.scale.setScalar(Math.max(.65,1.8-y*.1));shadow.visible=settings.shadows!=='off'&&s.y>=0&&!loop.track.gapAt(d);
  const gliding=moving&&!s.grounded&&s.vy<0&&s.glide>0;actor.tail.scale.copy(tailScale);actor.tail.animate?.(dt,{speed:moving?s.speed/7:0,gliding,reduceMotion:settings.reduceMotion});
  dustTime+=dt;particles.setEmber(s.boost>0);if(moving&&s.grounded&&dustTime>.07&&settings.particles>0){particles.emit(position.x-forward.x*.4,position.y,position.z-forward.z*.4);dustTime=0;}particles.update(dt);
  if(tour().trail==='rainbow'){const phase=time*2,k=Math.floor(phase)%trailSpectrum.length;streaks.material.color.copy(trailSpectrum[k]).lerp(trailSpectrum[(k+1)%trailSpectrum.length],phase%1);}streaks.visible=moving&&s.boost>0&&!settings.reduceMotion;if(streaks.visible){for(let i=0;i<20;i++){const theta=i*2.39996,z=-3-((i*.617-time*4)%1+1)%1*10,rad=3.4+(i%3)*.5;streakPositions.set([Math.cos(theta)*rad,Math.sin(theta)*rad,z,Math.cos(theta)*rad,Math.sin(theta)*rad,z-2.1],i*6);}streakGeometry.attributes.position.needsUpdate=true;}
  const narrow=camera.aspect<.8,menuView=screen==='title';goal.copy(position).addScaledVector(forward,menuView?-19:narrow?-16:-10.8).addScaledVector(u,menuView?16:4.8);if(menuView)goal.addScaledVector(r,selected==='coast'?-50:-16);
  look.copy(position).addScaledVector(forward,menuView?35:14).addScaledVector(u,1.9);camera.position.lerp(goal,cameraSnap?1:1-Math.exp(-dt*12));basis.lookAt(camera.position,look,u);q.setFromRotationMatrix(basis);camera.quaternion.slerp(q,cameraSnap?1:1-Math.exp(-dt*12));cameraSnap=false;camera.fov+=( (narrow?68:64)+(s.boost>0&&!settings.reduceMotion?10:0)-camera.fov)*Math.min(1,dt*5);camera.updateProjectionMatrix();
  toon.time.value=settings.reduceMotion?0:time;renderer.getDrawingBufferSize(toon.resolution.value);world.update(loop,preview?3:time);audio.setMood({region:selected==='coast'?0:2,intensity:moving?.45+(s.boost>0?.35:0):.08});audio.update(dt);
  hudTick+=dt;if(hudTick>.07){hudTick=0;scoreEl.textContent=Math.floor(s.score).toLocaleString();comboEl.textContent=`×${s.combo} FLOW`;comboEl.style.color=s.combo>=3?brand.colors.gold:brand.colors.pulseCyan;feathersEl.textContent=`✦ ${s.feathers} / 3${s.magnetTime>0?' · MAGNET '+Math.ceil(s.magnetTime)+'s':''}`;const split=s.splits.length-1,old=bests()[selected]?.splits?.[split];paceEl.textContent=old?`${s.splits[split]-old>0?'+':''}${(s.splits[split]-old).toFixed(2)}s VS BEST · KM ${split+1}`:dailyMode?dailyMode.description.toUpperCase():'CHASE YOUR PERSONAL BEST';speedEl.textContent=Math.round(s.speed*3.6);coinsEl.textContent=String(s.coins).padStart(3,'0');timeEl.textContent=timeText(s.age);distanceEl.textContent=`${Math.floor(s.distance)} / ${loop.track.config.length} m`;chargeEl.style.width=s.charge+'%';boostEl.textContent=s.boost>0?'ACTIVE':Math.round(s.charge)+'%';shieldEl.textContent=s.shield?`${s.shield} SHIELD${s.shield>1?'S':''} READY`:s.route?'HIGH ROUTE · SPEED BONUS':'FOLLOW YOUR OWN PATH';progressEl.style.width=(s.distance/loop.track.config.length*100)+'%';regionEl.textContent=loop.track.config.sections[Math.min(6,Math.floor(s.distance/loop.track.config.length*7))];messageEl.textContent=s.messageTime>0?s.message:'';messageEl.hidden=!messageEl.textContent;if(query.has('debug'))$('.lr-debug').textContent=JSON.stringify(report(),null,1);}
}
function trackFrame(d,route){loop.track.sample(d,route,f);r.set(f.rx,0,f.rz);u.set(f.ux,f.uy,f.uz);forward.set(f.fx,f.fy,f.fz);}
function report(){const s=loop.state;return {build:'LIBERTY-RUNNER-POLISH-R6',game:params.game,funOnly,screen,map:selected,preset:runtime.preset,...runtime.metrics,textureMB:Math.round((assets.textureMB+world.textureMB)*100)/100,assets:assets.states,activeChunks:world.activeChunks,pools:world.poolSizes,worldObjects:world.objects(),worldResources:world.ownedResources,ownedResources:resources.items.size,run:{retries,crashed:s.crashed,score:s.score,combo:s.combo,maxCombo:s.maxCombo,feathers:s.feathers,drifts:s.drifts,pickups:s.pickups,loopsCleared:s.loopsCleared.size,splitCount:s.splits.length,distance:s.distance,x:s.x,y:s.y,speed:s.speed,age:s.age,coins:s.coins,jumps:s.jumps,slide:s.slide,boost:s.boost,charge:s.charge,route:s.route,hits:s.hits,falls:s.falls,recoveries:s.recoveries,grounded:s.grounded,shield:s.shield,ended:s.ended,success:s.success},currency:save.state.games[params.game].currency,upgrades:{...save.state.games[params.game].upgrades},bests:structuredClone(bests()),tour:structuredClone(tour()),dailyMode,saveError:save.error,errors:window.__PCOCK_ERRORS||[]};}
window.PCOCK={ready:false,report,get save(){return structuredClone(save.state);},get settings(){return {...save.state.settings,...graphics()};},setPreset(v){if(['Auto','Low','Medium','High','Ultra'].includes(v)){settings.preset=v;runtime.applySettings();world.update(loop,time);save.write();}}};
runtime.setRunning(()=>screen==='run'&&!preview);runtime.setQualityHandler(profile=>{world?.setQuality(profile,settings);root.dataset.graphicsPreset=runtime.preset;updateQualityStatus();});
selectCourse(selected);refresh();if(query.has('debug')){$('.lr-debug').hidden=false;const copy=button('Copy report',()=>navigator.clipboard.writeText(JSON.stringify(report())).then(()=>toast('Report copied')).catch(()=>toast('Select the visible report to copy it.')));copy.classList.add('lr-copy');root.append(copy);}
if(query.get('shot')&&query.get('shot')!=='menu'){makeRun(selected);setScreen('run');const s=loop.state;s.distance=query.get('shot')==='loop'?985:query.get('shot')==='fork'?470:selected==='coast'?70:130;s.previous=s.distance;s.route=query.get('shot')==='fork'?1:0;s.speed=loop.track.config.speed;s.age=s.distance/s.speed;preview=true;input.enable(false);if(query.get('hud')==='0'){hud.hidden=true;$('.lr-header').hidden=true;}}
await renderer.compileAsync(scene,camera);runtime.start(fixed,interpolate);window.PCOCK.ready=true;
resources.onDispose(()=>{runnerHudEditor.dispose();world.dispose();input.dispose();audio.dispose();save.dispose();removeEventListener('keydown',key);removeEventListener('blur',blur);removeEventListener('visibilitychange',visibility);});addEventListener('pagehide',()=>resources.dispose(),{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
