import * as THREE from 'three';
import {spring} from './disposal.js';
export function createMovement(actor,input,camera,settings,world,onAction=()=>{}){const p={position:new THREE.Vector3(),previous:new THREE.Vector3(),velocityY:0,vx:0,vz:0,onGround:true,coyote:.12,glide:2.4,dash:0,cooldown:0,yaw:Math.PI,speed:0,jumps:0,distance:0,gliding:false},draw=new THREE.Vector3(),target=new THREE.Vector3(),goal=new THREE.Vector3(),temp=new THREE.Vector3(),viewForward=new THREE.Vector3(),springs=[{value:0,velocity:0},{value:8,velocity:0},{value:18,velocity:0}];let yaw=0,pitch=.36,glideMax=2.4,activeGlideMax=glideMax,flightSupport=null,runSpeed=6,sprintMode=false,sprintSpeed=11,sprintHeld=false,enabled=true;
 function place(x,z,y=world.heightAt(x,z)){p.position.set(x,y,z);p.previous.copy(p.position);p.velocityY=p.vx=p.vz=p.speed=0;p.onGround=y<=(world.groundAt?.(x,z,y)??world.heightAt(x,z))+.05;p.coyote=p.onGround?.12:0;p.gliding=false;actor.root.position.copy(p.position);target.copy(p.position);target.y+=1.4;goal.set(target.x+Math.sin(yaw)*10*Math.cos(pitch),target.y+Math.sin(pitch)*10+2,target.z+Math.cos(yaw)*10*Math.cos(pitch));for(let i=0;i<3;i++){springs[i].value=goal.getComponent(i);springs[i].velocity=0;}camera.position.copy(goal);camera.lookAt(target);}
 function step(dt,active=true){p.speed=0;p.previous.copy(p.position);if(!active||!enabled){p.vx=p.vz=0;return;}const wasGrounded=p.onGround,c=input.sample(dt),flight=flightSupport?.();yaw-=c.lookX*.004;pitch=THREE.MathUtils.clamp(pitch+c.lookY*.003,.12,.82);input.state.lookX=input.state.lookY=0;p.dash=Math.max(0,p.dash-dt);p.cooldown=Math.max(0,p.cooldown-dt);if(sprintMode){p.dash=c.dash?.24:0;p.cooldown=0;if(c.dash&&!sprintHeld)onAction('dash');sprintHeld=c.dash;}else if(c.dash&&p.cooldown===0){p.dash=.24;p.cooldown=.95;onAction('dash');}viewForward.set(0,0,-1).applyQuaternion(camera.quaternion);viewForward.y=0;viewForward.normalize();const speed=p.dash?(sprintMode?sprintSpeed:15):Math.max(runSpeed,flight?.speed||0),tx=(-c.x*viewForward.z-c.z*viewForward.x)*speed,tz=(c.x*viewForward.x-c.z*viewForward.z)*speed,rate=1-Math.exp(-32*dt);p.vx+=(tx-p.vx)*rate;p.vz+=(tz-p.vz)*rate;
 const nextX=THREE.MathUtils.clamp(p.position.x+p.vx*dt,-(world.bounds||248),world.bounds||248),nextZ=THREE.MathUtils.clamp(p.position.z+p.vz*dt,-(world.bounds||248),world.bounds||248);if(!world.blocked?.(nextX,p.position.z,p.position.y))p.position.x=nextX;if(!world.blocked?.(p.position.x,nextZ,p.position.y))p.position.z=nextZ;p.speed=Math.hypot(p.position.x-p.previous.x,p.position.z-p.previous.z)/dt;p.distance+=p.speed*dt;if(p.speed>.1)p.yaw=Math.atan2(p.position.x-p.previous.x,p.position.z-p.previous.z);
 const ground=world.groundAt?.(p.position.x,p.position.z,p.position.y)??world.heightAt(p.position.x,p.position.z);activeGlideMax=flight?.duration??glideMax;p.coyote=p.onGround?.12:Math.max(0,p.coyote-dt);if(c.jumpBuffer>0&&p.coyote>0){p.velocityY=8.4;p.onGround=false;p.coyote=0;p.glide=activeGlideMax;p.jumps++;input.consumeJump();onAction('jump');}p.gliding=(c.jump||flight?.automatic)&&!p.onGround&&p.velocityY<0&&p.glide>0;if(p.gliding){const sink=flight?Math.max(.75,p.speed*flight.sinkPerMetre):1.7;p.velocityY=Math.max(-sink,p.velocityY-4*dt);p.glide-=dt;}else p.velocityY-=24*dt;p.position.y+=p.velocityY*dt;const followGround=wasGrounded&&p.velocityY<=0&&!p.gliding&&p.position.y-ground<=.35;if(p.position.y<=ground||followGround){if(!p.onGround&&p.velocityY<-5)onAction('land');p.position.y=ground;p.velocityY=0;p.onGround=true;p.glide=activeGlideMax;}else p.onGround=false;if(world.unsafe?.(p.position.x,p.position.z,p.position.y)){place(world.respawn?.x||0,world.respawn?.z||24);onAction('splash');}}
 function render(alpha,dt,active=true){draw.lerpVectors(p.previous,p.position,alpha);actor.root.position.copy(draw);actor.root.rotation.y+=Math.atan2(Math.sin(p.yaw-actor.root.rotation.y),Math.cos(p.yaw-actor.root.rotation.y))*Math.min(1,dt*14);const moving=active&&p.onGround&&p.speed>.08;if(moving){if(actor.walk&&!actor.walk.isRunning())actor.walk.reset().play();actor.walk?.setEffectiveWeight(1);actor.walk?.setEffectiveTimeScale(Math.max(.8,p.speed/5));}else actor.walk?.stop();actor.mixer?.update(dt);if(!moving)for(const rest of actor.rest||[])rest.arm.quaternion.copy(rest.pose);
 actor.tail.animate?.(dt,{speed:active?p.speed:0,gliding:p.gliding,reduceMotion:settings.reduceMotion});target.copy(draw);target.y+=1.4;const range=10;goal.set(target.x+Math.sin(yaw)*range*Math.cos(pitch),target.y+Math.sin(pitch)*range+2,target.z+Math.cos(yaw)*range*Math.cos(pitch));const cameraBlocked=world.cameraBlocked||world.blocked;if(cameraBlocked){for(let i=1;i<=6;i++){temp.lerpVectors(target,goal,i/6);if(cameraBlocked(temp.x,temp.z,temp.y)){goal.lerpVectors(target,goal,Math.max(.28,(i-1)/6));break;}}}for(let i=0;i<3;i++)camera.position.setComponent(i,spring(springs[i],goal.getComponent(i),dt,8));camera.lookAt(target);}
 return {player:p,step,render,place,set enabled(v){enabled=v;input.enable(v);if(!v){p.speed=p.vx=p.vz=0;input.reset();}},get yaw(){return yaw;},set yaw(v){yaw=v;},get pitch(){return pitch;},set pitch(v){pitch=v;},configure(options={}){glideMax=options.glide??glideMax;activeGlideMax=glideMax;runSpeed=options.speed??runSpeed;sprintMode=options.sprint??sprintMode;sprintSpeed=options.sprintSpeed??sprintSpeed;flightSupport=options.flightSupport??flightSupport;},get glideMax(){return activeGlideMax;}};
}
