import * as THREE from 'three';
import {worldPalette as W} from './world-palette.js';
import {createFrameClock} from './frame-clock.js';
export const profiles=Object.freeze({Low:{dpr:1,distance:65},Medium:{dpr:1.5,distance:95},High:{dpr:2,distance:115},Ultra:{dpr:2,distance:130}});
export function createRenderer(container,settings,resources,options={}){
  const renderer=resources.own(new THREE.WebGLRenderer({antialias:options.antialias??false,powerPreference:'high-performance',alpha:false}));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.info.autoReset=false;renderer.setClearColor(W.sky);renderer.domElement.setAttribute('aria-label','Feathers of Liberty foundation world');container.append(renderer.domElement);
  const scene=new THREE.Scene();scene.fog=new THREE.Fog(W.fog,55,115);
  const camera=new THREE.PerspectiveCamera(48,1,.1,240);camera.position.set(16,10,22);camera.lookAt(0,2,-4);
  const sun=new THREE.DirectionalLight(W.warmKey,2.1);sun.position.set(-25,40,20);scene.add(sun);const fill=new THREE.HemisphereLight(W.sky,W.coolFill,1.35);scene.add(fill);
  const deterministic=new URLSearchParams(location.search).has('shot');
  let preset=settings.preset==='Auto'?'Medium':settings.preset,scale=settings.renderScale,contextLost=false,frameMs=16.7,cpuMs=0,frames=0,benchmark=0,adjust=0,raf=0,acc=0,last=0,running=false,post=null;const clock=createFrameClock();
  const metrics={fps:60,frameMs:16.7,cpuMs:0,drawCalls:0,triangles:0,activePreset:preset,renderScale:scale,dpr:1,contextLost:false};
  function resize(){const rect=container.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height);const mobile=matchMedia('(pointer:coarse)').matches,cap=mobile?Math.min(1.5,profiles[preset].dpr):profiles[preset].dpr;metrics.dpr=Math.min(devicePixelRatio||1,cap)*scale;renderer.setPixelRatio(metrics.dpr);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(post)post.target.setSize(renderer.domElement.width,renderer.domElement.height);metrics.renderScale=scale;}
  function createPost(){const target=resources.own(new THREE.WebGLRenderTarget(1,1));target.depthTexture=resources.own(new THREE.DepthTexture(1,1));const material=resources.own(new THREE.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{image:{value:target.texture},depth:{value:target.depthTexture},resolution:{value:new THREE.Vector2()},ink:{value:new THREE.Color(W.outline)},edge:{value:1}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}',fragmentShader:`varying vec2 vUv;uniform sampler2D image;uniform sampler2D depth;uniform vec2 resolution;uniform vec3 ink;uniform float edge;void main(){vec2 p=1.0/resolution;vec3 c=texture2D(image,vUv).rgb;float dx=texture2D(depth,vUv+vec2(p.x,0.0)).r-texture2D(depth,vUv-vec2(p.x,0.0)).r;float dy=texture2D(depth,vUv+vec2(0.0,p.y)).r-texture2D(depth,vUv-vec2(0.0,p.y)).r;float e=smoothstep(.0004,.002,length(vec2(dx,dy)));c=mix(c,ink,e*.7*edge);c*=1.0-dot(vUv-.5,vUv-.5)*.25;gl_FragColor=vec4(c,1.0);\n#include <colorspace_fragment>}` }));const quadScene=new THREE.Scene();quadScene.add(new THREE.Mesh(resources.own(new THREE.PlaneGeometry(2,2)),material));post={target,material,scene:quadScene,camera:new THREE.OrthographicCamera(-1,1,1,-1,0,1)};resize();}
  function render(){renderer.info.reset();if(['High','Ultra'].includes(preset)&&settings.outlines!=='off'){if(!post)createPost();post.material.uniforms.edge.value=settings.outlines==='post'?1:.5;post.material.uniforms.resolution.value.set(renderer.domElement.width,renderer.domElement.height);renderer.setRenderTarget(post.target);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(post.scene,post.camera);}else{renderer.setRenderTarget(null);renderer.render(scene,camera);}metrics.drawCalls=renderer.info.render.calls;metrics.triangles=renderer.info.render.triangles;}
  function applySettings(){preset=settings.preset==='Auto'?preset:settings.preset;if(!profiles[preset])preset='Medium';metrics.activePreset=preset;scale=settings.renderScale;scene.fog.far=Math.min(profiles[preset].distance,settings.viewDistance)+20;resize();}
  const observer=new ResizeObserver(resize);observer.observe(container);visualViewport?.addEventListener('resize',resize);
  const lost=e=>{e.preventDefault();contextLost=true;metrics.contextLost=true;},restored=()=>{contextLost=false;metrics.contextLost=false;last=0;resize();};renderer.domElement.addEventListener('webglcontextlost',lost);renderer.domElement.addEventListener('webglcontextrestored',restored);
  function start(fixed,interpolate){if(running)return;running=true;function tick(now){raf=requestAnimationFrame(tick);if(document.hidden||contextLost){last=0;acc=0;clock.reset();return;}let raw;if(options.smoothTiming){raw=clock.advance(now,settings.fpsCap);if(raw===null)return;}else{if(!last)last=now;raw=now-last;const cap=settings.fpsCap?1000/settings.fpsCap:0;if(raw<cap-.5)return;last=now;}const dt=Math.min(raw/1000,options.smoothTiming?.25:.1),begin=performance.now();acc+=dt;let steps=0;while(acc>=1/60&&steps++<(options.smoothTiming?15:6)){fixed(1/60);acc-=1/60;}interpolate(Math.min(1,acc*60),dt);render();cpuMs+=(performance.now()-begin-cpuMs)*.06;frameMs+=(raw-frameMs)*.08;Object.assign(metrics,{fps:Math.round(1000/Math.max(1,frameMs)),frameMs:Math.round(frameMs*100)/100,cpuMs:Math.round(cpuMs*100)/100});frames++;benchmark+=dt;adjust+=dt;if(settings.preset==='Auto'&&benchmark>=3&&benchmark<3.2){preset=frameMs>28?'Low':'Medium';metrics.activePreset=preset;resize();}if(adjust>2&&!deterministic&&(!options.smoothTiming||settings.preset==='Auto')){adjust=0;const next=Math.max(.6,Math.min(settings.renderScale,scale+(frameMs>24?-.08:frameMs<18?.025:0)));if(Math.abs(next-scale)>.015){scale=next;resize();}}}raf=requestAnimationFrame(tick);}
  resources.onDispose(()=>{running=false;cancelAnimationFrame(raf);observer.disconnect();visualViewport?.removeEventListener('resize',resize);renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.domElement.removeEventListener('webglcontextrestored',restored);renderer.domElement.remove();});resize();
  return {renderer,scene,camera,metrics,sun,applySettings,resize,start,render,get preset(){return preset;}};
}
