import {createRunnerTrack} from './runner-data.js';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export function createRunnerLoop(seed,upgrades={},emit=()=>{}){
 const track=createRunnerTrack(seed),s={seed,distance:(upgrades['head-start']||0)*100,previous:0,previousLane:0,previousY:0,age:0,speed:12,lane:0,targetLane:0,y:0,vy:0,grounded:true,coyote:.12,jumpBuffer:0,glide:2+(upgrades.signature||0)*.5,slide:0,dash:0,charge:40,hits:0,grace:0,slow:0,coins:0,score:0,jumps:0,pickups:0,nearMisses:0,intents:0,bosses:0,ended:false,revived:false,recovered:false,turnChoice:0,turnRoll:0,segment:-1,wave:0,waveBudget:6,waveSpent:0,release:false,boss:false,bossLane:0,bossWarn:false,bossLaser:false,bossPhase:-1,bossHit:-1,powers:{gasless:0,shield:0,rocket:0,storm:0,double:0},events:{},hazards:{},bossWins:{},magnet:0,tutorial:'Follow the coin trail. A/D changes lanes.'};
 const glideMax=()=>2+(upgrades.signature||0)*.5;
 function effect(type,text){emit(type,text);}
 function hit(reason){if(s.grace>0||s.powers.gasless>0||s.powers.rocket>0||s.dash>0)return false;if((upgrades['second-wind']||0)>0&&!s.recovered&&s.hits===1){s.recovered=true;s.grace=3;effect('power','SECOND WIND');return false;}s.hits++;s.grace=2.5;s.slow=.6;s.y=Math.max(0,s.y);effect('hit',reason);if(s.hits>=2){s.ended=true;effect('end','The horde caught up. One more flight?');}return true;}
 function power(kind){if(kind==='gasless')s.magnet=5+(upgrades.magnet||0)*2;s.powers[kind]=kind==='gasless'?5+(upgrades.gasless||0)*2:kind==='rocket'?5:kind==='shield'?7:kind==='storm'?6:8;effect('power',kind.toUpperCase());}
 function action(type){if(s.ended)return;const seg=track.get(Math.floor(s.distance/40)),offset=s.distance-seg.start;if(type==='left'||type==='right'){const direction=type==='left'?-1:1;if(seg.turn&&seg.kind!=='fork'&&offset>18){s.turnChoice=direction;effect('turn',direction<0?'TURN LEFT':'TURN RIGHT');}else s.targetLane=clamp(s.targetLane+direction,-1,1);}if(type==='jump')s.jumpBuffer=.14;if(type==='slide'){s.slide=.9;effect('slide','SLIDE');}if(type==='dash'&&s.charge>=35){s.charge-=35;s.dash=.75;effect('dash','DASH BURST');}}
 function near(){s.nearMisses++;s.charge=clamp(s.charge+22,0,100);s.slow=.16;s.score+=50;effect('near','CLOSE CALL +50');}
 function step(dt,held={}){if(s.ended)return;s.previous=s.distance;s.previousLane=s.lane;s.previousY=s.y;s.age+=dt;const d=dt*(s.slow>0?.55:1);for(const key of ['slide','dash','grace','slow','magnet'])s[key]=Math.max(0,s[key]-dt);for(const key of Object.keys(s.powers))s.powers[key]=Math.max(0,s.powers[key]-dt);s.turnRoll*=Math.exp(-dt*5);const wave=Math.floor(s.age/20);if(wave!==s.wave){s.wave=wave;s.waveSpent=0;s.waveBudget=Math.min(12,6+Math.floor(wave/2));}s.release=s.age%20>14;
  s.speed=Math.min(23,12+s.age*.045)+(s.dash>0?10:0)+(s.powers.rocket>0?13:0);s.distance+=s.speed*d;s.lane+=(s.targetLane-s.lane)*(1-Math.exp(-22*dt));s.jumpBuffer=Math.max(0,s.jumpBuffer-dt);s.coyote=s.grounded?.12:Math.max(0,s.coyote-dt);if(s.jumpBuffer>0&&s.coyote>0){s.vy=8.8;s.grounded=false;s.coyote=0;s.jumpBuffer=0;s.glide=glideMax();s.jumps++;effect('jump','JUMP');}const gliding=held.jump&&!s.grounded&&s.vy<0&&s.glide>0;if(gliding){s.vy=Math.max(-1.3,s.vy-3*dt);s.glide-=dt;}else s.vy-=25*dt;s.y+=s.vy*dt;if(s.y<=0){s.y=0;s.vy=0;s.grounded=true;s.glide=glideMax();}if(s.powers.rocket>0){s.y=3.6;s.vy=0;s.grounded=false;}
  const index=Math.floor(s.distance/40),seg=track.get(index),offset=s.distance-seg.start;
  if(index!==s.segment){if(s.segment>=0){const previous=track.get(s.segment);if(previous.turn){if(previous.kind!=='fork'&&s.turnChoice!==previous.turn)hit('Missed the corner: watch the turn banner.');else{s.score+=50;s.turnRoll=previous.turn*.13;}s.targetLane=0;s.lane=0;}}s.turnChoice=0;s.segment=index;s.hazards[index]=index<3||(!s.release&&s.waveSpent+seg.cost<=s.waveBudget);if(s.hazards[index])s.waveSpent+=seg.cost;for(const key of Object.keys(s.events))if(Number(key.split(':')[0])<index-3)delete s.events[key];for(const key of Object.keys(s.hazards))if(Number(key)<index-3)delete s.hazards[key];if(index>0&&track.get(index-1).world!==seg.world)effect('world',String(seg.world));}
  s.rail=false;if(seg.kind==='rail'&&offset>8&&offset<32&&s.powers.rocket===0){if(s.y>1)s.events[index+':railride']=true;if(s.events[index+':railride']){s.rail=true;s.y=1.7;s.vy=0;s.grounded=false;}}
  const once=key=>{key=index+':'+key;if(s.events[key])return false;s.events[key]=true;return true;};
  if(offset>=7&&offset<18&&seg.power&&Math.abs(s.lane)<.55&&once('power'))power(seg.power);
  for(let i=0;i<5;i++){const at=6+i*5;if(offset>=at&&offset<at+3&&(!s.events[index+':coin'+i])){const magnet=s.magnet>0||s.powers.storm>0,coinLane=seg.kind==='fork'?seg.correct:(index+i)%3-1;if(magnet||Math.abs(s.lane-coinLane)<.52){s.events[index+':coin'+i]=true;s.coins++;s.pickups++;s.score+=10*(s.powers.double>0?2:1);effect('coin','+1');}}}
  if(offset>=25&&once('event')){const same=Math.abs(s.lane-seg.lane)<.58,raised=s.y>.6,low=s.slide>0,protectedBot=s.powers.shield>0;
   if(seg.kind==='fork'){track.choose(index,Math.abs(s.lane)>.4?Math.sign(s.lane):seg.correct);if(Math.sign(s.lane)===seg.correct&&Math.abs(s.lane)>.45){s.intents++;s.coins+=8;effect('intent','INTENT MATCH +8 COINS');}else{effect('wrong','Match token AND chain. Try the next fork.');s.slow=.5;}}
   else if(s.hazards[index]){if((seg.kind==='toll'&&same&&!raised)||(seg.kind==='tunnel'&&same&&!low)||(seg.kind==='gap'&&!raised)||(seg.kind==='chicane'&&same&&!protectedBot)||(seg.obstacle==='cannon'&&same&&!protectedBot)||(seg.obstacle==='steam'&&same&&!raised))hit(seg.kind==='gap'?'Hold Jump to glide across gaps.':seg.kind==='tunnel'?'Slide below the beam.':'Stumble! Find the open lane.');else if(seg.obstacle&&(same&&(raised||low)||!same&&Math.abs(s.lane-seg.lane)<1.2))near();}
   if(seg.kind==='rail'){s.charge=clamp(s.charge+12,0,100);effect('power','ZIP RAIL · DASH CHARGED');}}
  if(s.hazards[index]&&seg.kind==='gap'&&offset>23&&offset<31&&!s.events[index+':gapEnd']&&s.y<.25&&s.grace===0){s.events[index+':gapEnd']=true;hit('Keep holding Jump across the long gap.');}
  if(seg.kind==='bridge'&&offset>14&&offset<31){s.lane+=Math.sin(s.age*3)*dt*.09;if(Math.abs(s.lane)>.58&&once('wind'))hit('Windy bridge: take the center lane.');}
  const bossIndex=Math.floor(s.distance/1500),bossOffset=s.distance%1500;s.boss=bossIndex>0&&bossOffset<240;s.bossWarn=false;s.bossLaser=false;
  if(s.boss){const beat=Math.floor(bossOffset/40),phase=bossOffset%40;s.bossPhase=phase;s.bossLane=(bossIndex+beat)%3-1;s.bossWarn=phase>10&&phase<30;s.bossLaser=beat%3===2;if(phase>30&&s.bossHit!==bossIndex*10+beat){s.bossHit=bossIndex*10+beat;if(s.bossLaser?s.y<.5:Math.abs(s.lane-s.bossLane)<.6)hit(s.bossLaser?'Colossus sweep: jump!':'Colossus slam: move away from the warning lane!');}}
  if(bossIndex>0&&bossOffset>=240&&!s.bossWins[bossIndex]){s.bossWins[bossIndex]=true;s.bosses++;s.coins+=60;effect('boss','COLOSSUS CHEST +60');}
  s.score=Math.max(s.score,Math.floor(s.distance))+Math.floor(d*s.speed*(s.powers.double>0?2:1));s.tutorial=s.bossWarn?s.bossLaser?'LASER SWEEP — JUMP':'SLAM — LEAVE THE MARKED LANE':seg.turn&&seg.kind!=='fork'&&offset>15?(seg.turn<0?'LEFT CORNER — A / ←':'RIGHT CORNER — D / →'):seg.kind==='fork'?'INTENT: '+seg.intent+' · '+(seg.correct<0?'LEFT':'RIGHT'):seg.kind==='chicane'&&offset>25-s.speed*.8&&offset<25?'SANDWICH BOT — CHANGE LANE':seg.kind==='gap'?'JUMP, THEN HOLD TO GLIDE':seg.kind==='rail'?'JUMP TO CATCH THE ZIP RAIL':seg.kind==='bridge'?'WINDY BRIDGE — CENTER LANE':seg.kind==='tunnel'?'SLIDE UNDER THE HIGH BEAM':seg.kind==='toll'?'JUMP OR CHANGE LANE':s.release?'BREATHE · Follow the coins':seg.obstacle==='cannon'?'CANNON VOLLEY — PRIVATE SHIELD OR CHANGE LANE':seg.obstacle==='steam'?'STEAM PIPE — JUMP OR CHANGE LANE':'Read the road. Near misses charge Dash.';
 }
 return {state:s,track,step,action,power,hit,revive(){s.ended=false;s.hits=1;s.grace=4;s.revived=true;s.distance+=5;},get glideMax(){return glideMax();}};
}
