import {shellConfig} from './shell-config.js';
import {rng} from './rng.js';
export const runnerWorlds=['Pulse Peaks','Toll Town','Bridge Bay','Shield Citadel','Peg Foundry'];
export const segmentKinds=['straight','chicane','left','right','fork','bridge','tunnel','gap','rail','toll'];
export const powerKinds=['gasless','shield','rocket','storm','double'];
export function runnerConfig(save){const base=shellConfig('gasless-run'),upgrade=(id,title,cost,base,step,unit,max=5)=>({id,title,kind:'upgrade',description:`${title}: +${step} ${unit} per level.`,cost,growth:1.65,base,step,unit,effect:title,max});return {...base,subtitle:'Run free. Choose your route. Outrun the Colossus.',status:'Two hits. Six worlds. One more flight.',resultLabel:'GASLESS ESCAPE',controls:'A/D or swipe changes lane / turns at corners. Space jumps (hold to glide). S slides. Shift dashes.',howNote:'Read the warning banners. Every segment leaves a route through.',playLabel:'START RUN',upgrades:[{...upgrade('signature','Glide stamina',50,2,.5,'seconds'),recommended:true},upgrade('head-start','Head Start',80,0,100,'meters',3),upgrade('magnet','Magnet duration',65,5,2,'seconds'),upgrade('gasless','Gasless duration',70,5,2,'seconds'),upgrade('second-wind','Second Wind',100,0,1,'recovery',1),{id:'launch-ticket',title:'Rocket ticket',kind:'boost',description:'One run starts with a safe 100 m Rocket flight.',cost:20},...base.upgrades.filter(x=>x.kind==='skin')],get missions(){const sets=[[['distance','Find the flow',300],['jumps','Wings awake',3],['pickups','Coin trail',10]],[['distance','Long way home',700],['nearMisses','Close call artist',3],['intents','Intent navigator',1]],[['distance','Across six worlds',1500],['bosses','Colossus chest',1],['pickups','Golden trail',40]]],set=sets[save.state.games['gasless-run'].missions.tier%sets.length];return set.map(([metric,title,target])=>({id:metric,metric,title,target}));},tips:['A/D turns only while the corner banner is active.','Jump, then hold on the way down to glide over long gaps.','Near misses fill Dash; use it to smash a threat.','Choose the destination token AND chain at Intent Forks.'],tutorial:['Change lanes to follow the coin trail.','Jump low barriers; slide below high beams.','Hold Jump to glide. Turn at corners when the banner appears.','Match the intent at forks. Near misses charge your dash.']};}
// Generation is pure and reproducible. One central event per segment prevents stacked unavoidable hazards.
export function createRunnerTrack(seed){const random=rng(seed),segments=[];let x=0,z=0,yaw=0;
 function extend(index){while(segments.length<=index){const i=segments.length,wave=Math.floor(i/7),phase=i%7,budget=2+Math.min(4,Math.floor(wave/2)),intro=['straight','toll','tunnel','right','gap','fork','chicane'],release=phase>=5;let kind=i<intro.length?intro[i]:release?'straight':segmentKinds[Math.floor(random()*segmentKinds.length)];if(i%5===4&&i>8)kind='fork';const length=40,turn=kind==='left'?-1:kind==='right'?1:kind==='fork'?(i%2?-1:1):0,lane=i===1?0:Math.floor(random()*3)-1,world=Math.floor(i*length/500)%5,obstacle=kind==='toll'?'barrier':kind==='tunnel'?'beam':kind==='gap'?'gap':kind==='chicane'?'pincer':kind==='bridge'?'wind':world===3&&kind==='straight'&&!release?'cannon':world===4&&kind==='straight'&&!release?'steam':null;const s={obstacle,id:i,start:i*length,length,x,z,yaw,turn,kind,lane,world,wave,release,budget,cost:obstacle?Math.min(2,budget):turn?1:0,intent:i%2?'USDC on Base':'pDAI on PulseChain',correct:i%2?-1:1,power:i>1&&i%4===2?powerKinds[Math.floor(i/4)%powerKinds.length]:null};segments.push(s);x-=Math.sin(yaw)*length;z-=Math.cos(yaw)*length;yaw+=turn*Math.PI/2;}}
 return {choose(index,direction){extend(index);segments[index].turn=direction;for(let i=index+1;i<segments.length;i++){const p=segments[i-1],s=segments[i];s.x=p.x-Math.sin(p.yaw)*p.length;s.z=p.z-Math.cos(p.yaw)*p.length;s.yaw=p.yaw+p.turn*Math.PI/2;}const last=segments.at(-1);x=last.x-Math.sin(last.yaw)*last.length;z=last.z-Math.cos(last.yaw)*last.length;yaw=last.yaw+last.turn*Math.PI/2;},get(index){extend(index);return segments[index];},get segments(){return segments;},at(distance,lane=0,out={}){const index=Math.max(0,Math.floor(distance/40));extend(index);const s=segments[index],t=distance-s.start;out.x=s.x-Math.sin(s.yaw)*t+Math.cos(s.yaw)*lane*2.1;out.z=s.z-Math.cos(s.yaw)*t-Math.sin(s.yaw)*lane*2.1;out.yaw=s.yaw;return out;}};
}
