import * as THREE from 'three';
import {element,button} from './hud-kit.js';
import {markNext} from './valley-guide.js';
import {worldPalette as W} from './world-palette.js';
export const skillLevel=xp=>Math.min(20,1+Math.floor((Math.sqrt(1+Math.max(0,xp)/7.5)-1)/2));
export const tools={wood:[['Bronze axe',1,0,3.6,1],['Iron axe',2,12,2.4,1],['Steel axe',4,30,1.6,2]],fish:[['Reed rod',1,0,3.4,1],['River rod',2,12,2.4,1],['Master rod',4,30,1.7,2]]};
export const skillQuests=[{id:'bridge-timber',title:'Pulse Guy · Timber for the footbridge',giver:'Pulse Guy',x:0,z:29,logs:3,fish:0},{id:'harbor-supper',title:'Nessa · Supper for the harbor',giver:'Nessa',x:33,z:-20,logs:0,fish:2},{id:'camp-supplies',title:'Liberty · Frontier camp supplies',giver:'Liberty',x:-5,z:-14,logs:6,fish:4}];
export const skillTrees=[{x:-18,z:33},{x:-23,z:30},{x:-27,z:35}];
const lake={x:56,z:97};
export function createValleySkills({state,save,world,mover,panel,close,notify,audio,wallet}){
 const valid=state.skills&&typeof state.skills==='object'&&!Array.isArray(state.skills),data=state.skills=valid?state.skills:{wood:0,fish:0,logs:0,catch:0,axe:0,rod:0,owned:{wood:[0],fish:[0]},completed:[],felled:{}};for(const k of ['wood','fish','logs','catch','axe','rod'])data[k]=Number.isFinite(data[k])?Math.max(0,Math.floor(data[k])):0;data.owned=data.owned&&typeof data.owned==='object'&&!Array.isArray(data.owned)?data.owned:{};for(const k of ['wood','fish'])data.owned[k]=Array.isArray(data.owned[k])?data.owned[k].filter(Number.isFinite):[0];data.completed=Array.isArray(data.completed)?data.completed.filter(v=>typeof v==='string'):[];data.felled=data.felled&&typeof data.felled==='object'&&!Array.isArray(data.felled)?data.felled:{};save.write();let job=null,visual=null;
 const distance=t=>Math.hypot(t.x-mover.player.position.x,t.z-mover.player.position.z),standing=i=>(data.felled[i]||0)<=Date.now();
 function tree(){return skillTrees.map((t,i)=>({...t,index:i})).filter(t=>standing(t.index)).sort((a,b)=>distance(a)-distance(b))[0];}
 function objective(id){const q=skillQuests.find(q=>q.id===id);if(q){if(data.logs<q.logs)return {...(tree()||skillTrees[0]),id,label:'Chop '+(q.logs-data.logs)+' more logs · '+q.giver,kind:'skill-wood'};if(data.catch<q.fish)return {...lake,id,label:'Catch '+(q.fish-data.catch)+' more fish · '+q.giver,kind:'skill-fish'};const n=world.npcs.find(n=>n.name===q.giver);return {x:n?.x??q.x,z:n?.z??q.z,id,label:'Deliver camp supplies to '+q.giver,kind:'skill-deliver'};}return id==='wood-training'?{...(tree()||skillTrees[0]),id,label:'Woodcutting · chop a grove tree',kind:'skill-wood'}:{...lake,id,label:'Fishing · cast from the lake boardwalk',kind:'skill-fish'};}
 function entries(){return [...skillQuests.map(q=>({...objective(q.id),title:q.title,done:data.completed.includes(q.id)})),{...objective('wood-training'),title:'Woodcutting training · level '+skillLevel(data.wood),done:skillLevel(data.wood)>=20},{...objective('fish-training'),title:'Fishing training · level '+skillLevel(data.fish),done:skillLevel(data.fish)>=20}];}
 function show(){const p=panel('Skills & equipment',close);p.append(element('p','','Gather real in-game supplies, level up and unlock faster tools. Guide → Skills & supply quests tracks every tree, fishing spot and delivery. Move away to cancel an action. Trees regrow after 45 seconds.'));
  p.append(element('p','v-dialogue',`Woodcutting ${skillLevel(data.wood)} · ${data.wood} XP | Fishing ${skillLevel(data.fish)} · ${data.fish} XP`),element('p','',`${data.logs} logs · ${data.catch} fish · ${save.state.profile.feathers} Feathers`));let next;
  for(const kind of ['wood','fish']){p.append(element('h3','',kind==='wood'?'Axes · chop faster':'Rods · faster catches'));for(let i=0;i<tools[kind].length;i++){const [name,level,cost,seconds,yieldCount]=tools[kind][i],owned=data.owned[kind].includes(i),equipped=data[kind==='wood'?'axe':'rod']===i,b=button(name+(equipped?' · equipped':owned?' · equip':` · ${cost} Feathers · level ${level}`),()=>{if(!owned){if(skillLevel(data[kind])<level||save.state.profile.feathers<cost)return;save.state.profile.feathers-=cost;data.owned[kind].push(i);}data[kind==='wood'?'axe':'rod']=i;save.write();show();},'pc-button');b.disabled=equipped||!owned&&(skillLevel(data[kind])<level||save.state.profile.feathers<cost);p.append(element('p','v-small',`${seconds}s per action · ${yieldCount} ${kind==='wood'?'logs':'fish'} · requires level ${level}`),b);if(!b.disabled&&!next)next=b;}}
  p.append(element('h3','','Supply quests'));for(const q of skillQuests)p.append(button(q.title+(data.completed.includes(q.id)?' · complete':` · ${q.logs} logs / ${q.fish} fish`),()=>{state.guideCategory='skills';state.guideFocus=q.id;save.write();close();notify('Follow the gold trail · '+objective(q.id).label);},'pc-button'));const back=button('Back to adventure',close,'pc-button pc-primary');p.append(back);markNext(p,next||back,'Choose an unlocked tool or a supply quest; follow the gold trail.');}
 function act(o){if(!o.kind?.startsWith('skill-'))return false;if(distance(o)>4.5){notify('Follow the gold trail to the marked resource.');return true;}if(job)return true;
  if(o.kind==='skill-deliver'){const q=skillQuests.find(q=>q.id===o.id);if(!q||data.completed.includes(q.id))return true;if(data.logs<q.logs||data.catch<q.fish)return true;data.logs-=q.logs;data.catch-=q.fish;data.completed.push(q.id);save.state.profile.feathers+=12;save.state.profile.xp+=30;wallet.reward('skill:'+q.id,40,q.title);save.write();audio.sound('buy');notify(q.title+' COMPLETE · +12 Feathers · +40 practice USDC');return true;}
  const kind=o.kind==='skill-wood'?'wood':'fish',target=kind==='wood'?tree():lake;if(!target||distance(target)>4.5){notify('Trees are regrowing. Try fishing, or return in 45 seconds.');return true;}const tier=data[kind==='wood'?'axe':'rod'],tool=tools[kind][tier]||tools[kind][0];if(kind==='wood'){const p=mover.player.position,dx=p.x-target.x,dz=p.z-target.z,n=Math.hypot(dx,dz)||1;mover.place(target.x+dx/n*.95,target.z+dz/n*.95);}job={kind,target,tier,time:0,duration:tool[3],yield:tool[4]};close();notify(kind==='wood'?'CHOPPING · Three axe swings':'CASTING · Watch the float');return true;
 }
 function nearby(){const t=tree();if(t&&distance(t)<3)return { ...t,id:'wood-training',label:'Chop grove tree',kind:'skill-wood'};if(distance(lake)<3)return {...lake,id:'fish-training',label:'Cast fishing rod',kind:'skill-fish'};return null;}
 function step(dt,active){if(!job)return;if(!active||distance(job.target)>4.5){job=null;return;}job.time+=dt;if(job.time<job.duration)return;const done=job,before=skillLevel(data[done.kind]);job=null;data[done.kind]+=20*done.yield;data[done.kind==='wood'?'logs':'catch']+=done.yield;save.state.profile.feathers+=done.yield;if(done.kind==='wood'){data.felled[done.target.index]=Date.now()+45000;visual?.fall(done.target.index);}save.write();audio.sound('pickup');notify(`+${done.yield} ${done.kind==='wood'?'logs':'fish'} · +${20*done.yield} ${done.kind==='wood'?'Woodcutting':'Fishing'} XP`+(skillLevel(data[done.kind])>before?' · LEVEL UP!':''));}
 function bind(scene,resources,actor){
  const group=new THREE.Group();scene.add(group);const geo=resources.own(new THREE.CylinderGeometry(.18,.25,2.2,6)),leaf=resources.own(new THREE.ConeGeometry(1.05,2.4,7)),wood=resources.own(new THREE.MeshLambertMaterial({color:W.wood})),green=resources.own(new THREE.MeshLambertMaterial({color:W.pine})),metal=resources.own(new THREE.MeshLambertMaterial({color:W.stone}));const trunks=new THREE.InstancedMesh(geo,wood,3),crowns=new THREE.InstancedMesh(leaf,green,3);group.add(trunks,crowns);const dummy=new THREE.Object3D(),falls={};
  const hand=actor.model?.getObjectByName('mixamorigRightHand')||actor.model?.getObjectByName('mixamorig:RightHand')||actor.root,held=new THREE.Group();hand.add(held);held.scale.setScalar(hand===actor.root?1:1/actor.model.scale.x);const arm=actor.rest?.find(r=>/Right/.test(r.arm.name));
  const handle=resources.own(new THREE.CylinderGeometry(.035,.04,.95,6)),head=resources.own(new THREE.BoxGeometry(.35,.2,.09)),pole=resources.own(new THREE.CylinderGeometry(.018,.035,1.9,5));const axe=new THREE.Group(),rod=new THREE.Group();axe.add(new THREE.Mesh(handle,wood));const blade=new THREE.Mesh(head,metal);blade.position.set(.14,.4,0);axe.add(blade);const shaft=new THREE.Mesh(pole,wood);shaft.position.y=.75;rod.add(shaft);axe.rotation.z=Math.PI;rod.rotation.z=Math.PI;held.add(axe,rod);const lineGeo=resources.own(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,1.7,0),new THREE.Vector3(0,1.3,.7)]));rod.add(new THREE.Line(lineGeo,resources.own(new THREE.LineBasicMaterial({color:W.cloud}))));const float=new THREE.Mesh(resources.own(new THREE.SphereGeometry(.12,6,4)),resources.own(new THREE.MeshLambertMaterial({color:W.flowerGold})));float.position.set(68,.3,100);group.add(float);const ring=new THREE.Mesh(resources.own(new THREE.TorusGeometry(.65,.05,4,18)),green);ring.rotation.x=-Math.PI/2;ring.position.set(lake.x,world.heightAt(lake.x,lake.z)+.06,lake.z);group.add(ring);
  visual={fall(i){falls[i]=0;},render(dt,active){group.visible=active;held.visible=!!job&&active;axe.visible=job?.kind==='wood';rod.visible=job?.kind==='fish';float.visible=active&&Math.hypot(mover.player.position.x-lake.x,mover.player.position.z-lake.z)<90;for(let i=0;i<3;i++){const t=skillTrees[i],down=!standing(i),f=falls[i];if(f!==undefined)falls[i]+=dt;const tilt=down&&f!==undefined?Math.min(Math.PI/2,falls[i]*2):0,scale=down&&(f===undefined||f>1)?0:1;dummy.position.set(t.x,world.heightAt(t.x,t.z)+(scale?1.1:.12),t.z);dummy.rotation.set(0,0,tilt);dummy.scale.set(1,scale||.1,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=world.heightAt(t.x,t.z)+3;dummy.scale.setScalar(scale);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix);}trunks.instanceMatrix.needsUpdate=crowns.instanceMatrix.needsUpdate=true;if(job){mover.player.yaw=Math.atan2(job.target.x-mover.player.position.x,job.target.z-mover.player.position.z);const swing=Math.sin(job.time/job.duration*Math.PI*6);if(arm){arm.arm.quaternion.copy(arm.pose);arm.arm.rotateX(job.kind==='wood'?-.7+swing*.9:-.8);arm.arm.rotateZ(job.kind==='wood'?-.65+swing*.4:-.3);}held.rotation.set(job.kind==='wood'?swing*.3:0,0,job.kind==='fish'?-.6:0);float.position.y=.3+Math.sin(job.time*6)*.08;}},dispose(){group.removeFromParent();held.removeFromParent();}};resources.onDispose(()=>visual.dispose());
 }
 return {data,entries,objective,show,act,nearby,step,bind,render:(dt,active)=>visual?.render(dt,active),get busy(){return !!job;},get action(){return job?{kind:job.kind,time:job.time,duration:job.duration}:null;}};
}
