import {commonGuests,commonModes,commonConversation} from './valley-reach-common.js';
import {element,button} from './hud-kit.js';
import {createReachModel} from './valley-reach-model.js';
import {reachSites as S,reachRoad,reachQuests,reachRegion} from './valley-reach-data.js';
export function createLanternReach({root,state,save,world,mover,panel,close,notify,audio,scenePlay,say}){
 const model=createReachModel(state,()=>save.write()),d=model.data;world.reach.bind(model);
 const status=element('aside','v-reach-status');status.setAttribute('aria-live','off');status.hidden=true;root.append(status);
 const distance=p=>Math.hypot(mover.player.position.x-p.x,mover.player.position.z-p.z);
 function follow(){state.guideCategory='reach';state.guideFocus='reach';save.write();close();}
 function reward(id){if(model.reward(id)){save.state.profile.feathers+=25;save.state.profile.xp+=80;save.write();notify('ADVENTURE COMPLETE · '+reachQuests.find(q=>q.id===id).title+' · +25 Feathers');}}
 function page(title,lines){const p=panel(title);p.classList.add('v-reach-panel');for(const line of lines)p.append(element('p','v-dialogue',line));return p;}
 function travel(back=false){model.visit();state.guideCategory=back?'story':'reach';state.guideFocus=back?'story':'reach';const at=back?S.ferry:S.landing;mover.yaw=back?0:-Math.PI/2;mover.place(at.x,at.z,world.groundAt(at.x,at.z,world.heightAt(at.x,at.z)));world.respawn.x=at.x;world.respawn.z=at.z;state.position={x:at.x,z:at.z};save.write();close();notify(back?'SWAP HARBOR · Your Valley adventure is still here':'LANTERN REACH · Follow the quay to Nessa');}
 function show(){const p=page('Lantern Reach · beyond the eastern road',['A new canal district beyond the old map edge: boathouses, a working lock, an abandoned mill, an aqueduct you can climb and a flooded archive.','Nessa, Ivo and Orin need your help to bring it back. Water, bridges, machinery and the common change as you complete their adventures.']);p.append(element('p','v-eyebrow','EXPLORE · REPAIR · UNCOVER'));
  p.append(element('p','v-dialogue',d.ending?'The three restoration adventures are complete. Visit the common, invite your neighbours or keep exploring.':'Next: '+objective().label));if(mover.player.position.x>598)p.append(button('Continue from here',follow,'pc-button pc-primary'));if(d.ending)p.append(button('Riverside common · gatherings & stories',common,'pc-button'));
  for(const q of reachQuests)p.append(element('p','v-reach-record',(model.done(q.id)?'✓ ':'○ ')+q.title+(model.done(q.id)?' · restored':'')));
  p.append(button(d.visited?'Travel to the Lantern quay':'Take Nessa’s survey ferry',()=>travel(),'pc-button pc-primary'),button('Walk the eastern road',()=>{state.guideCategory='reach';state.guideFocus='reach-road';save.write();close();},'pc-button'),button('Back to the Valley',()=>travel(true),'pc-button'));return p;
 }
 function common(){const p=page('Riverside common',d.ending?['Choose a gathering, then meet the neighbours. Your restored garden or reading terrace stays, and you can change the gathering anytime.']:['Recover the atlas and help Orin restore this place first.']);p.dataset.choiceMenu='true';if(!d.ending){p.append(button('Continue the restoration',follow,'pc-button pc-primary'));return p;}if(distance(S.overlook)>8){p.append(button('Walk to the riverside common',()=>{state.guideCategory='reach';state.guideFocus='overlook';save.write();close();},'pc-button pc-primary'));return p;}for(const m of commonModes){const b=button(m.title+(d.commonMode===m.id?' · selected':''),()=>{const first=!d.homecoming;if(model.setCommon(m.id)){follow();if(first&&m.id!=='quiet')scenePlay('reach-homecoming','LANTERN REACH · Everyone has a place','Nessa brought the neighbours across. Moss brought the seedlings. Orin brought the old stories. You made a place for all of them.',S.overlook,12);notify(m.title+' · '+(m.id==='quiet'?'Take your time.': 'Six neighbours are here. Walk over and talk to them.'));}},'pc-button');b.setAttribute('aria-pressed',String(d.commonMode===m.id));p.append(b,element('p','v-small',m.description));}p.append(element('p','v-small','Conversations heard: '+d.heard.length+' / 6 · '+(d.heard.join(', ')||'Everyone has a story to share.')),button('Keep exploring',close,'pc-button'));return p;}
 function talk(id){if(id==='nessa'){
   if(d.bridge){reward('lock');const p=page('Nessa · A route worth keeping',['There it is. A bridge people can cross tomorrow, not just today. I used to count a delivery as finished when my boat came home. Now I look for who can make the journey without me.','Ivo has found the old mill beyond the crossing. Its pump once kept the archive dry.']);p.append(button('Continue to Ivo',()=>{model.accept('mill');follow();},'pc-button pc-primary'),button('Keep exploring',follow,'pc-button'));return;}
   const p=page('Nessa · A light across the water',[state.feathers.includes('feather-1')?'You helped reopen Swap Harbor. This is where those old boats used to go.':'I brought a survey boat from Swap Harbor. There is more to this valley than the roads we know.','The lock is pressing against the bridge latch. Close the UPPER inlet first, then open the LOWER drain. Watch the water fall. When the gauge reaches the safe band, release the bridge winch.','You can walk between the wheels while the lock drains. If both are open, the river fills it faster than it can empty.']);p.append(button('Help Nessa reopen the crossing',()=>{model.accept('lock');follow();},'pc-button pc-primary'));return;
  }
  if(id==='ivo'){
   if(!d.bridge){const p=page('Ivo · The silent mill',['Nessa needs the lock made safe before we feed water into this mill.']);p.append(button('Follow Nessa’s adventure',follow,'pc-button pc-primary'));return;}
   if(d.powered){reward('mill');const p=page('Ivo · The mill wakes',['Listen to it. That is a useful machine again. The pump has emptied Orin’s archive and the nursery has water.','We did more than replace a broken part. We made sure the water had somewhere to go. Orin is waiting by the old reading hall.']);p.append(button('Continue to Orin',()=>{model.accept('archive');follow();},'pc-button pc-primary'));return;}
   const p=page('Ivo · The silent mill',['The spare gear is still on the aqueduct. Take the long stone ramp from its southern end, bring the gear down and fit it into the gearbox.','Then turn the three elbows to connect the canal to the mill. Water comes from the WEST: it must turn NORTH at A, EAST at B, then SOUTH at C. The blue water shows how far it gets.','The elbows can be turned in any order. Nothing is spent or lost if the route is wrong.']);p.append(button('Restore the mill with Ivo',()=>{model.accept('mill');follow();},'pc-button pc-primary'));return;
  }
  if(!d.powered){const p=page('Orin · Names worth keeping',['The archive is underwater. Ivo’s mill pump is our way in.']);p.append(button('Follow the mill adventure',follow,'pc-button pc-primary'));return;}
  if(d.atlas){reward('archive');const p=page('Orin · A place for the next story',['This atlas carries the names of the people who built the canal. Not prices. Not grand promises. Where they planted, where they read, and where they met.','We can use its plan to reopen the riverside common. Choose a reading terrace or a lantern garden. You can change it here whenever you like.']);p.append(button('Build the reading terrace',()=>ending('reading'),'pc-button pc-primary'),button('Plant the lantern garden',()=>ending('garden'),'pc-button'),button('Visit the riverside common',()=>{state.guideCategory='reach';state.guideFocus='overlook';save.write();close();},'pc-button'));return;}
  const p=page('Orin · Names worth keeping',['The pump has cleared the entrance. The archive’s inner gate listens for its three old chimes.','The mural remembers their order: “First the river carried us. Then the grain sustained us. At last the stars guided us home.” Ring the chimes in that order, find the atlas and bring it back.','A wrong chime only clears the melody. Your other progress stays.']);p.append(button('Recover the Lantern atlas',()=>{model.accept('archive');follow();},'pc-button pc-primary'));return;
 }
 function ending(kind){const first=!d.ending;model.finish(kind);reward('archive');state.guideCategory='reach';state.guideFocus='overlook';save.write();close();if(first)scenePlay('reach-common','LANTERN REACH · A place to return to',kind==='reading'?'The forgotten names have a home again. Leave a seat for the next reader.':'Where the water once stood, a new garden welcomes the next visitor.',S.overlook,12);notify(kind==='reading'?'THE COMMON · Reading terrace restored':'THE COMMON · Lantern garden planted');}
 function point(id,label){return {...S[id],id,kind:'reach',label:label||S[id].label};}
 function objective(){const p=mover.player.position;if(state.guideFocus==='overlook'&&d.ending)return commonObjective();if(p.x<598&&state.guideFocus==='reach-road'){const next=reachRoad.find(q=>q[0]>p.x+20)||reachRoad[3];return {x:next[0],z:next[1],kind:'reach',id:'eastern-road',auto:true,label:'Follow the eastern road to Lantern Reach'};}if(p.x<598)return point('ferry','Lantern Reach · take the ferry at Swap Harbor');if(!model.accepted('lock'))return point('nessa');if(!d.bridge)return d.inlet?point('inlet','Close the upper inlet'):!d.outlet?point('outlet','Open the lower drain'):point('winch',d.water>1.2?'Lock draining · '+Math.round((d.water-.7)/4.8*100)+'% · wait for SAFE':'Water safe · release the bridge');if(!d.rewarded.includes('lock'))return point('nessa','Tell Nessa the crossing is open');if(!model.accepted('mill'))return point('ivo');if(!d.gear){if(p.x<844||p.x>856||p.z>55)return {x:850,z:54,id:'ramp',kind:'reach',auto:true,label:'Aqueduct · enter the long ramp from the south'};return point('gear');}if(!d.installed)return point('mill','Fit the recovered gear into the mill');if(!d.powered)return point('pipe'+model.flow,'Connect elbow '+String.fromCharCode(65+model.flow)+' · follow the blue water');if(!d.rewarded.includes('mill'))return point('ivo','Show Ivo the running mill');if(!model.accepted('archive'))return point('orin');if(!d.vault)return point(['river','grain','stars'][model.echoes],'Archive chimes · river, grain, stars · '+model.echoes+'/3');if(!d.atlas)return point('atlas');if(!d.ending)return point('orin','Bring Orin the Lantern atlas');return commonObjective();}
 function commonObjective(){return {...point('overlook',d.homecoming?'Riverside common · talk, gather or keep exploring':'Visit the common · invite your neighbours'),noTrail:d.homecoming&&distance(S.overlook)<14,hint:'E / tap near a neighbour to talk · Interact at the common to change the gathering'};}
 function nearby(){let nearest=null,best=4;const places=[...Object.entries(S),...(d.ending&&d.commonMode!=='quiet'?commonGuests.map(g=>[g.id,{...g,label:g.name+' · hear their story'}]):[])];for(const [id,p]of places){if(id==='overlook'&&!d.ending||d.ending&&d.commonMode!=='quiet'&&['nessa','ivo','orin'].includes(id))continue;const dist=distance(p);if(dist<best&&Math.abs(mover.player.position.y-(p.y??world.groundAt(p.x,p.z,world.heightAt(p.x,p.z))))<3.4){nearest={...p,id,kind:'reach',label:id==='overlook'?'Riverside common · gatherings':p.label};best=dist;}}return nearest;}
 function act(o=nearby()){if(!o||o.kind!=='reach')return false;const id=o.id;if(id==='overlook'){common();return true;}const guest=commonGuests.find(g=>g.id===id);if(guest&&d.ending&&d.commonMode!=='quiet'){say(guest.name,commonConversation(state,guest.name),()=>{model.remember(guest.name);notify(guest.name+' will remember your visit.');});return true;}if(id==='ferry'){show();return true;}if(id==='landing'){const p=page('Lantern quay',['Nessa’s boat keeps a free route back to Swap Harbor. Your restoration work stays saved.']);p.append(button('Sail back to Swap Harbor',()=>travel(true),'pc-button pc-primary'),button('Continue exploring Lantern Reach',follow,'pc-button'));return true;}if(['nessa','ivo','orin'].includes(id)){talk(id);return true;}
  if(id==='inlet'||id==='outlet'){if(!model.accepted('lock')){talk('nessa');return true;}if(d.bridge){notify('The lock is safe and the bridge is open.');return true;}model.turn(id);audio.sound('buy');notify((id==='inlet'?'UPPER INLET':'LOWER DRAIN')+' · '+(d[id]?'OPEN':'CLOSED'));return true;}
  if(id==='winch'){if(model.openBridge()){audio.sound('buy');notify('CROSSING OPEN · The bridge is here to stay. Tell Nessa.');}else notify(d.bridge?'The restored bridge is open.':d.inlet?'Close the upper inlet before releasing the bridge.':d.water>1.2?'Let the lower drain empty the lock. Watch the gauge.':'Talk to Nessa at the quay first.');return true;}
  if(id==='gear'){if(model.takeGear()){audio.sound('pickup');notify('MILL GEAR RECOVERED · Bring it to the gearbox.');}else notify(d.gear?'You already have the gear.':'Speak to Ivo before borrowing the mill gear.');return true;}
  if(id==='mill'){if(model.install()){audio.sound('buy');notify('GEAR FITTED · Connect the canal elbows to feed the wheel.');}else notify(d.installed?'The gear is fitted. Follow the blue water through all three elbows.':'Recover the gear from the top of the aqueduct ramp.');return true;}
  if(id.startsWith('pipe')){const was=d.powered;if(model.rotate(Number(id.slice(-1)))){audio.sound('pickup');notify(d.powered&&!was?'MILL RESTORED · Wheel turning, nursery watered, archive drained. Tell Ivo.':'ELBOW '+id.slice(-1)+' · Water reaches '+model.flow+' / 3 connections');}else notify(d.powered?'The water route is working.':'Speak to Ivo to begin restoring the mill.');return true;}
  if(id==='mural'){const p=page('The archive mural',['First the RIVER carried us. Then the GRAIN sustained us. At last the STARS guided us home.','Ring the three chimes by the inner gate in that order. A wrong note starts the melody again.']);p.append(button('Return to the chimes',close,'pc-button pc-primary'));return true;}
  if(['river','grain','stars'].includes(id)){const result=model.ring(id);audio.sound(result==='wrong'?'hit':'pickup');notify(result==='open'?'THE ARCHIVE OPENS · Recover the atlas from the reading table.':result==='wrong'?'The echo fades. Start again: river, grain, stars.':result==='locked'?d.vault?'The inner archive is already open.':'Speak to Orin after restoring the mill.':'CHIME '+model.echoes+' / 3 · '+id.toUpperCase());return true;}
  if(id==='atlas'){if(model.takeAtlas()){audio.sound('pickup');notify('LANTERN ATLAS RECOVERED · Bring it back to Orin.');}return true;}return false;
 }
 function step(dt,active){model.step(dt,active&&!document.hidden);const p=mover.player.position;if(active&&p.x>625){model.visit();world.respawn.x=d.bridge&&p.x>753?768:668;world.respawn.z=110;}const show=active&&p.x>680&&p.x<765&&p.z>73&&p.z<132&&!d.bridge;status.hidden=!show;if(show){status.textContent=`LOCK ${d.water<=1.2?'SAFE':Math.round((d.water-.7)/4.8*100)+'%'} · Inlet ${d.inlet?'OPEN':'CLOSED'} · Drain ${d.outlet?'OPEN':'CLOSED'}`;status.classList.toggle('is-safe',d.water<=1.2);}}
 return {model,show,common,act,nearby,objective,step,travel,entries:()=>reachQuests.map(q=>({...reachRegion,...q,kind:'reach',done:model.done(q.id),title:q.title})),dispose(){status.remove();}};
}
