import * as THREE from 'three';
import {brand,applyBrandCss} from './brand.js';
import {Resources} from './disposal.js';
import {createSave} from './save.js';
import {createRenderer} from './renderer.js';
import {createToon} from './toon.js';
import {createSky} from './sky.js';
import {createAssets} from './assets.js';
import {createHud,element,button} from './hud-kit.js';
import {createInput} from './input.js';
import {createAudio} from './audio.js';
import {createParticles} from './particles.js';
import {createDebug} from './debug.js';
import {ensureStyles} from './styles.js';
import {createMovement} from './movement.js';
import {createGuideTrail} from './valley-trail.js';
import {createCastStaging} from './valley-cinema.js';
import {createCinematicCamera} from './valley-camera.js';
import {createValleyWorld} from './valley-world.js';
import {createValleyStory} from './valley-story.js';
import {districts,disclaimer} from './valley-data.js';
import {createAtropaBridge} from './atropa-bridge.js';
import {createHudEditor} from './hud-editor.js';
await ensureStyles(['./fonts.css','./foundation.css','./valley.css']);applyBrandCss();document.body.classList.add('foundation','valley');await document.fonts.ready;
let liveGame=null,restarting=false;
async function boot({resumeRunner=new URLSearchParams(location.search).get('return')==='runner'}={}){
const params=new URLSearchParams(location.search),shot=params.get('shot'),resources=new Resources(),save=createSave(),settings=save.state.settings;if(params.has('preset'))settings.preset=params.get('preset');
const root=document.getElementById('foundation-root');root.replaceChildren();root.className='pc-root';root.inert=true;root.setAttribute('aria-busy','true');root.setAttribute('aria-label','Feathers of Liberty game world');const host=element('div','pc-world'),grade=element('div','pc-grade'),bar=element('header','pc-brandbar');bar.innerHTML='<span class="pc-mark">PCOCK<small>FEATHERS OF LIBERTY</small></span><span class="pc-stage-tag">LIBERTY VALLEY</span>';root.append(host,grade,bar);
const runtime=createRenderer(host,settings,resources,{antialias:true,smoothTiming:true}),{scene,camera,renderer}=runtime;camera.far=700;camera.updateProjectionMatrix();renderer.domElement.setAttribute('aria-label','Liberty Valley game world');const toon=createToon(resources),assets=createAssets(toon,resources,{originalCharacters:true,peacockFan:true,environmentVariant:'valley'});await assets.loadEnvironment();const world=createValleyWorld(scene,toon,resources,assets,{stress:params.has('stress')}),skyRoot=new THREE.Group();scene.add(skyRoot);const sky=createSky(skyRoot,toon,resources),actor=assets.standIn();scene.add(actor.root);
const hud=createHud(root,save,{id:'gasless-run',currency:'Coins'}),input=createInput(renderer.domElement,hud.hud,settings),audio=createAudio(settings),particles=createParticles(scene,resources),hudEditor=createHudEditor(root);let story;
hud.hud.querySelector('[data-dash]').innerHTML='<span>»</span>SPRINT';hud.hud.querySelector('[data-dash]').setAttribute('aria-label','Hold to sprint');hud.hud.querySelector('.pc-desktop-help').textContent='WASD move · drag to look · Space jump / hold to glide · hold Shift to sprint · E interact';
const mover=createMovement(actor,input,camera,settings,world,type=>{story?.onAction(type);audio.sound(type==='dash'?'jump':type==='land'?'pickup':'jump');if(settings.particles>0)particles.emit(mover.player.position.x,mover.player.position.y,mover.player.position.z);});
let landscapeBlocked=false;
const landscapeGuard=element('section','v-landscape-guard');landscapeGuard.innerHTML='<div><strong>ROTATE TO LANDSCAPE</strong><p>Liberty Valley is designed for landscape mobile play.</p></div>';const landscapeBtn=button('ENTER LANDSCAPE',async()=>{try{const doc=window.top&&window.top!==window&&window.top.location.origin===location.origin?window.top.document:document,el=doc.documentElement;if(!doc.fullscreenElement&&el.requestFullscreen)await el.requestFullscreen({navigationUI:'hide'});const orientation=(doc.defaultView||window).screen?.orientation||screen.orientation;await orientation?.lock?.('landscape');}catch(_){}syncLandscapeGuard();},'pc-button pc-primary');landscapeGuard.firstElementChild.append(landscapeBtn,element('small','v-small','If your browser cannot rotate automatically, turn your phone sideways.'));root.append(landscapeGuard);landscapeGuard.hidden=true;
function mobileDevice(){return (navigator.maxTouchPoints||0)>0||matchMedia?.('(pointer:coarse)').matches;}
function syncLandscapeGuard(){landscapeBlocked=!!(mobileDevice()&&innerHeight>innerWidth);landscapeGuard.hidden=!landscapeBlocked;root.classList.toggle('v-landscape-blocked',landscapeBlocked);if(landscapeBlocked){input.enable(false);mover.enabled=false;}}
const landscapeMedia=matchMedia?.('(orientation: landscape)'),landscapeSync=()=>syncLandscapeGuard();addEventListener('resize',landscapeSync);addEventListener('orientationchange',landscapeSync);visualViewport?.addEventListener?.('resize',landscapeSync);landscapeMedia?.addEventListener?.('change',landscapeSync);screen.orientation?.addEventListener?.('change',landscapeSync);
function settingsChanged(){runtime.applySettings();root.classList.toggle('pc-reduce-motion',settings.reduceMotion);root.classList.toggle('pc-color-safe',settings.colorSafe);grade.hidden=settings.postFX==='off';audio.apply();}
function hudResizeOrientation(back,device){
 const p=story.panel('Resize HUD · '+device.toUpperCase(),()=>hudResizeDevice(back));
 p.append(element('p','v-guide-note','Choose which orientation you want to edit. Each device + orientation keeps its own independent layout.'));
 const landscape=button('LANDSCAPE',()=>{story.close();hudEditor.start(device,'landscape',()=>settingsPanel(back));},'pc-button pc-primary');
 const portrait=button('PORTRAIT',()=>{story.close();hudEditor.start(device,'portrait',()=>settingsPanel(back));},'pc-button pc-primary');
 if(device==='mobile'){portrait.disabled=true;portrait.textContent='PORTRAIT · LANDSCAPE REQUIRED';}
 p.append(landscape,portrait,button('Back',()=>hudResizeDevice(back),'pc-button'));
}
function hudResizeDevice(back){
 const p=story.panel('Resize HUD',()=>settingsPanel(back));
 p.append(element('p','v-guide-note','Choose the device layout first. PC and Mobile are stored separately, so changing Mobile will not alter your existing PC HUD.'));
 p.append(button('PC',()=>hudResizeOrientation(back,'pc'),'pc-button pc-primary'),button('MOBILE',()=>hudResizeOrientation(back,'mobile'),'pc-button pc-primary'),button('Back to Settings',()=>settingsPanel(back),'pc-button'));
}
function miniGamesPanel(back){
 const p=story.panel('Mini-Games · Fun Only',()=>settingsPanel(back));
 p.append(element('p','v-guide-note','Play these finished Liberty mini-games whenever you want. FUN MODE does not advance Liberty quests or story and does not save currency, XP, feathers, rewards, medals, best scores or unlocks.'));
 const launch=(path)=>{story.savePosition();location.href=path;};
 p.append(button('LIBERTY RUNNER · FUN MODE',()=>launch('./games/gasless-run.html?fun=1'),'pc-button pc-primary'),button('GHOST ROUTE · FUN MODE',()=>launch('./games/ghost-route.html?fun=1'),'pc-button pc-primary'),button('Back to Settings',()=>settingsPanel(back),'pc-button'));
}
function settingsPanel(back){
 const p=story.panel('Settings',back),fields=[['preset','Graphics',['Auto','Low','Medium','High','Ultra']],['musicVolume','Music',0,.6,.02],['sfxVolume','Sound effects',0,.8,.02],['sensitivity','Look sensitivity',.3,2,.1],['controlOpacity','Control opacity',.25,1,.05],['viewDistance','View distance',45,130,5],['foliage','Foliage',0,1,.25],['fpsCap','Frame cap',['30','60','0']],['leftHanded','Left-handed'],['reduceMotion','Reduce motion'],['colorSafe','Colorblind indicators']];
 for(const [key,label,options,max,step]of fields){const row=element('label','pc-row'),name=element('span','',label),field=element(Array.isArray(options)?'select':'input');if(Array.isArray(options)){for(const value of options){const o=element('option','',value==='0'?'Uncapped':value);o.value=value;field.append(o);}field.value=settings[key];}else{field.type=typeof options==='number'?'range':'checkbox';if(field.type==='range'){field.min=options;field.max=max;field.step=step;field.value=settings[key];}else field.checked=settings[key];}field.setAttribute('aria-label',label);field.addEventListener('change',()=>{settings[key]=field.type==='checkbox'?field.checked:typeof settings[key]==='number'?Number(field.value):field.value;save.write();settingsChanged();});row.append(name,field);p.append(row);}
 p.append(button('Mini-Games · Fun Only',()=>miniGamesPanel(back),'pc-button pc-primary'),button('Resize HUD',()=>hudResizeDevice(back),'pc-button pc-primary'),button('About',()=>{const about=story.panel('About',()=>settingsPanel(back));about.append(element('p','',disclaimer),element('p','','PCOCK · Feathers of Liberty. Local saves stay in this browser. Keyboard: WASD move, drag to look, Space jump/hold glide, Shift sprint, E interact, J journal. Touch controls use independent fingers.'),button('Back to Settings',()=>settingsPanel(back),'pc-button pc-primary'));},'pc-button'),button('Back',back,'pc-button pc-primary'));
}

story=createValleyStory(root,save,world,mover,hud,audio,camera,{onSettings:settingsPanel,onRestart:restartGame,onGate:gate=>location.href=gate.url,onPhoto(){runtime.render();const canvas=document.createElement('canvas');canvas.width=renderer.domElement.width;canvas.height=renderer.domElement.height;const ctx=canvas.getContext('2d');ctx.drawImage(renderer.domElement,0,0);ctx.fillStyle=brand.colors.surface;ctx.fillRect(0,canvas.height-55,canvas.width,55);ctx.font='700 18px "BT Beau Sans"';ctx.fillStyle=brand.colors.text;ctx.fillText('PCOCK · LIBERTY VALLEY · FAN-MADE',18,canvas.height-20);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download='pcock-liberty-valley.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});}});
hud.onInteract(()=>story?.act());
const atropaBridge=createAtropaBridge(root,()=>story?.state);
world.cinemaCamera=createCinematicCamera(scene,world);
const guides=[];for(const [key,index]of [['pulse',0],['liberty',1]]){const group=new THREE.Group();scene.add(group);const model=await assets.loadGuide(key,group);if(model){world.npcs[index].visibleModel=true;guides.push({group,index});}}
await assets.loadPeacock(actor);story.skills.bind(scene,resources,actor);
const guideTrail=createGuideTrail(scene,resources,world),castStaging=createCastStaging(actor,guides,world);
const plumeMeshes=actor.tail.children.filter(m=>m.isMesh&&!m.userData.hull),plumeBase=plumeMeshes.map(m=>m.material.color.clone()),C=brand.colors,plumeStyles={'signal-gold':[C.gold,C.logoOrange,C.gold],'pixel-plume':[C.pulseCyan,C.pulseBlue,C.pulsePurple],'spring-green':[C.success,C.gold,C.success],'liberty-spectrum':[C.pulseCyan,C.pulseBlue,C.pulsePurple,C.pulseMagenta,C.pulseRed,C.logoOrange,C.gold],torchbearer:[C.accent,C.primary,C.gold]};let wornPlume=null;
function applyPlume(){const selected=save.state.profile.cosmetic;if(selected===wornPlume)return;wornPlume=selected;const palette=plumeStyles[selected];for(let i=0;i<plumeMeshes.length;i++){const m=plumeMeshes[i];if(palette)m.material.color.set(palette[i%palette.length]);else m.material.color.copy(plumeBase[i]);}}

const shadow=new THREE.Mesh(resources.own(new THREE.CircleGeometry(.6,16)),resources.own(new THREE.MeshBasicMaterial({color:brand.colors.bg,transparent:true,opacity:.22,depthWrite:false})));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
const arrow=new THREE.Mesh(resources.own(new THREE.ConeGeometry(.2,.8,5)),toon.material(brand.colors.gold));arrow.rotation.x=Math.PI/2;scene.add(arrow);const arrowHull=toon.hull(arrow);const beam=new THREE.Mesh(resources.own(new THREE.CylinderGeometry(.4,.4,9,8)),resources.own(new THREE.MeshBasicMaterial({color:brand.colors.gold,transparent:true,opacity:.16,depthWrite:false})));scene.add(beam);const labels=element('div','v-world-labels');root.append(labels);const labelNodes=world.labels.map(l=>({...l,node:element('span','v-world-label',l.text)}));for(const l of labelNodes)labels.append(l.node);const projected=new THREE.Vector3(),info={};let time=0,dustAge=0,activeChunks=0;
const shotDistrict=districts.find(d=>d.id===shot);if(shot){root.querySelector('.v-layer').hidden=true;root.querySelector('.v-toolbar').hidden=true;hud.show(params.get('hud')!=='0');if(shotDistrict)mover.place(shotDistrict.x+5,shotDistrict.z+12);else mover.place(0,22);}
function fixed(dt){const playActive=story.active&&!shot&&!hudEditor.editing&&!landscapeBlocked;mover.step(dt,playActive);story.skills.step(dt,playActive);if(playActive){input.enable(true);dustAge+=dt;if(dustAge>.12&&mover.player.speed>1&&mover.player.onGround&&settings.particles>0){particles.emit(mover.player.position.x,mover.player.position.y,mover.player.position.z);dustAge=0;}}else input.enable(false);}
function interpolate(alpha,dt){time+=dt;applyPlume();toon.time.value=shot?2:time;renderer.getDrawingBufferSize(toon.resolution.value);mover.render(alpha,dt,story.active&&!shot&&!landscapeBlocked);if(!landscapeBlocked)story.update(dt);atropaBridge.update();if(shot){const d=shotDistrict||{x:0,z:0};if(shot==='vista'){camera.position.set(30,16,46);camera.lookAt(0,5,-10);}else if(shot==='spawn'){camera.position.set(0,7,36);camera.lookAt(0,2,10);}else{camera.position.set(d.x+18,world.heightAt(d.x,d.z)+10,d.z+32);camera.lookAt(d.x,world.heightAt(d.x,d.z)+3,d.z);}}
 world.cinemaCamera.restore();activeChunks=world.update(shot?0:dt,story.sceneFocus||mover.player.position,settings,camera,story.cinematic?1:2);const day=shot?.25:world.dayFraction,light=.45+.55*Math.max(0,Math.sin(day*6.28));runtime.sun.intensity=1.15+light;grade.style.opacity=String(1-light*.35);const viewFocus=story.sceneFocus||mover.player.position;skyRoot.position.set(viewFocus.x,world.heightAt(viewFocus.x,viewFocus.z),viewFocus.z);sky.sun.lookAt(camera.position);for(const guide of guides){const n=world.npcs[guide.index];guide.group.visible=Math.hypot(n.x-viewFocus.x,n.z-viewFocus.z)<27;guide.group.position.set(n.x,world.heightAt(n.x,n.z),n.z);guide.group.rotation.y=Math.atan2(mover.player.position.x-n.x,mover.player.position.z-n.z);if(story.cinematic&&!settings.reduceMotion)guide.group.position.y+=Math.sin(time*2)*.03;}
 castStaging.update(story.cinematicFrame,settings.reduceMotion);story.skills.render(dt,story.running&&!story.cinematic&&!shot);world.cinemaCamera.apply(story.cinematicFrame,camera,[actor.root,...guides.filter(g=>g.group.visible).map(g=>g.group)]);
 shadow.position.set(mover.player.position.x,world.groundAt(mover.player.position.x,mover.player.position.z,mover.player.position.y)+.04,mover.player.position.z);shadow.visible=settings.shadows!=='off';actor.tail.scale.x=actor.tailBaseScale.x;const o=story.objective();guideTrail.update(dt,mover.player.position,o,story.running&&!story.modal&&!story.cinematic&&!shot,settings.reduceMotion);beam.position.set(o.x,world.heightAt(o.x,o.z)+4.5,o.z);arrow.position.copy(actor.root.position);arrow.position.y+=3;arrow.rotation.z=-Math.atan2(guideTrail.next.x-mover.player.position.x,guideTrail.next.z-mover.player.position.z);beam.visible=story.running&&!story.modal&&!story.cinematic&&params.get('hud')!=='0';arrow.visible=beam.visible&&!guideTrail.pending;arrowHull.position.copy(arrow.position);arrowHull.rotation.copy(arrow.rotation);arrowHull.visible=arrow.visible;
 info.x=mover.player.position.x;info.z=mover.player.position.z;info.yaw=THREE.MathUtils.euclideanModulo(mover.yaw,Math.PI*2);info.glideFraction=mover.player.glide/mover.glideMax;info.dashCooldown=1-mover.player.cooldown/.95;hud.update(dt,info);story.drawGuide(guideTrail.pending);for(const l of labelNodes){projected.set(l.x,l.y,l.z).project(camera);l.node.hidden=params.get('hud')==='0'||projected.z>1||Math.abs(projected.x)>1||Math.abs(projected.y)>1||Math.hypot(l.x-mover.player.position.x,l.z-mover.player.position.z)>120;l.node.style.left=(projected.x*.5+.5)*innerWidth+'px';l.node.style.top=(-projected.y*.5+.5)*innerHeight+'px';}audio.setMood({intensity:story.cinematic?.6:world.weather==='rain'?.25:.08,region:Math.floor(Math.abs(mover.player.position.x)/50)%5});audio.update(dt);particles.update(dt);debug.update(dt);}
function report(){const m=runtime.metrics,s=story.state,p=mover.player;return {build:'PCOCK-VALLEY-BETA-20261002-r14',stage:'RELEASE',fps:m.fps,frameMs:m.frameMs,cpuMs:m.cpuMs,drawCalls:m.drawCalls,triangles:m.triangles,textureMB:Math.round((assets.textureMB+world.textureMB+.36)*100)/100,assets:{...assets.states},env:{...assets.envStates},activeChunks,pools:{dust:{active:particles.pool.active,capacity:particles.pool.capacity},scorePops:{active:hud.pops.active,capacity:hud.pops.capacity}},heapMB:performance.memory?Math.round(performance.memory.usedJSHeapSize/1048576):null,preset:runtime.preset,requestedPreset:settings.preset,renderScale:m.renderScale,dpr:m.dpr,memory:{...renderer.info.memory},stress:params.has('stress'),contextLost:m.contextLost,audioUnlocked:audio.unlocked,saveVersion:save.state.saveVersion,screen:story.cinematic?'cutscene':story.modal?'menu':'world',character:{animation:actor.walk?.isRunning()?'locomotion':'idle',cosmetic:wornPlume,speed:Math.round(p.speed*100)/100},player:{x:p.position.x,y:p.position.y,z:p.position.z,onGround:p.onGround,gliding:p.gliding,jumps:p.jumps,distance:p.distance,glideTime:s.glideTime||0},world:{width:1200,depth:1200,npcs:24,weather:world.weather,dayFraction:world.dayFraction,bridgeBuilt:world.bridgeBuilt,restoredDistricts:Math.min(7,s.feathers.length),cinematicFocus:story.sceneFocus},guidance:{activities:story.journey.summary(),trailMarkers:guideTrail.count,routePoints:guideTrail.route.length,routePending:guideTrail.pending,maxRouteSliceMs:guideTrail.maxSlice,category:story.state.guideCategory},cinema:story.cinematicFrame?{speaker:story.cinematicFrame.speaker,visibility:story.cinematicFrame.visibility,shot:story.cinematicFrame.shot,beat:story.cinematicFrame.index}:null,quest:{objective:story.objective(),scenes:s.scenes,finaleComplete:Boolean(s.finaleComplete),active:s.chapter<0?'prologue':s.chapter<7?'chapter-'+(s.chapter+1):null,step:s.step,completed:s.completed,feathers:s.feathers,featherCount:s.feathers.length,hunt:s.hunt.length,side:Object.values(s.side).filter(q=>q.done).length,fieldGuide:Object.keys(s.fieldGuide),cinematic:story.cinematic},expeditions:{complete:Object.keys(s.expeditions?.completed||{}).length,active:s.expeditions?.active},skills:{...story.skills.data,action:story.skills.action},practiceWallet:{balances:s.practiceWallet?.balances,receipts:s.practiceWallet?.receipts.length,upgrades:s.practiceWallet?.upgrades},profile:{feathers:save.state.profile.feathers,xp:save.state.profile.xp},errors:(window.__PCOCK_ERRORS||[]).slice(-5),saveError:save.error};}
const debug=createDebug(root,report,params.has('debug')&&params.get('hud')!=='0');window.PCOCK={ready:false,report,get settings(){return save.state.settings;},get save(){return structuredClone(save.state);},setPreset(value){if(['Auto','Low','Medium','High','Ultra'].includes(value)){settings.preset=value;save.write();settingsChanged();}}};settingsChanged();if(resumeRunner)story.start();if(params.get('hud')==='0'){bar.hidden=true;hud.show(false);labels.hidden=true;}world.update(0,mover.player.position,settings,camera);await renderer.compileAsync(scene,camera);runtime.start(fixed,interpolate);window.PCOCK.ready=true;root.inert=false;root.removeAttribute('aria-busy');syncLandscapeGuard();
resources.onDispose(()=>{removeEventListener('resize',landscapeSync);removeEventListener('orientationchange',landscapeSync);visualViewport?.removeEventListener?.('resize',landscapeSync);landscapeMedia?.removeEventListener?.('change',landscapeSync);screen.orientation?.removeEventListener?.('change',landscapeSync);landscapeGuard.remove();hudEditor.dispose();atropaBridge.dispose();story.dispose();save.dispose();audio.dispose();input.dispose();hud.dispose();debug.dispose();});liveGame={resources,story,hud};
async function restartGame(){if(restarting)return;restarting=true;window.PCOCK.ready=false;liveGame=null;resources.dispose();root.replaceChildren();try{await boot({resumeRunner:false});}catch(error){const notice=element('section','pc-file-message','The new game could not load. Your saved game and restart backup are retained. Reload to try again.');root.replaceChildren(notice);root.inert=false;root.removeAttribute('aria-busy');(window.__PCOCK_ERRORS||=[]).push(error.message);}finally{restarting=false;}}
}
addEventListener('pagehide',()=>{liveGame?.story.savePosition();liveGame?.resources.dispose();liveGame=null;},{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});addEventListener('visibilitychange',()=>{if(document.hidden&&liveGame?.story.active)liveGame.hud.hud.querySelector('[data-pause]').click();});
await boot();
