import * as THREE from 'three';
const ray=new THREE.Raycaster(),direction=new THREE.Vector3();
export function createCinematicCamera(scene,world){
 const hidden=new Map();let visibleShot='';
 const obstacles=focus=>world.cinematicMeshes(focus).filter(o=>o?.isMesh);
 function stage(focus){const meshes=world.landmarkMeshes(),box=new THREE.Box3();for(let ring=0;ring<=5;ring++)for(let i=0;i<(ring?16:1);i++){const a=i*Math.PI/8,p={x:focus.x+Math.sin(a)*ring*4,z:focus.z+Math.cos(a)*ring*4},h=world.heightAt(p.x,p.z);let clear=true;for(const [dx,dz]of [[0,0],[-3.4,0],[1.5,0],[-1.4,.4]])if(world.blocked(p.x+dx,p.z+dz,h)||world.unsafe(p.x+dx,p.z+dz,h))clear=false;if(!clear)continue;for(const mesh of meshes){box.setFromObject(mesh);if(p.x>box.min.x-4&&p.x<box.max.x+4&&p.z>box.min.z-3&&p.z<box.max.z+3){clear=false;break;}}if(clear)return p;}return {...focus};}
 function blocked(eye,target,meshes){direction.subVectors(target,eye);const distance=direction.length();ray.set(eye,direction.normalize());ray.far=Math.max(0,distance-.18);return ray.intersectObjects(meshes,false).length>0;}
 function solve(eye,look,cut,index,camera){if(cut.cameraBeat!==index||cut.cameraAspect!==camera.aspect){const meshes=obstacles(cut.anchor);scene.updateMatrixWorld(true);const targets=[look.clone(),look.clone().add(new THREE.Vector3(-1.4,-.1,.4)),look.clone().add(new THREE.Vector3(1.45,.2,0))];if(cut.id.includes('chapter-2')||cut.id==='finale'||cut.id==='peg-engine')targets.push(look.clone().add(new THREE.Vector3(-3.4,.5,-.3)));let best=null,score=Infinity;const preferred=eye.clone(),offset=preferred.clone().sub(look),base=Math.atan2(offset.x,offset.z),fit=(cut.id.includes('chapter-2')||cut.id==='finale'||cut.id==='peg-engine'?7.2:5.3)/(2*Math.tan(24*Math.PI/180)*camera.aspect);
   for(const radius of [Math.max(8,fit,Math.hypot(offset.x,offset.z)),Math.max(8,fit),Math.max(6,fit)])for(const up of [3.8,6,9])for(let i=0;i<24;i++){const angle=base+(i%2?-1:1)*Math.ceil(i/2)*Math.PI/12,candidate=new THREE.Vector3(look.x+Math.sin(angle)*radius,Math.max(look.y+up,world.heightAt(look.x+Math.sin(angle)*radius,look.z+Math.cos(angle)*radius)+2),look.z+Math.cos(angle)*radius);if(score<10000&&candidate.distanceTo(preferred)>=score)continue;let hits=0;for(const t of targets)if(blocked(candidate,t,meshes))hits++;const rank=hits*10000+candidate.distanceTo(preferred);if(rank<score){score=rank;best=candidate;}if(!hits&&i===0)break;}
   cut.cameraAspect=camera.aspect;cut.cameraBeat=index;cut.clearCamera=best;cut.cameraClear=score<10000;cut.cameraTargets=targets;cut.cameraObstructions=Math.floor(score/10000);
  }eye.copy(cut.clearCamera);return {clear:cut.cameraClear,obstructions:cut.cameraObstructions};}
 function restore(){for(const [mesh,visible]of hidden)mesh.visible=visible;}
 // Last-resort foreground culling runs after scenery, sky and the cast are staged.
 // Checking that final scene also catches backs of meshes when a lens is inside one.
 function apply(frame,camera,actors){if(!frame){hidden.clear();visibleShot='';return;}const key=frame.id+':'+frame.index+':'+camera.aspect;if(key!==visibleShot){hidden.clear();visibleShot=key;scene.updateMatrixWorld(true);const meshes=[],targets=[];const cast=o=>{for(let p=o;p;p=p.parent)if(actors.includes(p))return true;return false;};scene.traverseVisible(o=>{if(o.isMesh&&!cast(o)){const materials=Array.isArray(o.material)?o.material:[o.material];if(materials.some(m=>m.depthWrite&&(!m.transparent||m.opacity>.5)))meshes.push(o);}});for(const root of actors)if(root.visible){const at=root.getWorldPosition(new THREE.Vector3());targets.push(at.clone().add(new THREE.Vector3(0,1.65,0)),at.clone().add(new THREE.Vector3(0,1.1,0)));}const sides=new Map();for(const m of meshes)for(const mat of Array.isArray(m.material)?m.material:[m.material])if(!sides.has(mat)){sides.set(mat,mat.side);mat.side=THREE.DoubleSide;}const blocking=new Set();for(const target of targets){direction.subVectors(target,camera.position);ray.set(camera.position,direction.clone().normalize());ray.far=direction.length()-.25;for(const hit of ray.intersectObjects(meshes,false))blocking.add(hit.object.geometry);}for(const [mat,side]of sides)mat.side=side;for(const mesh of meshes)if(blocking.has(mesh.geometry))hidden.set(mesh,mesh.visible);}
  for(const mesh of hidden.keys())mesh.visible=false;frame.visibility={...frame.visibility,clear:true,foregroundHidden:hidden.size};
 }
 return {stage,solve,blocked,restore,apply};
}
