import {element,button} from './hud-kit.js';
import {clubCamp,clubStart,clubCourses,clubSlots,clubFurnishings,clubNote,medalName,medalFor} from './valley-club-data.js';
import {createClubModel} from './valley-club-model.js';
export const clubTime=value=>value===null?'—':value.toFixed(2)+' s';
export function createTrailClub({root,state,save,mover,world,panel,close,notify,audio}){
 const model=createClubModel(state,()=>save.write()),overlay=element('section','v-club-run'),heading=element('strong'),clock=element('span','v-club-clock'),hint=element('span'),pause=button('Pause trail',show,'pc-button');
 overlay.setAttribute('aria-label','Trail Club race');overlay.append(heading,clock,hint,pause);overlay.hidden=true;root.append(overlay);save.write();
 const distance=p=>Math.hypot(mover.player.position.x-p.x,mover.player.position.z-p.z);
 function track(){state.guideCategory='trails';state.guideFocus='trail-club';save.write();close();}
 function start(){if(distance(clubStart)>4.5){track();notify('Follow the trail to the start pennants beside camp.');return;}track();if(model.start())audio.sound('jump');}
 function show(){const p=panel('Trail Club & camp');p.classList.add('v-club-panel');p.dataset.choiceMenu='true';
  p.append(element('p','v-eyebrow','RUN · HOP · MAKE A PLACE OF YOUR OWN'),element('p','v-club-note',clubNote(model.summary)));
  if(model.run){p.append(element('p','',`${model.course.title} paused · ${clubTime(model.run.elapsed)}. Your timer stays paused while this menu is open.`),button('Resume trail',close,'pc-button pc-primary'),button('End run · keep personal bests',()=>{model.cancel();show();},'pc-button'));return p;}
  p.append(element('p','','Pass the numbered gates in order. Jump through gates marked JUMP. Hold Sprint on the straights; every finish earns bronze, with silver and gold for faster times. All courses are always available.'),element('p','v-small','No entry fee or lost rewards. Menus pause the timer; reloading ends an unfinished run. Your best times and camp stay saved.'));
  for(const c of clubCourses){const card=element('article','v-club-card'),best=model.data.best[c.id];card.append(element('strong','',c.title),element('p','',c.description),element('p','v-small',`Best ${clubTime(best)} · ${medalName(medalFor(c,best))} | Silver ${c.silver}s · Gold ${c.gold}s`));const b=button((model.data.selected===c.id?'Selected · ':'Choose ')+c.title,()=>{model.choose(c.id);show();},'pc-button');b.setAttribute('aria-pressed',String(model.data.selected===c.id));card.append(b);p.append(card);}
  p.append(button(distance(clubStart)<4.5?'Start '+model.course.title:'Guide me to the start',start,'pc-button pc-primary'),button('Camp workshop · arrange furnishings',workshop,'pc-button'),button('Back to adventure',close,'pc-button'));return p;
 }
 function workshop(){const p=panel('Camp workshop');p.classList.add('v-club-panel','v-club-workshop');p.dataset.choiceMenu='true';p.append(element('p','v-eyebrow',`${model.unlocked().length} / ${clubFurnishings.length} FURNISHINGS UNLOCKED`),element('p','','Choose a furnishing, then an empty pad. Rotate or pack away an item freely. Nothing is spent, and your layout stays after reload.'));
  if(distance(clubCamp)>15)p.append(button('Walk to my camp',()=>{model.cancel();state.guideCategory='trails';state.guideFocus='club-camp';save.write();close();},'pc-button pc-primary'));
  for(const f of clubFurnishings){const ready=model.unlocked().includes(f.id),where=Object.entries(model.data.placements).find(([,v])=>v.item===f.id),b=button(f.title+(ready?where?' · '+clubSlots.find(s=>s.id===where[0]).title:' · place':' · locked'),()=>placement(f.id),'pc-button');b.disabled=!ready;p.append(b,element('p','v-small',f.rule));}
  for(const slot of clubSlots){const at=model.data.placements[slot.id];if(!at)continue;const line=element('article','v-club-card');line.append(element('strong','',slot.title+' · '+clubFurnishings.find(f=>f.id===at.item).title),button('Rotate at '+slot.title,()=>{if(model.rotate(slot.id)){audio.sound('pickup');workshop();}},'pc-button'),button('Pack away from '+slot.title,()=>{model.remove(slot.id);workshop();},'pc-button'));p.append(line);}
  p.append(button('Back to Trail Club',show,'pc-button'),button('Back to adventure',close,'pc-button'));return p;
 }
 function placement(item){const f=clubFurnishings.find(f=>f.id===item),p=panel('Place '+f.title);p.classList.add('v-club-panel','v-club-workshop');p.dataset.choiceMenu='true';p.append(element('p','','Moving this item frees its previous pad. Pack away an occupied pad first to use it.'));
  for(const slot of clubSlots){const at=model.data.placements[slot.id],b=button(slot.title+(at?' · '+clubFurnishings.find(f=>f.id===at.item).title:' · empty'),()=>{if(model.place(item,slot.id)){audio.sound('buy');notify(f.title+' placed at '+slot.title);workshop();}},'pc-button');b.disabled=!!at&&at.item!==item;p.append(b);}p.append(button('Back to workshop',workshop,'pc-button'));
 }
 function result(){const r=model.last,c=clubCourses.find(c=>c.id===r.course),p=panel(medalName(r.medal)+' · '+c.title);p.classList.add('v-club-panel');p.dataset.choiceMenu='true';p.append(element('p','v-eyebrow',clubTime(r.time)+(r.improved?' · NEW PERSONAL BEST':'')),element('p','',`Saved best: ${clubTime(r.best)}. ${r.medal===3?'A gold route! Try a different course or arrange your camp.':`Silver: ${c.silver}s · Gold: ${c.gold}s. Sprint between turns and time the jump gates.`}`));
  for(const id of r.unlocked)p.append(element('p','v-club-note','Unlocked: '+clubFurnishings.find(f=>f.id===id).title));p.append(button('Race this course again',start,'pc-button pc-primary'),button('Camp workshop · arrange furnishings',workshop,'pc-button'),button('Choose another course',show,'pc-button'),button('Back to adventure',close,'pc-button'));
 }
 function nearby(){if(model.run)return null;if(distance(clubStart)<4)return {...clubStart,id:'club-start',kind:'trails',label:'Trail Club · start a course'};return distance(clubCamp)<5?{...clubCamp,id:'club-camp',kind:'trails',label:'Camp workshop'}:null;}
 function act(o=nearby()){if(!o||o.kind!=='trails')return false;if(o.id==='club-camp')workshop();else if(model.run)notify('Pass the next gate'+(model.course.gates[model.run.gate].jump?' with a jump.':'.'));else show();return true;}
 function objective(){if(model.run){const g=model.course.gates[model.run.gate];return {...g,id:'club-gate',kind:'trails',auto:true,label:`${model.course.title} · gate ${model.run.gate+1}/${model.course.gates.length} · ${g.jump?'JUMP through':'pass through'}`};}return state.guideFocus==='club-camp'?{...clubCamp,id:'club-camp',kind:'trails',label:'Camp workshop · make yourself at home'}:{...clubStart,id:'club-start',kind:'trails',label:'Trail Club · choose a course at the start pennants'};}
 function step(dt,active){if(model.run&&state.guideCategory!=='trails'){model.cancel();notify('Trail ended · your saved personal bests are safe.');}overlay.hidden=!active||!model.run;root.classList.toggle('v-club-running',!overlay.hidden);if(!active||!model.run||document.hidden)return;
  const p=mover.player,event=model.step(dt,p,world.groundAt(p.position.x,p.position.z,p.position.y));if(event){audio.sound('pickup');if(event.finished){overlay.hidden=true;root.classList.remove('v-club-running');result();return;}}
  const r=model.run,g=model.course.gates[r.gate];heading.textContent=model.course.title;clock.textContent=r.countdown>0?'Ready · '+Math.ceil(r.countdown):clubTime(r.elapsed);hint.textContent=`${r.gate+1}/${model.course.gates.length} · ${g.jump?'JUMP gate':'next gate'} · Sprint between turns`;
 }
 return {model,show,workshop,nearby,act,objective,step,get view(){return root.querySelector('.v-club-workshop')&&distance(clubCamp)<20?{...clubCamp,id:'club-workshop',key:'club'}:null;},entries(){return [{...clubStart,id:'trail-club',kind:'trails',title:'Trail Club & camp workshop',label:'Race three trails and make a camp',done:model.summary.finished===3}];},dispose(){overlay.remove();root.classList.remove('v-club-running');}};
}
