import {element,button} from './hud-kit.js';
import {markNext} from './valley-guide.js';
export function createPracticeLedger(state){
 const isNew=!state.practiceWallet;const wallet=state.practiceWallet||={version:1,balances:{USDC:0,pDAI:0},receipts:[],upgrades:[],claimed:[]};
 function transact(id,label,changes){if(wallet.claimed.includes(id))return {ok:true,duplicate:true};if(Object.entries(changes).some(([key,value])=>!Number.isFinite(value)||(wallet.balances[key]||0)+value<0))return {ok:false,error:'Not enough practice tokens. Complete a delivery to earn more.'};for(const [key,value]of Object.entries(changes))wallet.balances[key]=(wallet.balances[key]||0)+value;wallet.claimed.push(id);wallet.receipts.unshift({id,label,changes:{...changes},number:wallet.claimed.length});wallet.receipts=wallet.receipts.slice(0,30);return {ok:true};}
 if(isNew){transact('opening','Nessa issued a practice supply budget',{USDC:300});if(state.chapter>0)transact('harbor-swap','Harbor completed in an earlier edition · carried forward',{});else if(state.chapter===0&&state.step>=2)transact('harbor-swap','Practice supplies carried forward from your earlier save',{pDAI:100});}
 return {wallet,transact,reward(id,amount,label){return transact('reward:'+id,label,{USDC:amount});},swap(amount){if(!Number.isFinite(amount)||amount<10||amount>25000)return {ok:false,error:'Choose an amount from 10 to 25,000.'};return transact('harbor-swap','Harbor supplies · USDC to pDAI · fictional 1:1 exercise',{USDC:-amount,pDAI:amount});},upgrade(id,cost){if(wallet.upgrades.includes(id))return {ok:true,duplicate:true};const result=transact('upgrade:'+id,id==='wings'?'Long-flight harness':'Trail running boots',{USDC:-cost});if(result.ok)wallet.upgrades.push(id);return result;}};
}
export function createPracticeWallet({state,save,panel,mover,notify}){
 const ledger=createPracticeLedger(state),{wallet}=ledger;
 function apply(){mover.configure({sprint:true,sprintSpeed:wallet.upgrades.includes('boots')?13:11,glide:wallet.upgrades.includes('wings')?6:4});}apply();
 function show(){const p=panel('Practice wallet');p.append(element('p','v-wallet-label','FICTIONAL · Local game inventory'),element('p','','Nessa issued 300 practice USDC for supplies. Story feathers and expeditions earn more. Spend them on equipment and see how each decision changes the ledger. No real funds or account are involved.'));const balances=element('div','v-wallet-balances');for(const [name,value]of Object.entries(wallet.balances))balances.append(element('strong','',value+' '+name));p.append(balances);let next;for(const [id,name,cost,detail]of [['wings','Long-flight harness',80,'Glide for six seconds instead of four.'],['boots','Trail running boots',100,'Hold Sprint for a faster sustained run.']]){const owned=wallet.upgrades.includes(id),b=button(owned?name+' · equipped':name+' · '+cost+' practice USDC',()=>{const r=ledger.upgrade(id,cost);if(!r.ok){notify(r.error);return;}apply();save.write();show();},'pc-button');b.disabled=owned||wallet.balances.USDC<cost;p.append(element('p','v-small',detail),b);if(!b.disabled&&!next)next=b;}p.append(element('h3','','Route receipts'));for(const r of wallet.receipts)p.append(element('article','v-guide-entry',String(r.number).padStart(3,'0')+' · '+r.label+' · '+Object.entries(r.changes).map(([k,v])=>(v>0?'+':'')+v+' '+k).join(' / ')));if(!wallet.receipts.length)p.append(element('p','','Your first receipt will appear after the guided Harbor swap.'));if(next)markNext(p,next,'Choose an upgrade, or close the wallet to keep exploring.');}
 return {...ledger,show,apply,reward(id,amount,label){const r=ledger.reward(id,amount,label);save.write();return r;}};
}
