import {element,button} from './hud-kit.js';
import {markNext} from './valley-guide.js';
import {content} from './valley-content.js';
import {brand} from './brand.js';
import {districts,disclaimer} from './valley-data.js';

const spots=[[-8,-26],[22,-34],[29,-12],[62,-34],[-82,-8],[58,81],[26,78],[113,18],[-13,96],[-93,67],[146,-133],[-62,-86],[-166,-126],[159,133],[-148,-184]];
export const secrets=Object.freeze([...content.EGGS.map((e,i)=>({...e,x:spots[i][0],z:spots[i][1],kind:'secret'})),...content.LORE.map((e,i)=>({...e,id:'page-'+e.id,x:spots[i][0]+3,z:spots[i][1]+3,kind:'page',hint:'A folded page near '+districts[i%districts.length].name+'.'}))]);
export function safeSignalURL(value){try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname==='x.com'||u.hostname==='libertyswap.finance'||u.hostname.endsWith('.libertyswap.finance'))?u.href:null;}catch{return null;}}
export function createValleyExtras({root,state,save,mover,panel,close,notify,scenePlay,onTrack,onMission}){
 state.secrets||=[];state.academy||=[];let target=secrets.find(s=>s.id===state.discoveryTarget)||null,time=0,index=0,events=content.EVENTS,source='Bundled story signals',disposed=false;
 const ticker=element('button','v-signal');ticker.type='button';ticker.setAttribute('aria-label','Open Signal Tower');root.append(ticker);ticker.addEventListener('click',signals);
 function paint(){const e=events[index%events.length];ticker.textContent='SIGNAL TOWER · '+(e?.text||'The Valley keeps a light on.');}
 fetch(new URL('../events.json',import.meta.url),{signal:AbortSignal.timeout(3000)}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json();}).then(data=>{if(disposed)return;const rows=Array.isArray(data)?data:data.events;const valid=rows?.filter(e=>e&&typeof e.id==='string'&&typeof e.text==='string'&&e.text.length<=140&&['tweet','swap','burn','news'].includes(e.type)&&(!e.url||safeSignalURL(e.url))).slice(0,50);if(valid?.length){events=valid;source='Local events feed';paint();}}).catch(()=>{});paint();
 function signals(){state.signalsRead=true;save.write();const p=panel('Signal Tower');p.append(element('p','v-small',source+' · Story signals are fictional. External links open only when you choose them.'));for(const e of events.slice(index%events.length,index%events.length+5)){p.append(element('p','',e.text));if(e.url&&safeSignalURL(e.url)){const a=element('a','pc-button','Read source ↗');a.href=safeSignalURL(e.url);a.target='_blank';a.rel='noopener noreferrer';p.append(a);}}p.append(button('Next signals',()=>{index=(index+5)%events.length;signals();},'pc-button'));markNext(p,p.querySelector('.v-panel-head button'),'Return to the adventure after reading the signals.');}
 function academy(){const p=panel('Liberty Academy');p.append(element('p','','Eight short practice lessons. The yellow ring guides each step. Every amount and outcome is fictional.'));let next;for(const l of content.LESSONS){const learned=state.academy.includes(l.id),b=button(l.title+(learned?' · learned':''),()=>lesson(l),'pc-button');p.append(b);if(!next&&!learned)next=b;}if(next)markNext(p,next,'Begin the next unlearned lesson.');}
 function lesson(l){let phase=0,choice=null;const product=content.PRODUCTS.find(p=>p.id===l.product);function draw(){const s=l.stages[phase],p=panel(l.title),status=element('p','v-sim-status');let advance,first;const options=[];p.append(element('small','v-eyebrow','Academy · '+(phase+1)+' / '+l.stages.length),element('h3','',s.title),element('p','',s.text.replace(/Ghost Route|Peg Keeper|Gasless Run/g,'the Valley practice route')));if(s.kind==='choose'){for(const o of s.options){const b=button(o.label,()=>{choice=o.id;status.textContent=o.detail;markNext(p,advance,'Your approach is selected. Continue to the practice.');},'pc-button');p.append(b);options.push(b);first??=b;}}if(s.kind==='practice'){const row=element('label'),amount=element('input');amount.type='number';amount.min='10';amount.max='25000';amount.value='100';amount.setAttribute('aria-label','Academy fictional amount');row.append(element('span','','Practice amount · fictional tokens'),amount);p.append(row);amount.addEventListener('input',()=>markNext(p,Number(amount.value)>=10&&Number(amount.value)<=25000?advance:amount,'Use an invented amount from 10 to 25,000, then continue.'));}if(s.kind==='summary')for(const t of l.summary)p.append(element('p','',t));if(s.kind==='real-world'){for(const t of l.realWorld)p.append(element('p','',t));if(product?.url&&safeSignalURL(product.url)){const a=element('a','pc-button','Open actual product ↗');a.href=product.url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);}p.append(element('p','v-small',disclaimer));}advance=button(s.button,()=>{if(s.kind==='choose'&&!choice){status.textContent='Choose one approach to compare.';markNext(p,first,'Choose this suggested approach, or compare the other one.');return;}const amount=p.querySelector('input');if(amount&&(Number(amount.value)<10||Number(amount.value)>25000)){status.textContent='Use a fictional amount from 10 to 25,000.';markNext(p,amount,'Enter a fictional amount between 10 and 25,000.');return;}if(++phase<l.stages.length)draw();else{if(!state.academy.includes(l.id))state.academy.push(l.id);state.fieldGuide['academy-'+l.product]={title:l.title,lesson:l.summary.join(' '),url:product?.url};save.write();notify('ACADEMY · Lesson saved');academy();}},'pc-button pc-primary');p.append(status,advance);markNext(p,s.kind==='choose'&&!choice?first:advance,s.kind==='choose'?'Choose the highlighted practice approach. Both choices can be explored.':'Read this step, then choose '+s.button+'.');}draw();}
 function collect(s){const fresh=!state.secrets.includes(s.id);if(fresh){state.secrets.push(s.id);save.state.profile.feathers+=3;save.state.profile.xp+=10;if(s.reward?.type==='cosmetic'&&!save.state.profile.unlocks.includes(s.reward.id))save.state.profile.unlocks.push(s.reward.id);save.write();notify('DISCOVERED · '+s.title);}target=null;state.discoveryTarget=null;save.write();const show=()=>{const p=panel(s.title);p.append(element('small','v-eyebrow','Valley story · fictional'),element('p','v-dialogue',s.text));if(s.reward?.type==='lore'){const l=content.LORE.find(l=>l.id===s.reward.id);if(l)p.append(element('p','',l.text));}const next=button('Keep exploring',close,'pc-button pc-primary');p.append(next);markNext(p,next,'Read your discovery, then follow the next guide marker.');};if(fresh&&[1,5,10,15,20,30].includes(state.secrets.length))scenePlay('discovery-'+state.secrets.length,'VALLEY STORIES · '+state.secrets.length+' / 30',s.text,{x:s.x,z:s.z},8,show);else show();}
 function inspect(s){if(s.id==='seven-colors'&&state.feathers.length<7){notify('Finish the seven story feathers first; the Guide will bring you back.');return;}if(s.id==='tower-sequence'&&!state.secrets.includes(s.id)){let n=0;const sequence=['↑','↓','←','→'],p=panel('Tower rhythm'),status=element('p','','0 / 4 notes'),keys=[];p.append(element('p','v-dialogue','Play ↑ ↓ ← → in that order. The yellow ring moves to the next note. There is no timer.'),status);for(const arrow of sequence){const b=button(arrow,()=>{if(arrow===sequence[n]){n++;status.textContent=n+' / 4 notes';if(n===4){collect(s);return;}}else{n=0;status.textContent='Start again with ↑. No progress or tokens lost.';}markNext(p,keys[n],'Press '+sequence[n]+' · note '+(n+1)+' of 4.');},'pc-button');keys.push(b);p.append(b);}p.append(button('Replay the pattern',()=>{status.textContent='↑ then ↓ then ← then →';markNext(p,keys[n],'Press '+sequence[n]+' next.');},'pc-button'));markNext(p,keys[0],'Press ↑ to begin the four-note pattern.');return;}collect(s);}
 function collection(){const p=panel('Secrets & Valley stories');p.append(element('p','',state.secrets.length+' / 30 discoveries. Choose a clue and follow the gold trail.'));let next;for(const s of secrets){const found=state.secrets.includes(s.id),locked=s.id==='seven-colors'&&state.feathers.length<7,b=button(s.title+(found?' · found':locked?' · finish seven story feathers':' · follow clue'),()=>{if(found)collect(s);else onTrack(s);},'pc-button');p.append(b);if(!next&&!found&&!locked)next=b;}if(next)markNext(p,next,'Follow this clue, or choose any discovery from the list.');}
 function wardrobe(){const p=panel('Tail wardrobe');p.append(element('p','','Wear an unlocked plume, or follow its exact unlock route. Your choice stays with your profile.'));let next;for(const c of content.COSMETICS){let unlocked=save.state.profile.unlocks.includes(c.id);const mastery=c.id==='torchbearer'&&state.feathers.length===7&&Object.values(state.side).filter(q=>q.done).length===12;if(!unlocked&&(mastery||c.unlock.type==='points'&&save.state.profile.xp>=c.unlock.value)){save.state.profile.unlocks.push(c.id);unlocked=true;save.write();}const wearing=save.state.profile.cosmetic===c.id,b=button(c.name+(unlocked?(wearing?' · wearing':' · wear'):c.unlock.type==='secret'?' · guide to secret':' · complete story and neighbor missions'),()=>{if(!unlocked){const secret=secrets.find(s=>s.id===c.unlock.id);if(secret)onTrack(secret);else{notify('Torchbearer: finish all seven story feathers and twelve neighbor missions, or earn 10,000 XP.');onMission();}return;}save.state.profile.cosmetic=c.id;save.write();wardrobe();},'pc-button');p.append(b);if(!next&&!wearing)next=b;}if(next)markNext(p,next,'Choose a plume to wear, or let the guide lead you to its unlock.');}
 return{academy,lesson,inspect,collection,wardrobe,signals,follow(s){target=secrets.find(e=>e.id===s.id)||s;if(state.discoveryTarget!==s.id){state.discoveryTarget=s.id;save.write();}},clearTarget(){target=null;if(state.discoveryTarget){state.discoveryTarget=null;save.write();}},objective(){return target?{x:target.x,z:target.z,label:'Discover · '+target.title,kind:'secret'}:null;},act(){const p=mover.player.position,s=secrets.find(s=>Math.hypot(s.x-p.x,s.z-p.z)<2.2&&(!state.secrets.includes(s.id)||target?.id===s.id));if(s){inspect(s);return true;}if(Math.hypot(p.x-22,p.z+34)<4){signals();return true;}return false;},update(dt,visible){time+=dt;ticker.hidden=!visible;if(time>12){time=0;index++;paint();}},dispose(){disposed=true;ticker.remove();}};
}
