import {element,button} from './hud-kit.js';
import {createPoolModel,poolPlaces} from './valley-pool-model.js?v=s1';
export function createPoolQuest({state,save,wallet,mover,panel,close,notify,say,finish}){
 const model=createPoolModel(state,wallet),d=model.data;let view=null;
 const write=()=>save.write(),message=r=>{if(!r.ok)notify(r.error);write();return r.ok;};
 function collect(){const p=panel('Moss · the shared reserve');p.classList.add('v-pool-panel');p.dataset.choiceMenu='true';p.dataset.poolPanel='supplies';
  p.append(element('small','v-eyebrow','CHAPTER 3 · GROWTH'),element('p','','Nessa’s reopened route brought two reserve crates. Moss has been keeping too much water for the nursery while the orchard stays dry.'),element('p','v-guide-note','Deposit the two matched lesson reserves, then walk to the spring wheel. Share 100 water units between the nursery, orchard and tomorrow’s reserve.'),element('p','v-small',d.carriedLesson?'Your earlier Pool lesson is retained. These are earmarked practice supplies; your personal balances and earlier chapters will not be charged.':'Moss provides 100 Pool USDC and 100 Pool pDAI for this fictional exercise. These cannot be spent on your equipment; your personal balances are untouched.'));
  const b=button(d.carriedLesson?'Continue the water trial':'Deposit Moss’s matched reserves',()=>{if(message(model.start())){view=null;close();notify('POOL RECEIPT SAVED · Walk to the spring wheel');}},'pc-button pc-primary');b.dataset.poolStart='true';p.append(b,button('Come back later',()=>{view=null;close();},'pc-button'));}
 function consoleAt(key){if(!d.deposited){collect();return;}const orchard=key==='orchard',p=panel(orchard?'Orchard wheel · make room to grow':'Spring wheel · share the flow',()=>{view=null;write();close();});view={key,...poolPlaces[key]};p.classList.add('v-pool-panel');p.dataset.choiceMenu='true';p.dataset.poolPanel=key;
  p.append(element('small','v-eyebrow','100 WATER UNITS · ONE SHARED RESERVE'),element('p','','Nursery needs 30 or more. Orchard needs 40 or more. Keep 20 or more for tomorrow. Turn each wheel where it stands; the other wheel stays where you left it.'));
  const readouts=element('div','v-pool-readouts');for(const [id,label,target]of [['nursery','NURSERY',30],['orchard','ORCHARD',40],['reserve','RESERVE',20]]){const cell=element('div'),n=element('strong','',0),small=element('small','',label+' · MIN '+target);n.dataset.poolReadout=id;cell.append(n,small);readouts.append(cell);}p.append(readouts);
  const status=element('p','v-pool-status');status.setAttribute('role','status');p.append(status);
  const row=element('label','v-pool-control'),input=element('input');input.type='range';input.min=0;input.max=80;input.step=10;input.value=d[key];input.setAttribute('aria-label',(orchard?'Orchard':'Nursery')+' water valve');row.append(element('span','',orchard?'Orchard water':'Nursery water'),input);p.append(row);
  const adjust=element('div','v-pool-adjust'),change=v=>{if(model.setValve(key,v))refresh();};const less=button('− 10',()=>{change(d[key]-10);write();},'pc-button'),more=button('+ 10',()=>{change(d[key]+10);write();},'pc-button');adjust.append(less,more);p.append(adjust);input.oninput=()=>change(Number(input.value));input.onchange=write;
  const trial=button('Test the water flow',()=>{const r=model.test();write();if(!r.ok){status.textContent=r.error+' Both wheels remain adjustable.';return;}notify('WATER ARRIVED · The orchard has its share');consoleAt(key);},'pc-button pc-primary');trial.dataset.poolTest='true';
  const stake=button('Stake the practice receipt',()=>{if(message(model.stake())){view=null;close();notify('STAKING RECEIPT SAVED · Return to Moss');}},'pc-button pc-primary');stake.dataset.poolStake='true';if(orchard)p.append(trial,stake);
  const leave=button('Return to the world',()=>{view=null;write();close();},'pc-button');p.append(leave);
  const help=button('Show an example balance',()=>{d.assistance=true;write();status.textContent='Example: 40 to the nursery and 40 to the orchard leaves 20 for tomorrow. Walk between the two wheels to set them.';},'pc-button');help.dataset.poolHelp='true';const reset=button('Reset the water valves',()=>{model.reset();write();refresh();},'pc-button');p.append(help,reset,element('p','v-small','Water units illustrate sharing a reserve. Pool LP is a fictional practice receipt, not a real price, yield or transaction. See your Practice wallet for the exact entries.'));
  function refresh(){const m=model.metrics();for(const [id,min]of [['nursery',30],['orchard',40],['reserve',20]]){const e=p.querySelector('[data-pool-readout='+id+']');e.textContent=m[id];e.parentElement.classList.toggle('is-ready',m[id]>=min);}input.value=d[key];input.disabled=less.disabled=more.disabled=!!d.tested;help.hidden=reset.hidden=!!d.tested;trial.hidden=!!d.tested;stake.hidden=!d.tested||d.staked;status.textContent=d.staked?'Receipt staked. Bring the successful trial back to Moss.':d.tested?'The orchard is watered and tomorrow’s reserve is safe. Stake the practice receipt to record the completed exercise.':m.balanced?(orchard?'Balanced. Test the flow to the orchard.':'Balanced settings. Walk to the orchard wheel and test the delivery.'):'Watch the three levels while you turn the wheel. No water or practice funds are lost by experimenting.';}refresh();}
 function act(id=model.objective().id){if(!model.active()||state.step<1)return false;if(id==='pool-report'&&model.ready()){view=null;say('Moss',['Nessa brought the supplies. You showed me how to share them without emptying tomorrow.','The orchard can send fruit to Tavi’s festival now. I’ll set another bowl on the table.'],()=>{if(model.ready())finish();});return true;}if(!d.deposited){collect();return true;}consoleAt(id==='pool-orchard'?'orchard':'nursery');return true;}
 function nearby(){if(!model.active()||!d.deposited||state.step<2)return null;const p=mover.player.position;for(const key of ['nursery','orchard'])if(Math.hypot(p.x-poolPlaces[key].x,p.z-poolPlaces[key].z)<3.3)return 'pool-'+key;return null;}
 return {model,collect,act,nearby,objective:model.objective,get view(){return view;},clearView(){view=null;}};
}
