import * as THREE from 'three';
import {brand} from './brand.js';
import {worldPalette as W} from './world-palette.js';
import {createValleyScenery} from './valley-scenery.js';
import {createValleyMaterials} from './valley-materials.js';
import {authoredValleyTemplates} from './valley-kit.js';
import {createValleyDetails} from './valley-details.js';
import {rng} from './rng.js';
import {createFrontier} from './valley-frontier.js';
import {collisionIndex} from './valley-collision.js';
import {harborCargo,courierCover} from './valley-expedition-data.js';
import {valleyHeight,roadDistance,rawHeight,WORLD_EDGE} from './valley-terrain.js';
export {valleyHeight,roadDistance} from './valley-terrain.js';
import {createSceneKit,mergeParts} from './scene-kit.js';
import {campaignLocations} from './valley-campaign.js?v=s2';
import {secrets} from './valley-extras.js';
import {districts,namedResidents,gates,sideQuests} from './valley-data.js?v=s1';
const protectedPlaces=[{x:-18,z:33},{x:-23,z:30},{x:-27,z:35},...campaignLocations,...secrets,...namedResidents,...sideQuests.map(q=>({x:q.tx,z:q.tz})),{x:-68,z:-15},{x:36,z:-25}];
const B=brand.colors,roads=districts.filter(d=>!['plaza','spire'].includes(d.id));
function grassTuft(){const points=[],normals=[];for(let i=0;i<3;i++){const a=i*Math.PI/3,c=Math.cos(a),s=Math.sin(a);for(const [x,y,z]of [[-.22,0,0],[.22,0,0],[.08,.63,.06],[-.22,0,0],[.08,.63,.06],[-.1,1,.1]]){points.push(x*c-z*s,y,x*s+z*c);normals.push(-s,0,c);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));return g;}
export function createValleyWorld(scene,toon,resources,assets,{stress=false}={}){
 const materials=createValleyMaterials(toon,resources,districts),kit=createSceneKit(scene,toon,resources,assets,materials.props,authoredValleyTemplates),random=rng(726091),chunks=[],colliders=[],surfaces=[],landmarks=[],collectibles=[],shrines=[],boats=[],labels=[],dummy=new THREE.Object3D(),matrix=new THREE.Matrix4(),tempColor=new THREE.Color(),meshMat=kit.material,box=resources.own(new THREE.BoxGeometry(1,1,1)),leaf=resources.own(grassTuft());let progress=0,bridgeBuilt=false,activeChunks=0,weather='clear',time=0;
 const terrainMat=materials.terrain,terrainEdge=toon.outline(W.outline),baseGeo=resources.own(new THREE.PlaneGeometry(1200,1200,24,24));baseGeo.rotateX(-Math.PI/2);for(let i=0;i<baseGeo.attributes.position.count;i++)baseGeo.attributes.position.setY(i,-15);baseGeo.computeVertexNormals();scene.add(new THREE.Mesh(baseGeo,terrainMat));const baseColors=new Float32Array(baseGeo.attributes.position.count*3);for(let i=0;i<baseColors.length;i+=3)new THREE.Color(W.grass).toArray(baseColors,i);baseGeo.setAttribute('color',new THREE.BufferAttribute(baseColors,3));
 function placed(key,x,z,scale=1,yaw=0,y=valleyHeight(x,z)){return kit.mesh(key,x,y,z,scale,yaw);}
 function part(key,x,y,z,sx=1,sy=sx,sz=sx,yaw=0){dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,yaw,0);dummy.updateMatrix();return {geometry:kit.templates[key],matrix:dummy.matrix.clone(),color:B.text};}
 for(let gx=-250;gx<250;gx+=50)for(let gz=-250;gz<250;gz+=50){
  const geo=resources.own(new THREE.PlaneGeometry(50,50,12,12));geo.rotateX(-Math.PI/2);const p=geo.attributes.position,c=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=gx+25+p.getX(i),z=gz+25+p.getZ(i),y=valleyHeight(x,z);p.setY(i,y);tempColor.set(roadDistance(x,z)<5?W.path:z>170?W.plaza:W.grass);tempColor.toArray(c,i*3);}geo.setAttribute('color',new THREE.BufferAttribute(c,3));geo.computeVertexNormals();const terrain=new THREE.Mesh(geo,terrainMat),hull=new THREE.Mesh(geo,terrainEdge);terrain.position.set(gx+25,0,gz+25);hull.position.copy(terrain.position);terrain.userData.walkableTerrain=true;scene.add(terrain);
  const parts=[],farParts=[],clutter=[];const addPart=(key,...args)=>{const p=part(key,...args);parts.push(p);farParts.push({...p,geometry:kit.templates[key+'-far']||p.geometry});};for(let ix=0;ix<5;ix++)for(let iz=0;iz<5;iz++){
   let x=gx+ix*10+3+random()*4,z=gz+iz*10+3+random()*4;if(roadDistance(x,z)<6){const candidates=[[x+8,z],[x-8,z],[x,z+8],[x,z-8],[x+8,z+8],[x-8,z-8]];candidates.sort((a,b)=>roadDistance(b[0],b[1])-roadDistance(a[0],a[1]));[x,z]=candidates[0];}const town=districts.some(d=>!['summit','spire'].includes(d.id)&&Math.hypot(x-d.x,z-d.z)<22),key=town&&random()>.42?'house':'tree',scale=key==='house'?.9:1.2+random()*.45;const y=key==='house'?Math.max(...[-2.9,0,2.9].flatMap(dx=>[-2.9,0,2.9].map(dz=>valleyHeight(x+dx,z+dz))))+.06:valleyHeight(x,z);
   if(Math.hypot(x-95,z-100)>36&&Math.abs(x-44)>4&&!protectedPlaces.some(p=>Math.hypot(x-p.x,z-p.z)<6)){const yaw=random()*6.28;if(!(Math.abs(x-56)<6&&Math.abs(z-97)<5)&&![...harborCargo,...courierCover].some(p=>Math.hypot(x-p[0],z-p[1])<5)){addPart(key,x,y,z,scale,scale,scale,yaw);if(key==='house'){const foundation=part('house-far',x,y,z,0,0,0);foundation.geometry=box;dummy.position.set(x,y-1.5,z);dummy.scale.set(4.5*scale,3,4.5*scale);dummy.rotation.set(0,yaw,0);dummy.updateMatrix();foundation.matrix=dummy.matrix.clone();foundation.color=W.rockDark;parts.push(foundation);farParts.push(foundation);colliders.push({x,z,w:2*scale,d:2*scale,bottom:y-3,top:y+4.8*scale});surfaces.push({x:x+2.8*scale,z,w:.85,d:2.3,bottom:y,top:y+4.8*scale,ramp:true});}else colliders.push({x,z,w:.3,d:.3,bottom:y,top:y+2});}}
   {const a=x+(random()-.5)*7,b=z+(random()-.5)*7;if(Math.hypot(a-95,b-100)>36&&Math.abs(a-44)>4)addPart('rock',a,valleyHeight(a,b),b,.9);if(town&&Math.hypot(a-95,b-100)>38&&Math.abs(a-44)>5)addPart('crate',a+1.5,valleyHeight(a+1.5,b),b,.7);}
   for(let i=0;i<10;i++){const a=x+(random()-.5)*9,b=z+(random()-.5)*9;if(roadDistance(a,b)<4.9||Math.hypot(a-95,b-100)<37||Math.abs(a-44)<4.5)continue;dummy.position.set(a,valleyHeight(a,b)+.03,b);dummy.scale.set(.7,.45+random()*.45,.7);dummy.rotation.set(0,random()*6.28,.1);dummy.updateMatrix();clutter.push({matrix:dummy.matrix.clone(),color:i===0?W.flowerGold:i%2?W.grassLight:W.leafLight});}
  }
  const propsGeo=resources.own(mergeParts(parts)),props=new THREE.Mesh(propsGeo,meshMat),edges=new THREE.Mesh(propsGeo,kit.outline);const farGeo=resources.own(mergeParts(farParts)),farProps=new THREE.Mesh(farGeo,meshMat),farEdges=new THREE.Mesh(farGeo,kit.outline);scene.add(edges,props,farEdges,farProps);const grass=new THREE.InstancedMesh(leaf,toon.wind(toon.material(B.text)),clutter.length),grassHull=new THREE.InstancedMesh(leaf,toon.wind(toon.outline(W.grassDark)),clutter.length);resources.own(grass);resources.own(grassHull);for(let i=0;i<clutter.length;i++){grass.setMatrixAt(i,clutter[i].matrix);grassHull.setMatrixAt(i,clutter[i].matrix);grass.setColorAt(i,tempColor.set(clutter[i].color));}scene.add(grassHull,grass);chunks.push({x:gx+25,z:gz+25,terrain,items:[props,edges,farProps,farEdges,grass,grassHull],near:[props,edges],far:[farProps,farEdges],grass:[grass,grassHull],distance:0});
 }
 for(const d of districts){const item=placed(d.key,d.x,d.z,d.scale||1,d.id==='harbor'?Math.PI/2:0);landmarks.push({...d,item});labels.push({text:d.name,x:d.x,z:d.z,y:valleyHeight(d.x,d.z)+(d.key==='signal-spire'?10:7)*(d.scale||1)});}
 const arch=placed('liberty-arch',0,13,1.25);landmarks.push({x:0,z:13,item:arch});
 for(const g of gates){const item=placed('liberty-arch',g.x,g.z,.75);landmarks.push({...g,item});labels.push({text:g.name,x:g.x,z:g.z,y:valleyHeight(g.x,g.z)+6});}
 const bridge=placed('wooden-bridge',44,-20,1,Math.PI/2,.35);bridge.show(false);const rope=placed('wooden-bridge',44,-31,.7,Math.PI/2,.35);landmarks.push({x:44,z:-31,item:rope});surfaces.push({x:44,z:-31,w:4.2,d:1.8,top:1.05,bottom:.1});
 const waterGeo=resources.own(new THREE.CircleGeometry(36,32)),water=new THREE.Mesh(waterGeo,materials.water);water.rotation.x=-Math.PI/2;water.position.set(95,.35,100);scene.add(water);toon.hull(water);const river=new THREE.Mesh(resources.own(new THREE.PlaneGeometry(7.5,490)),materials.water);river.rotation.x=-Math.PI/2;river.position.set(44,.3,0);scene.add(river);toon.hull(river);
 for(const [x,z]of [[76,-29],[89,89],[110,110]])boats.push({item:placed('boat',x,z,.8,0,.45),x,z});
 for(const d of districts.filter(d=>!['spire','windmill'].includes(d.id))){const x=d.x+7,z=d.z+9,item=placed('feather-shrine',x,z,.7);shrines.push({id:d.id,name:d.name,x,z,item});}
 for(let i=0;i<100;i++){let x=-230+random()*460,z=-230+random()*460;if(i<6){x=i%2?5:-5;z=24-i*5;}if(Math.abs(x-44)<4)x+=8;if(Math.hypot(x-95,z-100)<38){const dx=x-95,dz=z-100,length=Math.hypot(dx,dz)||1;x=95+dx/length*40;z=100+dz/length*40;}collectibles.push({id:'hunt-'+i,x,z,y:valleyHeight(x,z)+1.3,collected:false});}
 const pickupGeo=resources.own(new THREE.IcosahedronGeometry(.5,0)),pickups=new THREE.InstancedMesh(pickupGeo,toon.material(B.gold),100),pickupHull=new THREE.InstancedMesh(pickupGeo,toon.outline(B.glow),100);resources.own(pickups);resources.own(pickupHull);scene.add(pickupHull,pickups);
 const npcGeo=resources.own(mergeParts([{geometry:resources.own(new THREE.IcosahedronGeometry(.5,0)),matrix:new THREE.Matrix4().makeTranslation(0,1.65,0),color:B.gold},{geometry:box,matrix:new THREE.Matrix4().compose(new THREE.Vector3(0,.85,0),new THREE.Quaternion(),new THREE.Vector3(.65,1.2,.5)),color:B.primary}])),npcMesh=new THREE.InstancedMesh(npcGeo,meshMat,24),npcHull=new THREE.InstancedMesh(npcGeo,kit.outline,24);resources.own(npcMesh);resources.own(npcHull);scene.add(npcHull,npcMesh);
 const npcs=Array.from({length:24},(_,i)=>{const named=namedResidents[i],home=named||districts[i%districts.length];return {id:named?.id||'resident-'+i,name:named?.name||'Valley neighbor',homeX:home.x+(named?0:7),homeZ:home.z+(named?0:9),x:home.x,z:home.z,walking:false,activity:'work',cosmeticReaction:false,visibleModel:false};});
 const wildlife=new THREE.InstancedMesh(pickupGeo,toon.material(W.cloud),20),wildHull=new THREE.InstancedMesh(pickupGeo,toon.outline(W.outline),20);resources.own(wildlife);resources.own(wildHull);scene.add(wildHull,wildlife);
 const pathParts=[];for(const d of roads){const len=Math.hypot(d.x,d.z+20),steps=Math.ceil(len/5);for(let i=0;i<steps;i++){const t=i/steps,x=d.x*t,z=-20+(d.z+20)*t;if(Math.hypot(x-95,z-100)<36)continue;dummy.position.set(x,valleyHeight(x,z)+.09,z);dummy.scale.set(.14,.04,len/steps+1);dummy.rotation.set(0,Math.atan2(d.x,d.z+20),0);dummy.updateMatrix();pathParts.push({geometry:box,matrix:dummy.matrix.clone(),color:i%3?B.primary:B.accent});}}const pathGeo=resources.own(mergeParts(pathParts));scene.add(new THREE.Mesh(pathGeo,meshMat));
 if(stress){const geo=resources.own(new THREE.IcosahedronGeometry(.3,0)),m=new THREE.InstancedMesh(geo,toon.material(B.accent),600),h=new THREE.InstancedMesh(geo,toon.outline(B.glow),600);resources.own(m);resources.own(h);for(let i=0;i<600;i++){const x=(random()-.5)*60,z=(random()-.5)*60;dummy.position.set(x,valleyHeight(x,z)+.4,z);dummy.scale.setScalar(.4);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix);h.setMatrixAt(i,dummy.matrix);}scene.add(h,m);}
 const scenery=createValleyScenery(scene,toon,resources,kit,valleyHeight,colliders,surfaces,materials.water),details=createValleyDetails(scene,toon,resources,kit,valleyHeight,districts);
 const shieldLights=new THREE.InstancedMesh(kit.templates['signal-lamp'],meshMat,5),shieldHulls=new THREE.InstancedMesh(kit.templates['signal-lamp'],kit.outline,5);resources.own(shieldLights);resources.own(shieldHulls);for(let i=0;i<5;i++){dummy.position.set(-60-i*4,valleyHeight(-60-i*4,-10),-10);dummy.scale.setScalar(1);dummy.rotation.set(0,0,0);dummy.updateMatrix();shieldLights.setMatrixAt(i,dummy.matrix);shieldHulls.setMatrixAt(i,dummy.matrix);}scene.add(shieldHulls,shieldLights);
 
 const frontier=createFrontier(scene,toon,resources,kit,materials);
 const nearbyColliders=collisionIndex(colliders),nearbySurfaces=collisionIndex(surfaces);
 function blocked(x,z,y){if(frontier.blocked(x,z,y))return true;for(const c of nearbyColliders(x,z))if(y<c.top-.25&&y+2>c.bottom&&Math.abs(x-c.x)<c.w+.32&&Math.abs(z-c.z)<c.d+.32)return true;return false;}
 function groundAt(x,z,y){let h=Math.max(valleyHeight(x,z),frontier.groundAt(x,z,y));for(const c of nearbyColliders(x,z))if(y>=c.top-.5&&Math.abs(x-c.x)<c.w&&Math.abs(z-c.z)<c.d)h=Math.max(h,c.top);for(const s of nearbySurfaces(x,z))if(Math.abs(x-s.x)<s.w&&Math.abs(z-s.z)<s.d){const top=s.ramp?s.bottom+(1-Math.abs(z-s.z)/s.d)*(s.top-s.bottom):s.top;if(y>=top-.6||s.ramp||s.walkway)h=Math.max(h,top);}if(bridgeBuilt&&Math.abs(x-44)<6&&Math.abs(z+20)<2.5)h=Math.max(h,1.05);return h;}
 function update(dt,focus,settings,camera,detailChunks=2){time+=dt;weather=time%180>145?'rain':'clear';for(const c of chunks)c.distance=Math.hypot(c.x-focus.x,c.z-focus.z);chunks.sort((a,b)=>a.distance-b.distance);activeChunks=settings.preset==='Low'?5:7;for(let i=0;i<chunks.length;i++){const c=chunks[i];c.terrain.visible=c.distance<155;for(const item of c.items)item.visible=i<activeChunks&&c.distance<125;for(const item of c.near)item.visible=i<detailChunks&&c.distance<125;for(const item of c.far)item.visible=i>=detailChunks&&i<activeChunks&&c.distance<125;for(const grass of c.grass)grass.visible=i<activeChunks&&c.distance<125&&settings.foliage>0;}for(const l of landmarks)l.item.show(Math.hypot(l.x-focus.x,l.z-focus.z)<145);bridge.show(bridgeBuilt&&Math.hypot(44-focus.x,-20-focus.z)<115);
  for(let i=0;i<collectibles.length;i++){const f=collectibles[i],near=Math.hypot(f.x-focus.x,f.z-focus.z)<90;dummy.position.set(f.x,f.y+(settings.reduceMotion?0:Math.sin(time*2+i)*.1),f.z);dummy.scale.set(f.collected||!near?0:.25,f.collected||!near?0:1, f.collected||!near?0:.16);dummy.rotation.set(0,time*.8+i,0);dummy.updateMatrix();pickups.setMatrixAt(i,dummy.matrix);pickupHull.setMatrixAt(i,dummy.matrix);}pickups.instanceMatrix.needsUpdate=pickupHull.instanceMatrix.needsUpdate=true;
  const day=(time%600)/600;for(let i=0;i<npcs.length;i++){const n=npcs[i],fixed=i<3,working=day<.55,shelter=weather==='rain';n.walking=!fixed&&!shelter&&day>.2&&day<.85;n.activity=shelter?'shelter':working?'work':i%2?'chat':'sit';n.x=n.homeX+(n.walking?Math.sin(time*.12+i)*3:0);n.z=n.homeZ+(n.walking?Math.cos(time*.12+i)*3:0);if(progress===1&&i>=8){const a=(i-8)*Math.PI/8;n.x=Math.sin(a)*10;n.z=-20+Math.cos(a)*10;n.activity='celebrate';}dummy.position.set(n.x,valleyHeight(n.x,n.z),n.z);dummy.scale.setScalar(n.visibleModel||Math.hypot(n.x-focus.x,n.z-focus.z)>90?0:1);dummy.rotation.set(0,n.walking?time*.12+i:Math.PI,0);dummy.updateMatrix();npcMesh.setMatrixAt(i,dummy.matrix);npcHull.setMatrixAt(i,dummy.matrix);}npcMesh.instanceMatrix.needsUpdate=npcHull.instanceMatrix.needsUpdate=true;
  for(let i=0;i<20;i++){const fish=i>13,x=fish?95+Math.sin(time*.3+i)*22:focus.x+Math.sin(time*.2+i)*35,z=fish?100+Math.cos(time*.3+i)*22:focus.z+Math.cos(time*.15+i)*35;dummy.position.set(x,fish?.37:valleyHeight(x,z)+5+Math.sin(time+i),z);dummy.scale.set(fish?.5:.8,.15,fish?.15:.35);dummy.rotation.set(0,time*.1+i,0);dummy.updateMatrix();wildlife.setMatrixAt(i,dummy.matrix);wildHull.setMatrixAt(i,dummy.matrix);}wildlife.instanceMatrix.needsUpdate=wildHull.instanceMatrix.needsUpdate=true;for(const b of boats){b.item.mesh.position.y=b.item.hull.position.y=.45+Math.sin(time+b.x)*.08;b.item.mesh.rotation.z=b.item.hull.rotation.z=Math.sin(time*.7+b.z)*.035;}
  shieldLights.visible=shieldHulls.visible=progress>=2/7&&Math.hypot(focus.x+68,focus.z+10)<110;scenery.update(time,focus,weather,settings.reduceMotion);details.update(focus,progress,time,settings.reduceMotion);materials.setProgress(progress);frontier.update(dt,focus,settings);return activeChunks;
 }
 return {setExpeditions:(s,q)=>frontier.setState(s,q),adventureHit:frontier.hit,landmarkMeshes:()=>[...landmarks.map(l=>l.item.mesh),...frontier.landmarkMeshes()],cinematicMeshes:(focus)=>{frontier.update(0,focus,{});return [...chunks.flatMap(c=>Math.hypot(c.x-focus.x,c.z-focus.z)<100?[c.terrain,...c.near.filter(m=>m.material!==kit.outline)]:[]),...landmarks.map(l=>l.item.mesh),...frontier.cinematicMeshes()];},bounds:WORLD_EDGE,terrainMeshes:[...chunks.map(c=>c.terrain),...frontier.terrainMeshes],heightAt:valleyHeight,groundAt,blocked,update,collectibles,npcs,shrines,gates,labels,kit,colliders,textureMB:materials.textureMB+details.textureMB,respawn:{x:0,z:24},get activeChunks(){return activeChunks;},get weather(){return weather;},get bridgeBuilt(){return bridgeBuilt;},get dayFraction(){return time%600/600;},setProgress(feathers){progress=Math.min(1,feathers/7);bridgeBuilt=feathers>=1;npcs[1].homeX=feathers>=1?-68:-5;npcs[1].homeZ=feathers>=1?-15:-14;},setCollected(ids){for(const f of collectibles)f.collected=ids.includes(f.id);},unsafe(x,z,y){return z>485&&y<.3||y<.25&&(Math.hypot(x-95,z-100)<35||Math.abs(x-44)<3.7)&&!(Math.abs(z+31)<2)&&!(bridgeBuilt&&Math.abs(z+20)<2.6);}};
}
