import * as THREE from 'three';
import {brand} from './brand.js';

// A small cached navigation grid follows the same ground, bridge and collision
// rules as the player. It never sends a guide straight through the lake or a house.
export function createRoutePlanner(world){
 const step=4,edge=world.bounds||248,n=Math.ceil(edge*2/step)+1,size=n*n,walk=new Int8Array(size),links=new Int8Array(size*9),heights=new Float32Array(size),cost=new Float32Array(size),came=new Int32Array(size),closed=new Uint8Array(size);const navigationKey=()=>[world.bridgeBuilt,world.reach?.navigationKey].join(":");let bridge=navigationKey();
 const index=(x,z)=>THREE.MathUtils.clamp(Math.round((x+edge)/step),0,n-1)+THREE.MathUtils.clamp(Math.round((z+edge)/step),0,n-1)*n;
 const point=i=>({x:(i%n)*step-edge,z:Math.floor(i/n)*step-edge});
 function safe(x,z){const y=world.groundAt(x,z,world.heightAt(x,z));return {x,y,z,ok:!world.blocked(x,z,y)&&!world.unsafe(x,z,y)};}
 function open(i){if(!walk[i]){const p=point(i),s=safe(p.x,p.z);walk[i]=s.ok?1:-1;heights[i]=s.y;}return walk[i]>0;}
 function clear(a,b){const d=Math.hypot(b.x-a.x,b.z-a.z),count=Math.max(1,Math.ceil(d));let previous=safe(a.x,a.z);for(let i=1;i<=count;i++){const t=i/count,p=safe(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t);if(!p.ok||Math.abs(p.y-previous.y)>1.2)return false;previous=p;}return true;}
 function* clearTask(a,b){const d=Math.hypot(b.x-a.x,b.z-a.z),count=Math.max(1,Math.ceil(d));let previous=safe(a.x,a.z);for(let i=1;i<=count;i++){const t=i/count,p=safe(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t);if(!p.ok||Math.abs(p.y-previous.y)>1.2)return false;previous=p;if(i%4===0)yield;}return true;}
 function* nearest(p){const at=index(p.x,p.z),x=at%n,z=Math.floor(at/n);let best=-1,distance=Infinity;for(let r=0;r<=4;r++){for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){const nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=n||nz>=n)continue;const i=nx+nz*n,q=point(i),d=Math.hypot(q.x-p.x,q.z-p.z);if(d<distance&&open(i)&&(yield* clearTask(p,q))){best=i;distance=d;}yield;}if(best>=0)return best;}return -1;}
 function* request(from,target){
  if(bridge!==navigationKey()){walk.fill(0);links.fill(0);bridge=navigationKey();}
  let goal=safe(target.x,target.z);if(!goal.ok){const radius=target.kind==='hunt'?1:3.2;for(let i=0;i<24;i++){const a=i*Math.PI/12,q=safe(target.x+Math.sin(a)*radius,target.z+Math.cos(a)*radius);if(q.ok){goal=q;break;}}}
  const start=safe(from.x,from.z);if(!start.ok)return[];if(goal.ok&&(yield* clearTask(start,goal)))return[start,goal];
  const a=yield* nearest(start),b=yield* nearest(goal);if(a<0||b<0)return[];cost.fill(Infinity);yield;came.fill(-1);closed.fill(0);cost[a]=0;
  const heap=[],push=(id,score)=>{let i=heap.length;heap.push({id,score});while(i){const p=(i-1)>>1;if(heap[p].score<=score)break;heap[i]=heap[p];i=p;}heap[i]={id,score};},pop=()=>{const first=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let c=i*2+1;if(c+1<heap.length&&heap[c+1].score<heap[c].score)c++;if(heap[c].score>=last.score)break;heap[i]=heap[c];i=c;}heap[i]=last;}return first.id;};
  const dest=point(b);push(a,0);let found=false,visited=0;while(heap.length&&visited++<size*3){const i=pop();if(closed[i])continue;if(i===b){found=true;break;}closed[i]=1;const x=i%n,z=Math.floor(i/n),p=point(i);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;const nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=n||nz>=n)continue;const j=nx+nz*n;if(closed[j]||!open(j))continue;const next=cost[i]+Math.hypot(dx,dz)*step;if(next>=cost[j])continue;const q=point(j),link=i*9+(dz+1)*3+dx+1;if(!links[link])links[link]=(yield* clearTask(p,q))?1:-1;if(links[link]<0)continue;cost[j]=next;came[j]=i;push(j,next+Math.hypot(q.x-dest.x,q.z-dest.z));}yield;}
  if(!found)return[];const path=[];for(let i=b;i>=0;i=came[i]){const p=point(i);path.push({x:p.x,y:heights[i],z:p.z});if(i===a)break;}path.reverse();path.unshift(start);if(goal.ok&&(yield* clearTask(path.at(-1),goal)))path.push(goal);
  const smooth=[path[0]];for(let i=0;i<path.length-1;){let j=Math.min(path.length-1,i+18);while(j>i+1&&!(yield* clearTask(path[i],path[j])))j--;smooth.push(path[j]);i=j;yield;}return smooth;
 }
 function route(from,target){const job=request(from,target);let result;do{result=job.next();}while(!result.done);return result.value;}
 return {route,request,safe,clear};
}
export function createGuideTrail(scene,resources,world){
 const planner=createRoutePlanner(world),material=resources.own(new THREE.MeshBasicMaterial({color:brand.colors.gold})),geometry=resources.own(new THREE.IcosahedronGeometry(.13,0)),trail=resources.own(new THREE.InstancedMesh(geometry,material,24)),ring=new THREE.Mesh(resources.own(new THREE.TorusGeometry(1.35,.075,4,32)),material),dummy=new THREE.Object3D();ring.rotation.x=-Math.PI/2;scene.add(trail,ring);let path=[],key='',age=3,time=0,job=null,cursor=1,maxSlice=0;const next=new THREE.Vector3();
 function distanceFromPath(p){const a=path[Math.max(0,cursor-1)],b=path[cursor];if(!a||!b)return Infinity;const dx=b.x-a.x,dz=b.z-a.z,t=THREE.MathUtils.clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/Math.max(.01,dx*dx+dz*dz),0,1);return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);}
 function update(dt,p,o,visible,reduceMotion){trail.visible=ring.visible=visible;if(!visible)return;time+=dt;age+=dt;const id=[o.kind,o.id||'',Math.round(o.x),Math.round(o.z),world.bridgeBuilt,world.reach?.navigationKey].join(':');if(id!==key||(!job&&age>2&&distanceFromPath(p)>8)){if(id!==key)path=[];job=o.airborne?null:planner.request({x:p.x,z:p.z},o);if(o.airborne){path=[{x:p.x,y:p.y+1,z:p.z},{x:o.x,y:o.y,z:o.z}];cursor=1;}key=id;age=0;}if(job){const begin=performance.now(),deadline=begin+1.5;do{const result=job.next();if(result.done){path=result.value;cursor=1;job=null;break;}}while(performance.now()<deadline);maxSlice=Math.max(maxSlice,performance.now()-begin);}while(cursor<path.length-1&&Math.hypot(path[cursor].x-p.x,path[cursor].z-p.z)<2.5)cursor++;const goal=path.at(-1)||{x:o.x,y:o.y??world.heightAt(o.x,o.z),z:o.z};ring.position.set(goal.x,goal.y+.13,goal.z);ring.rotation.set(o.airborne?0:-Math.PI/2,o.airborne?Math.atan2(o.x-p.x,o.z-p.z):0,0);ring.scale.setScalar(reduceMotion?1:1+Math.sin(time*2)*.055);next.set(path[cursor]?.x??o.x,0,path[cursor]?.z??o.z);let count=0,travel=1.7,segment=cursor,start={x:p.x,z:p.z};while(count<24&&segment<path.length){const end=path[segment],length=Math.hypot(end.x-start.x,end.z-start.z);if(length<travel){travel-=length;start=end;segment++;continue;}const t=travel/Math.max(.001,length),x=start.x+(end.x-start.x)*t,z=start.z+(end.z-start.z)*t,y=o.airborne?p.y+1+(o.y-p.y-1)*Math.min(1,Math.hypot(x-p.x,z-p.z)/Math.max(.1,Math.hypot(o.x-p.x,o.z-p.z))):world.groundAt(x,z,world.heightAt(x,z));dummy.position.set(x,y+.22+(reduceMotion?0:Math.sin(time*3-count*.5)*.035),z);dummy.rotation.set(0,Math.atan2(end.x-start.x,end.z-start.z),0);dummy.scale.set(.8,1,2);dummy.updateMatrix();trail.setMatrixAt(count++,dummy.matrix);travel+=1.7;}trail.count=count;trail.instanceMatrix.needsUpdate=true;}
 return {update,planner,get next(){return next;},get route(){return path;},get pending(){return !!job;},get maxSlice(){return maxSlice;},get count(){return trail.count;}};
}
