import {element,button} from './hud-kit.js';
import {harborDock as dock,harborRoutes,harborDecor} from './valley-harbor-data.js';
import {createHarborModel,cartOffset,throwFlight} from './valley-harbor-model.js';
export function createHarborDays({root,state,save,mover,panel,close,notify,audio}){
 const model=createHarborModel(state,()=>save.write()),d=model.data,overlay=element('section','v-harbor-play'),label=element('strong'),meter=element('div','v-harbor-meter'),zone=element('span','v-harbor-zone'),needle=element('i'),feedback=element('p'),throwButton=button('Toss parcel · E',()=>toss(),'pc-button pc-primary');
 meter.setAttribute('aria-hidden','true');meter.append(zone,needle);feedback.setAttribute('aria-live','polite');overlay.append(label,meter,feedback,throwButton,button('Leave challenge · keep supplies',()=>{model.pauseRound();overlay.hidden=true;root.classList.remove('v-harbor-playing');show();},'pc-button'));overlay.hidden=true;root.append(overlay);save.write();
 const distance=p=>Math.hypot(mover.player.position.x-p.x,mover.player.position.z-p.z);
 function track(){state.guideCategory='harbor';state.guideFocus='harbor-days';save.write();close();}
 function show(){const p=panel('Harbor Days');p.classList.add('v-harbor-panel');p.dataset.choiceMenu='true';p.append(element('p','v-eyebrow','SALVAGE · LOAD · MAKE IT YOURS'),element('p','',`${d.completed} harbor days hosted · ${d.tickets} festival tickets`),element('p','','Help prepare the dock for a neighborhood gathering. Find three marked supply crates, then land three of five parcels in the moving cart. Misses keep your supplies.'));
  if(d.active){p.append(element('p','v-guide-note',`${model.route.title} · ${d.active.collected.length} / 3 crates · ${d.active.secret?'keepsake found':'optional keepsake still hidden'}`),element('p','',model.route.clue),element('p','',model.route.secretClue));const ready=d.active.collected.length===3,near=distance(dock)<4.5;
   p.append(button(ready&&near?'Start cart challenge':ready?'Return to the loading dock':'Continue searching',()=>{track();if(ready&&near)model.startRound();},'pc-button pc-primary'));
  }else{p.append(element('p','v-guide-note',`Suggested today: ${harborRoutes[d.completed%3].title}. All three routes are always available.`));for(const r of harborRoutes){const card=element('article','v-harbor-card');card.append(element('strong','',r.title),element('p','',`${r.description} Best: ${d.best[r.id]} / 10.`),button('Choose '+r.title,()=>{if(model.begin(r.id)){track();notify(r.clue);}},'pc-button'));p.append(card);}}
  const guide=button('Precise trail: '+(d.precise?'ON':'OFF · use clues'),()=>{model.setPrecise(!d.precise);show();},'pc-button');guide.setAttribute('aria-pressed',String(d.precise));p.append(guide,element('h3','','Make the harbor yours'),element('p','v-small','Earn 2 tickets per completed run, +1 for 8 points, +1 for a keepsake. Tickets are local game rewards. Decorations stay after reload.'));
  for(const decor of harborDecor){const owned=d.decor.includes(decor.id),b=button(owned?decor.title+' · placed':decor.title+' · '+decor.cost+' tickets',()=>{if(model.buy(decor.id)){audio.sound('buy');notify(decor.title+' added to the harbor');show();}},'pc-button');b.disabled=owned||d.tickets<decor.cost;p.append(b,element('p','v-small',decor.description));}p.append(button('Back to adventure',close,'pc-button'));return p;
 }
 function nearby(){if(model.round)return {...dock,id:'harbor-toss',kind:'harbor',label:'Toss parcel'};const a=d.active,r=model.route;if(a&&r){for(let i=0;i<3;i++)if(!a.collected.includes(i)&&distance(r.points[i])<3)return {...r.points[i],id:'harbor-crate-'+i,kind:'harbor',label:'Collect supply crate'};if(!a.secret&&distance(r.secret)<2.5)return {...r.secret,id:'harbor-keepsake',kind:'harbor',label:'Find tucked-away keepsake'};}return distance(dock)<4?{...dock,id:'harbor-board',kind:'harbor',label:'Harbor Days board'}:null;}
 function objective(){const a=d.active,r=model.route;if(!a||a.collected.length===3)return {...dock,id:'harbor-board',kind:'harbor',label:model.round?'Load the cart · three hits from five throws':a?'Supplies ready · return to the Harbor Days dock':'Harbor Days · choose a route at the dock'};const next=r.points.find((p,i)=>!a.collected.includes(i));return {...next,id:'harbor-search',kind:'harbor',noTrail:!d.precise,label:`${a.collected.length} / 3 crates · ${d.precise?'Find the next blue supply crate':r.clue}`};}
 function toss(){if(overlay.hidden||!model.round)return;const result=model.toss();if(result)audio.sound(result.hit?'pickup':'jump');}
 function act(o=nearby()){if(!o||o.kind!=='harbor')return false;if(model.round){toss();return true;}if(o.id.startsWith('harbor-crate-')){if(model.collect(Number(o.id.slice(13)))){audio.sound('pickup');notify(d.active.collected.length===3?'SUPPLIES READY · Return to the harbor dock':`${d.active.collected.length} / 3 supply crates found`);}return true;}if(o.id==='harbor-keepsake'){if(model.collect('secret')){audio.sound('pickup');notify('KEEPSAKE FOUND · +1 ticket when you finish');}return true;}if(distance(dock)<4.5)show();return true;}
 function result(){const r=model.last,p=panel(r.success?'The harbor is ready!':'Another cart is coming');p.classList.add('v-harbor-panel');p.dataset.choiceMenu='true';p.append(element('p','v-eyebrow',`${r.hits} / 5 DELIVERIES · ${r.score} / 10 POINTS`),element('p','',r.success?`The neighbors have supplies for their gathering. You earned ${r.reward} festival tickets. Choose a decoration, or try another route.`:'No supplies lost. Watch where the marker will be when your parcel lands, and toss inside the center zone.'));
  if(!r.success)p.append(button('Retry with the same supplies',()=>{close();model.startRound();},'pc-button pc-primary'));p.append(button(r.success?'Decorate & choose another route':'Return to Harbor Days',show,'pc-button pc-primary'),button('Back to adventure',close,'pc-button'));
 }
 let lastFeedback='';
 function step(dt,active){if(model.round&&state.guideCategory!=='harbor')model.pauseRound();overlay.hidden=!active||!model.round;root.classList.toggle('v-harbor-playing',!overlay.hidden);if(!active||!model.round)return;if(distance(dock)>5){model.pauseRound();overlay.hidden=true;root.classList.remove('v-harbor-playing');notify('Challenge paused · supplies kept at the dock');return;}model.step(dt);if(!model.round){overlay.hidden=true;root.classList.remove('v-harbor-playing');result();return;}const r=model.round;label.textContent=`CART DELIVERY · ${r.hits} hits · ${r.throws} / 5 throws`;needle.style.left=(50+cartOffset(r.time+throwFlight)/3.6*46)+'%';throwButton.disabled=r.cooldown>0||r.throws>=5;throwButton.textContent=r.cooldown>0?'Parcel in flight…':'Toss parcel · E';if(lastFeedback!==r.feedback){feedback.textContent=r.feedback;lastFeedback=r.feedback;}}
 return {model,show,nearby,act,step,objective,get view(){return model.round?{...dock,id:'harbor-camera',key:'harbor'}:null;},entries(){return [{...dock,id:'harbor-days',title:'Harbor Days · repeatable routes & decorations',done:false,kind:'harbor',label:'Visit the Harbor Days loading dock'}];},dispose(){overlay.remove();root.classList.remove('v-harbor-playing');}};
}
