import * as THREE from 'three';
import {element,button} from './hud-kit.js';
import {createValleyExtras} from './valley-extras.js';
import {createValleyCampaign} from './valley-campaign.js';
import {markNext,watchGuidance,guideSelect} from './valley-guide.js';
import {createJourney} from './valley-journey.js';
import {createCinematicScene,updateCinematic,neighborEnding} from './valley-cinema.js';
import {brand} from './brand.js';
import {createPracticeWallet} from './valley-wallet.js';
import {openHarborSwap} from './valley-swap.js';
import {createAdventure} from './valley-adventure.js';
import {regions} from './valley-expedition-data.js';
import {districts,sideQuests,disclaimer} from './valley-data.js';
import {gameEnabled} from './game-availability.js';
import {createHudMarker} from './valley-marker.js';
import {createValleySkills} from './valley-skills.js';
const B=brand.colors;
export function createValleyStory(root,save,world,mover,hud,audio,camera,{onPhoto=()=>{},onSettings=()=>{},onGate=()=>{},onRestart=()=>location.reload()}={}){
 const old=save.state.profile.story;old.valley||={revision:1,chapter:-1,step:0,completed:[],feathers:[],hunt:[],visited:['plaza'],fieldGuide:{},side:{},scenes:[],position:null};const state=old.valley;for(const [key,value]of Object.entries({completed:[],feathers:[],hunt:[],visited:['plaza'],fieldGuide:{},side:{},scenes:[]}))state[key]??=value;save.write();world.setProgress(state.feathers.length);world.setCollected(state.hunt);
 const layer=element('section','v-layer'),edge=element('div','v-edge'),journalButton=button('Journal',()=>journal(),'pc-button'),hintButton=button('Guide',()=>journey.show(),'pc-button'),toolbar=element('div','v-toolbar'),toast=element('div','v-toast');toolbar.append(journalButton,hintButton,button('Wallet',()=>wallet.show(),'pc-button'),button('Map',()=>adventure.show(),'pc-button'),button('Photo',()=>{onPhoto();state.photoTaken=true;write();},'pc-button'),button('Pause',()=>pause(),'pc-button'));root.append(layer,toolbar,edge,toast);toast.hidden=true;edge.hidden=true;const stopGuidance=watchGuidance(layer),edgeLayout=createHudMarker(root,edge);
 let running=false,modal=false,scene=null,skip=0,skipHeld=false,age=0,idle=0,hints=0,sprint=null,toastAge=0,sideActive=state.activeSide||null,dialogueIndex=0,dialogueLines=[],dialogueDone=null;const projected=new THREE.Vector3(),target=new THREE.Vector3(),camPos=new THREE.Vector3(),camTarget=new THREE.Vector3();const sceneLog=[];
 function write(){state.activeSide=sideActive;save.write();}
 function notify(text){toast.textContent=text;toast.hidden=Boolean(scene);toastAge=scene?0:3;if(!scene&&text.length<30)hud.feedback('score',text);}
 function clearPanel(){layer.replaceChildren();modal=false;inputMode();}
 function close(){if(!running&&!scene){title();return;}clearPanel();}
 function inputMode(){mover.enabled=running&&!modal&&!scene;}
 function panel(title,closeFn=close){toast.hidden=true;toastAge=0;hud.reset();modal=true;inputMode();layer.replaceChildren();const p=element('section','v-panel'),header=element('div','v-panel-head');header.append(element('h2','',title),button('×',closeFn,'pc-button'));header.lastChild.setAttribute('aria-label','Close '+title);p.append(header);layer.append(p);return p;}
 function paragraph(p,text,cls=''){p.append(element('p',cls,text));}
 function choice(p,label,action,primary=false){p.append(button(label,action,'pc-button'+(primary?' pc-primary':'')));}
 function say(speaker,lines,done){dialogueIndex=0;dialogueLines=lines;dialogueDone=done;function draw(){const p=panel(speaker,()=>{close();dialogueDone?.();});paragraph(p,dialogueLines[dialogueIndex],'v-dialogue');choice(p,dialogueIndex===dialogueLines.length-1?'Continue →':'Next →',()=>{audio.sound('pickup');if(++dialogueIndex<dialogueLines.length)draw();else{close();dialogueDone?.();}},true);}draw();}
 function scenePlay(id,title,line,focus,duration,done){if(state.scenes.includes(id)){done?.();return;}close();scene=createCinematicScene(id,title,line,focus,duration,world);scene.done=done;scene.savedFov=camera.fov;hud.reset();toast.hidden=true;toastAge=0;hud.show(false);toolbar.hidden=true;for(const e of root.querySelectorAll('.pc-brandbar,.v-world-labels'))e.hidden=true;skip=0;skipHeld=false;inputMode();const bars=element('div','v-letterbox'),caption=element('section','v-caption'),speaker=element('small','v-cinema-speaker',title),text=element('p','',line),count=element('small','v-cinema-count');caption.append(speaker,text,count);scene.caption={speaker,text,count};const actions=element('div','v-cinema-actions'),next=button('Next moment →',()=>{if(scene.beat>=scene.beats.length-1)endScene();else scene.age=(scene.beat+1)*scene.duration/scene.beats.length+.001;},'pc-button v-cinema-next'),b=button('Hold to skip',()=>{},'pc-button v-skip');b.addEventListener('pointerdown',e=>{skipHeld=true;b.setPointerCapture(e.pointerId);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{skipHeld=false;skip=0;});actions.append(next,b);caption.append(actions);layer.append(bars,caption);audio.sound('buy');}
 function endScene(){const finished=scene;if(!finished)return;if(!state.scenes.includes(finished.id))state.scenes.push(finished.id);sceneLog.push(finished.id);scene=null;camera.fov=finished.savedFov;camera.updateProjectionMatrix();skipHeld=false;close();if(running){hud.show(true);toolbar.hidden=false;for(const e of root.querySelectorAll('.pc-brandbar,.v-world-labels'))e.hidden=false;}write();finished.done?.();}
 function mainObjective(){const play=adventure.mainObjective();if(play)return play;if(sprint)return {x:sprint.x,z:sprint.z,label:'Pulse Line Sprint finish',kind:'sprint'};if(state.chapter<0){if(state.step===0)return {x:0,z:29,label:'Meet Pulse Guy',kind:'pulse'};if(state.step===1){const p=mover.player,label=p.distance<5?'Move with WASD or the stick · travel five metres':p.jumps<1?'Jump · press Space or the Jump button':!state.dashed?'Sprint · hold Shift or the Sprint button':(state.glideTime||0)<.2?'Jump, then HOLD Space / Jump while falling to glide':'Walk through the arch · follow the gold trail';return {x:0,z:13,label,kind:'movement'};}return {x:-5,z:-14,label:'Meet Liberty in the plaza',kind:'liberty'};}if(state.chapter===0){if(state.step<2)return {x:33,z:-20,label:state.step===0?'Help Nessa at Swap Harbor':'Try the guided simulated swap',kind:'nessa'};return {x:36,z:-25,label:'Route the harbor cargo',kind:'route'};}if(state.chapter===1){if(state.step<2)return {x:-68,z:-15,label:'Help Liberty protect the courier',kind:'shield'};if(old.ghostMilestone)return {x:-68,z:-15,label:'Return to Liberty with the safe delivery',kind:'shield'};if(state.step===2)return {x:-61,z:-20,label:'Collect the sealed practice parcel',kind:'courier'};if(state.step===3)return {x:-87,z:-20,label:'Deliver along the sheltered path',kind:'courier'};return {x:-68,z:-15,label:'Return the delivery receipt to Liberty',kind:'shield'};}return campaign.objective();}
 function objective(){if(sprint)return mainObjective();return journey.objective()||extras.objective()||mainObjective();}
 function awardFeather(id,chapter){if(!state.feathers.includes(id)){wallet.reward(id,60,'Story feather · '+chapter);state.feathers.push(id);if(!state.completed.includes(chapter))state.completed.push(chapter);old.feathers||=[];old.completed||=[];if(!old.feathers.includes(id))old.feathers.push(id);if(!old.completed.includes(chapter))old.completed.push(chapter);save.state.profile.feathers+=25;save.state.profile.xp+=80;world.setProgress(state.feathers.length);write();notify('KNOWLEDGE FEATHER '+state.feathers.length+' · +25 Feathers');audio.sound('buy');}}
 function realCard(product,done=()=>{}){const d=districts.find(d=>d.id===product),p=panel('Ready for the real thing?',()=>{close();done();});paragraph(p,'You practiced '+d.name+' with fictional balances. The real product has its own requirements; learn them before using it.');const link=element('a','pc-button pc-primary','Open actual product ↗');link.href=d.url;link.target='_blank';link.rel='noopener noreferrer';p.append(link);paragraph(p,disclaimer,'v-small');choice(p,'Save Field Guide and return',()=>{state.fieldGuide[product]={title:d.name,lesson:d.lesson,url:d.url};write();close();done();},true);}
 function chapterOneReward(){wallet.transact('harbor-delivery','Practice bridge supplies delivered',{pDAI:-wallet.wallet.balances.pDAI});awardFeather('feather-1','chapter-1');state.chapter=1;state.step=0;state.fieldGuide.harbor={title:'Swap Harbor',lesson:districts[1].lesson,url:districts[1].url};write();scenePlay('chapter-1-close','HOPE · The first color','One shore chose a destination. Two shores found each other.',{x:44,z:-20},20,()=>realCard('harbor'));}
 function routeChallenge(){const p=panel('The cargo has an intent');paragraph(p,'Deliver pDAI on PulseChain. Which route matches the destination?');choice(p,'pDAI · PulseChain',()=>{close();chapterOneReward();},true);choice(p,'USDC · Base',()=>{notify('That route changes the destination. Try pDAI on PulseChain.');});}
 function simSwap(){openHarborSwap({panel,wallet,done(){state.step=2;write();close();notify('INTENT ROUTED · Practice receipt saved in your wallet');}});}
 function shieldReward(){awardFeather('feather-2','chapter-2');state.chapter=2;state.step=0;state.fieldGuide.shield={title:'Shield Keep',lesson:districts.find(d=>d.id==='shield').lesson,url:districts.find(d=>d.id==='shield').url};write();scenePlay('chapter-2-close','SAFETY · A sheltered path','The package arrives. Along the quiet road, one light answers another.',{x:-68,z:-15},20,()=>realCard('shield'));}
 function shieldSim(){let phase=0;const p=panel('Shield / Railgun · SIMULATED'),hint=element('p','v-sim-hint'),form=element('div','v-sim-form'),row=element('label'),select=element('select'),status=element('p','v-sim-status');for(const v of ['Choose visibility','Public','Private'])select.append(element('option','',v));row.append(element('span','','Package visibility'),select);row.className='v-spotlight';form.append(row);p.append(hint,form,status);hint.textContent='Tap here: choose Private to hide the fictional package route.';const next=button('Continue',()=>{if(phase===0&&select.value!=='Private'){status.textContent='Public is exposed. Choose Private for this practice parcel.';return;}if(phase===0){phase=1;select.disabled=true;row.classList.remove('v-spotlight');hint.textContent='Private uses the Shield / Railgun route in this simulation. No wallet is connected.';status.textContent='Private route ready. Carry the sealed parcel along the sheltered path in Liberty Valley.';next.textContent='Take the courier challenge';next.classList.add('v-spotlight');}else{state.step=2;write();close();notify('SEALED PARCEL · Follow the Valley beacon');}},'pc-button pc-primary');p.append(next);guideSelect(p,select,'Private',next);paragraph(p,disclaimer,'v-small');}
 function shieldAct(){if(state.step>=2){if(old.ghostMilestone||state.step>=4)shieldReward();else say('Liberty',['Your practice parcel is ready beside the sheltered path.','Follow the gold beacon, deliver it here in the Valley, then bring back the receipt.'],()=>{});return;}if(state.step===0)scenePlay('chapter-2-open','SHIELD KEEP · The exposed parcel','A Watcher learns the route before the courier takes the first step.',{x:-68,z:-15},18,()=>say('Liberty',['A Public route is quick to announce itself. Sometimes that invites a watcher.','Private takes more care. Shield and Railgun are the lesson; this parcel is only practice.'],()=>{state.step=1;write();shieldSim();}));else shieldSim();}
 function prologueAct(){if(state.step===0)say('Pulse Guy',["Hey, my guy. Those toll gates don't get to choose our whole day.","Come on. Run, jump, sprint and hold Jump on the way down to glide."],()=>{state.step=1;write();});else if(state.step===2)say('Liberty',["A small tail can cast a very brave shadow.","Nessa is waiting at the harbor. Follow the pulse line; she needs a second shore."],()=>{state.completed.push('prologue');old.completed||=[];if(!old.completed.includes('prologue'))old.completed.push('prologue');state.chapter=0;state.step=0;write();});else hint();}
 function nessaAct(){if(state.step===0)scenePlay('chapter-1-open','SWAP HARBOR · Stranded shores',"Nessa's bridge supplies wait on the wrong shore.",{x:44,z:-20},16,()=>say('Nessa',["I tried to plan every turn. The cargo is still over there.","Tell the route what you have, what you want and where it should arrive."],()=>{state.step=1;write();simSwap();}));else simSwap();}
 function pause(){if(!running)return;const p=panel('Paused');choice(p,'Resume',close,true);choice(p,'Settings',()=>onSettings(()=>pause()));choice(p,'Quest Journal',journal);choice(p,'Start Over',()=>restartPanel(pause));choice(p,'Main menu',title);paragraph(p,disclaimer,'v-small');}
 function title(){running=false;clearPanel();toolbar.hidden=true;hud.show(false);const p=panel('LIBERTY VALLEY',()=>{});p.classList.add('v-title');paragraph(p,'PCOCK · Feathers of Liberty','v-eyebrow');paragraph(p,'Seven story feathers. Three frontier regions. Nine new expeditions. Run, glide, solve and bring the roads back to life.');choice(p,state.completed.length?'CONTINUE ADVENTURE':'PLAY',start,true);choice(p,'Field Guide / Journal',journal);choice(p,'Settings',()=>onSettings(title));choice(p,'Start Over',()=>restartPanel(title));paragraph(p,disclaimer,'v-small');}
 function restartPanel(back){const p=panel('Start Over',back);paragraph(p,'Start the whole game from the beginning? Story, wallet, collectibles, Feathers, XP and both mini-game saves will start fresh. Graphics, sound and controls stay the same.');paragraph(p,'Your current game is backed up first. Restore Previous Game brings it back.');choice(p,'Keep playing',back,true);choice(p,'Start Over Again',()=>{if(!save.startOver()){notify(save.error);return;}reloadGame();});if(save.hasPrevious)choice(p,'Restore Previous Game',()=>{const q=panel('Restore Previous Game',()=>restartPanel(back));paragraph(q,'Restore the game saved before your last Start Over, including its quests, wallet, equipment and mini-game progress?');choice(q,'Keep current game',()=>restartPanel(back),true);choice(q,'Restore saved game',()=>{if(!save.restorePrevious()){notify(save.error);return;}reloadGame();});});}
 function reloadGame(){onRestart();}
 function start(){running=true;close();toolbar.hidden=false;hud.show(true);audio.unlock();if(!state.scenes.includes('opening'))scenePlay('opening','TOLL LANDS · A folded tail',"Every step had a price. Then someone stayed.",{x:0,z:30},18);else if(campaign.resume()){}else if(old.gaslessMilestone&&!state.scenes.includes('harbor-run'))scenePlay('harbor-run','NESSA · A route of your own','You named your destination, even while the road kept changing.',{x:44,z:-20},16,()=>say('Nessa',["You ran the route yourself. The destination stayed yours.","An intent describes the outcome. Gasless means the practice route covered the fee."],()=>realCard('harbor')));}
 function journal(){const p=panel('Quest Journal');paragraph(p,objective().label,'v-dialogue');paragraph(p,state.feathers.length+' / 7 story feathers · '+state.hunt.length+' / 100 hunt feathers · '+Object.values(state.side).filter(q=>q.done).length+' / 12 neighbor quests.');choice(p,'Guide every activity',()=>journey.show(),true);choice(p,'Frontier expeditions · nine new stories',adventure.show);choice(p,'Practice wallet & equipment',wallet.show);choice(p,'Skills & equipment',skills.show);choice(p,'Pulse Guy hint',hint);choice(p,'Liberty Academy',extras.academy);choice(p,'Secrets & Valley stories',extras.collection);choice(p,'Tail wardrobe',extras.wardrobe);choice(p,'Signal Tower',extras.signals);choice(p,'Follow the main story',()=>journey.main());choice(p,'All neighbor missions',()=>journey.show('neighbors'));choice(p,'Find every hunt feather',()=>journey.show('hunt'));for(const entry of Object.values(state.fieldGuide)){const section=element('article','v-guide-entry');section.append(element('strong','',entry.title),element('p','',entry.lesson));p.append(section);}if(sideActive)choice(p,'Return to main story guide',()=>journey.main());choice(p,'Feather Shrines',travel);choice(p,'Pulse Line Sprint',()=>{sprint={x:74,z:-20,age:0,par:24};close();notify('SPRINT · Follow the harbor pulse line');});choice(p,'Back to adventure',()=>{close();if(!running)start();},true);}
 function travel(){const p=panel('Feather Shrines');paragraph(p,'Visit a shrine to remember its route.');for(const shrine of world.shrines){const unlocked=state.visited.includes(shrine.id);const b=button(shrine.name+(unlocked?'':' · undiscovered'),()=>{if(!unlocked)return;mover.place(shrine.x+2,shrine.z);world.respawn.x=shrine.x+2;world.respawn.z=shrine.z;close();notify('SHRINE TRAVEL');},'pc-button');b.disabled=!unlocked;p.append(b);}}
 function hint(){const o=objective(),p=panel('Pulse Guy · Hint');const dx=o.x-mover.player.position.x,dz=o.z-mover.player.position.z;paragraph(p,["Follow the gold arrow and pink beacon, my guy. We're doing one thing at a time.",o.kind==='movement'?'Run at least five meters, jump once, dash, then hold Jump while falling to glide.':o.label+' · '+Math.round(Math.hypot(dx,dz))+' m away.',o.kind==='nessa'?'Find Nessa on the near shore; E or tap her bubble opens the swap lesson.':`Head ${dx>0?'east':'west'} and ${dz>0?'south':'north'}. The journal remembers the next step.`][Math.min(2,hints++)]);choice(p,'Got it',close,true);}
 function enterGate(gate){if(!gate||!gameEnabled(gate.id))return;state.position={x:mover.player.position.x,z:mover.player.position.z};write();onGate(gate);}
 function sideMenu(npc){const p=panel(npc.name);paragraph(p,world.weather==='rain'?'A little shelter makes a good meeting place.':save.state.profile.cosmetic!=='original'?'That new tail is hard to miss. Looking good!':'There is always something small we can do for a neighbor.');for(const q of sideQuests.filter(q=>q.giver===npc.name)){const s=state.side[q.id];choice(p,q.title+(s?.done?' · done':s?.stage?' · return':' · +8 Feathers'),()=>{if(s?.done)return;if(s?.stage){s.done=true;wallet.reward(q.id,20,q.title);save.state.profile.feathers+=q.reward;save.state.profile.xp+=20;sideActive=null;write();notify(q.title+' COMPLETE');scenePlay('neighbor-'+q.id,q.giver+' · '+q.title,neighborEnding(q),{x:npc.x??q.x,z:npc.z??q.z},10);return;}state.side[q.id]={stage:0,done:false};sideActive=q.id;state.guideCategory='neighbors';state.guideFocus=q.id;write();close();notify(q.description);},!s?.done&&(!sideActive||sideActive===q.id));}choice(p,'Skills & supply quests',skills.show);if(!sideQuests.some(q=>q.giver===npc.name))choice(p,'Thanks, neighbor',close,true);}
 function act(){if(modal||scene||!running)return;const p=mover.player.position,o=objective(),dist=Math.hypot(p.x-o.x,p.z-o.z);if(journey.interact(o))return;if(dist<4.5&&skills.act(o))return;if(dist<4.5){if(o.kind==='expedition')return adventure.act();if(o.kind==='worldplay'){notify('Walk through the gold ring to reach the next checkpoint.');return;}if(o.kind==='side-start')return sideMenu({name:sideQuests.find(q=>q.id===o.id).giver});if(o.kind==='hunt'){notify('Walk through the gold feather to collect it.');return;}if(o.kind==='shrine-guide'){travel();return;}if(o.kind==='pulse'||o.kind==='liberty')return prologueAct();if(o.kind==='nessa')return nessaAct();if(o.kind==='route')return routeChallenge();if(o.kind==='shield')return shieldAct();if(o.kind==='campaign')return campaign.act();if(o.kind==='courier'){state.step++;write();notify(state.step===3?'PARCEL COLLECTED · Follow the sheltered path':'DELIVERED · Bring the receipt to Liberty');return;}if(o.kind==='side'){const q=sideQuests.find(q=>q.id===o.id),s=state.side[q.id];if(!s.stage){s.stage=1;write();notify('FOUND · Return to '+q.giver);}else sideMenu({name:q.giver});return;}}
  if(extras.act())return;const resource=skills.nearby();if(resource&&skills.act(resource))return;const gate=world.gates.find(g=>Math.hypot(g.x-p.x,g.z-p.z)<4);if(gate){const panelNode=panel(gate.name);paragraph(panelNode,'Local best: '+save.state.games[gate.id].best);choice(panelNode,'Enter '+gate.name,()=>enterGate(gate),true);return;}
  const shrine=world.shrines.find(s=>Math.hypot(s.x-p.x,s.z-p.z)<3);if(shrine){if(!state.visited.includes(shrine.id))state.visited.push(shrine.id);world.respawn.x=shrine.x+2;world.respawn.z=shrine.z;write();travel();return;}
  const npc=world.npcs.find(n=>Math.hypot(n.x-p.x,n.z-p.z)<3.5);if(npc)return sideMenu(npc);hint();
 }
 hud.onPause(pause);hud.onFinish(act);root.querySelector('.pc-mission small').textContent='LIBERTY VALLEY';root.querySelector('[data-bubble]').textContent='Interact · E / tap';root.querySelector('.pc-hit-pips').hidden=true;
 const keyDown=e=>{if(e.code==='KeyE'&&!e.repeat&&!e.target.closest('input,select,textarea'))act();if(e.code==='Escape'){if(scene)skipHeld=true;else if(modal)close();else pause();}if(e.code==='KeyJ'&&!modal&&!scene)journal();if(e.code==='KeyH'&&!modal&&!scene)journey.show();},keyUp=e=>{if(e.code==='Escape'){skipHeld=false;skip=0;}};addEventListener('keydown',keyDown);addEventListener('keyup',keyUp);
 function update(dt){age+=dt;adventure.update(dt,running&&!modal&&!scene);extras.update(dt,running&&!modal&&!scene);if(toastAge>0){toastAge-=dt;if(toastAge<=0)toast.hidden=true;}if(scene){scene.age+=dt;if(skipHeld)skip+=dt;root.querySelector('.v-skip')?.style.setProperty('--skip',Math.min(1,skip/.65));const frame=updateCinematic(scene,camera,save.state.settings.reduceMotion);if(frame.index!==scene.beat){scene.beat=frame.index;scene.caption.speaker.textContent=frame.speaker;scene.caption.text.textContent=frame.text;scene.caption.count.textContent='Moment '+(frame.index+1)+' / '+scene.beats.length+' · Read, watch, or choose Next moment';}if(scene.age>=scene.duration||skip>=.65)endScene();return;}
  if(!running||modal)return;const p=mover.player;idle=p.speed>.2?0:idle+dt;if(idle>30){notify('NEXT · '+objective().label+' · Guide lists every activity');idle=0;}if(state.chapter<0&&state.step===1&&p.distance>=5&&p.jumps>=1&&state.dashed&&state.glideTime>=.2&&Math.hypot(p.position.x,p.position.z-13)<6){state.step=2;write();notify('WINGS FOUND · Meet Liberty');}if(p.gliding)state.glideTime=(state.glideTime||0)+dt;
  for(const f of world.collectibles)if(!f.collected&&Math.hypot(f.x-p.position.x,f.z-p.position.z)<1.25&&Math.abs(f.y-p.position.y-1)<2){f.collected=true;state.hunt.push(f.id);save.state.profile.feathers+=1;save.state.profile.xp+=2;write();audio.sound('pickup');notify('HUNT FEATHER '+state.hunt.length+' / 100');if(state.hunt.length%25===0)scenePlay('hunt-'+state.hunt.length,'THE FEATHER TRAIL · '+state.hunt.length+' / 100','Every little color belonged somewhere. You took the time to look.',{x:p.position.x,z:p.position.z},8);}
  for(const s of world.shrines)if(!state.visited.includes(s.id)&&Math.hypot(s.x-p.position.x,s.z-p.position.z)<3){state.visited.push(s.id);write();notify(s.name+' SHRINE DISCOVERED');}if(sprint){sprint.age+=dt;if(Math.hypot(sprint.x-p.position.x,sprint.z-p.position.z)<3){const best=sprint.age<=sprint.par;notify(best?'SPRINT GOLD · +15 Feathers':'SPRINT COMPLETE · +5 Feathers');save.state.profile.feathers+=best?15:5;save.state.profile.xp+=30;sprint=null;state.sprintComplete=true;write();}}
 }
 function drawGuide(planning=false){const o=objective(),p=mover.player.position;target.set(o.x,o.y??world.heightAt(o.x,o.z)+3,o.z);projected.copy(target).project(camera);const distance=Math.round(Math.hypot(o.x-p.x,o.z-p.z));root.querySelector('[data-mission]').textContent=o.label;root.querySelector('[data-tutorial]').textContent=(planning?'Finding a safe gold trail · ':sprint?Math.round(sprint.age)+' s · ':'')+(o.kind==='guide-menu'?'E / tap to open this activity':distance<5?(o.airborne?'Jump once, then hold W · automatic updraft glide':o.auto||o.kind==='worldplay'?'Move through the gold ring':o.kind==='hunt'?'Walk into the feather to collect it':'E / tap · interact with the yellow-ringed target'):distance+' m · follow the gold trail')+' · H Guide';for(const [key,needed]of [['jump',o.kind==='movement'&&(mover.player.jumps<1||(state.glideTime||0)<.2)],['dash',o.kind==='movement'&&!state.dashed]])root.querySelector('[data-'+key+']')?.classList.toggle('v-ability-guide',needed&&!modal&&!scene);const visible=projected.z<1&&Math.abs(projected.x)<.92&&Math.abs(projected.y)<.8;edge.hidden=!running||Boolean(scene)||modal||visible;edge.textContent='❧ '+distance+' m';edgeLayout.place(THREE.MathUtils.clamp((projected.x*.5+.5)*innerWidth,45,innerWidth-80),THREE.MathUtils.clamp((-projected.y*.5+.5)*innerHeight,130,innerHeight-170));
  const near=distance<5,gate=world.gates.find(g=>Math.hypot(g.x-p.x,g.z-p.z)<4),npc=world.npcs.find(n=>Math.hypot(n.x-p.x,n.z-p.z)<3.5),shrine=world.shrines.find(s=>Math.hypot(s.x-p.x,s.z-p.z)<3);const bubble=near?o:skills.nearby()||gate||npc||shrine;if(bubble&&running&&!modal&&!scene){projected.set(bubble.x,world.heightAt(bubble.x,bubble.z)+3.7,bubble.z).project(camera);const b=root.querySelector('[data-bubble]'),width=b.offsetWidth||220,height=b.offsetHeight||48;hud.setBubble(THREE.MathUtils.clamp((projected.x*.5+.5)*innerWidth-width/2,10,Math.max(10,innerWidth-width-10)),THREE.MathUtils.clamp((-projected.y*.5+.5)*innerHeight-height-18,12,innerHeight-height-160),projected.z<1);root.querySelector('[data-bubble]').textContent=(bubble.name||bubble.label||'Interact')+' · E / tap';root.querySelector('[data-bubble]').classList.toggle('v-ability-guide',near);}else hud.setBubble(0,0,false);
  const ctx=root.querySelector('[data-minimap]').getContext('2d');ctx.fillStyle=B.surface;ctx.fillRect(0,0,96,96);ctx.strokeStyle=B.primary;ctx.lineWidth=1;for(const d of [...districts,...regions]){ctx.beginPath();ctx.moveTo(48,48);ctx.lineTo(48+d.x*.07,48+d.z*.07);ctx.stroke();ctx.fillStyle=B.accent;ctx.fillRect(46+d.x*.07,46+d.z*.07,4,4);}ctx.fillStyle=B.gold;ctx.beginPath();ctx.arc(48+p.x*.07,48+p.z*.07,3,0,6.28);ctx.fill();ctx.strokeStyle=B.text;ctx.strokeRect(45+o.x*.07,45+o.z*.07,6,6);
 }
 const wallet=createPracticeWallet({state,save,panel,mover,notify});
 const adventure=createAdventure({root,state,save,world,mover,panel,close,notify,scenePlay,wallet,onRunner:()=>enterGate(world.gates.find(g=>g.id==='gasless-run'))});
 const campaign=createValleyCampaign({state,save,world,panel,close,say,scenePlay,awardFeather,realCard,notify});
 const extras=createValleyExtras({root,state,save,mover,panel,close,notify,scenePlay,onTrack:s=>journey.select('discoveries',s.id),onMission:()=>journey.show('neighbors')});
 const skills=createValleySkills({state,save,world,mover,panel,close:()=>{close();if(!running)start();},notify,audio,wallet});
 const journey=createJourney({skills,adventure,state,save,world,mover,panel,close,notify,mainObjective,followSide:id=>{sideActive=id;state.activeSide=id;save.write();},followSecret:s=>extras.follow(s),clearTargets(){sideActive=null;state.activeSide=null;extras.clearTarget();},extras:{...extras,travel},onSprint(){sprint={x:74,z:-20,age:0,par:24};close();notify('SPRINT · Follow the gold trail to the harbor');},onPhoto(){onPhoto();state.photoTaken=true;write();}});
 const saved=state.position;if(saved)mover.place(saved.x,saved.z);else mover.place(0,35);title();
 return {start,title,act,update,drawGuide,objective,journey,wallet,adventure,skills,get cinematicFrame(){return scene?.frame||null;},scenePlay,awardFeather,realCard,journal,notify,close,say,panel,get state(){return state;},get active(){return running&&!modal&&!scene;},get running(){return running;},get modal(){return modal;},get cinematic(){return scene?.id||null;},get sceneFocus(){return scene?.focus||null;},get sceneLog(){return sceneLog;},onAction(type){if(type==='dash')state.dashed=true;},savePosition(){state.position={x:mover.player.position.x,z:mover.player.position.z};write();},dispose(){stopGuidance();edgeLayout.dispose();extras.dispose();adventure.dispose();removeEventListener('keydown',keyDown);removeEventListener('keyup',keyUp);layer.remove();toolbar.remove();edge.remove();toast.remove();}};
}
